/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbstock;

import com.sun.awt.AWTUtilities;
import static dbstock.Inicio.milogo;
import static dbstock.metodos.st;
import java.awt.Image;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Derlis
 */
public class apariencia extends javax.swing.JFrame {

    /**
     * Creates new form apariencia
     */
     private FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos con Extension JPG y PNG", "jpg", "png");
    public apariencia() {
       // this.setUndecorated(true);
        initComponents();
        
     //   Shape forma = new RoundRectangle2D.Double(0,0,this.getBounds().width,this.getBounds().height,35,35);
      //  AWTUtilities.setWindowShape(this, forma);
        
        this.setLocationRelativeTo(null);//centra el formulario
        this.setTitle("Apariencia");
        setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE); //inabilida el uso del boton exit X
        this.setResizable(false); //Disable the Resize Button
        
        
        	Conexion cc=new Conexion();
		Connection con=cc.conectar();;
        	try {

		//String sql = "Select * from config where conf_ruc = '"+config.conf_ruc.getText()+"'";
		String sql = "Select * from apariencia ";
                st = con.createStatement();
                ResultSet rs=st.executeQuery(sql);
		if (rs.next()) {
                         menu.setText(rs.getString("apa_id"));
                         nombre_logo.setText(rs.getString("apa_nombremenu"));
                         url_logo.setText(rs.getString("apa_urlmenu"));
                         nombre_logo2.setText(rs.getString("apa_nombresubmenu"));
                         url_logo2.setText(rs.getString("apa_urlsubmenu"));

                         ///////////////////////////////////////////////mostrar imagenes en pantalla
                                String url = (rs.getString("apa_urlmenu"));
                                ImageIcon fot = new ImageIcon(url);
                                Icon icono = new ImageIcon(fot.getImage().getScaledInstance(logo_principal.getWidth(), logo_principal.getHeight(), Image.SCALE_DEFAULT));
                                logo_principal.setIcon(icono);
                                logo_principal.repaint();
                          //////////////////////////////////////////////////////fin mostrar pantalla
                          
                                ///////////////////////////////////////////////mostrar imagenes en pantalla
                                String url1 = (rs.getString("apa_urlsubmenu"));
                                ImageIcon fot1 = new ImageIcon(url1);
                                Icon icono1 = new ImageIcon(fot1.getImage().getScaledInstance(logo_principal2.getWidth(), logo_principal2.getHeight(), Image.SCALE_DEFAULT));
                                logo_principal2.setIcon(icono1);
                                logo_principal2.repaint();
                          //////////////////////////////////////////////////////fin mostrar pantalla

                    }
		

		} catch (SQLException e) {
			JOptionPane.showMessageDialog(null, e.getMessage());
		}
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guardar_submenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        guardar_menu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        url_logo = new javax.swing.JTextField();
        nombre_logo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        url_logo2 = new javax.swing.JTextField();
        nombre_logo2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        logo_principal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logo_principal2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        menu = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(710, 530));
        setPreferredSize(new java.awt.Dimension(730, 530));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        guardar_submenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        guardar_submenu.setText("Guardar");
        guardar_submenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_submenuActionPerformed(evt);
            }
        });
        getContentPane().add(guardar_submenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("APARIENCIAS DEL SISTEMA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 380, 20));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Examinar IMG");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 130, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sub Menu");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 110, 20));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Examinar IMG");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 40));

        guardar_menu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        guardar_menu.setText("Guardar");
        guardar_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_menuActionPerformed(evt);
            }
        });
        getContentPane().add(guardar_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 90, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Menu Principal");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, 20));

        url_logo.setEnabled(false);
        getContentPane().add(url_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 220, -1));

        nombre_logo.setEnabled(false);
        getContentPane().add(nombre_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 220, -1));

        jLabel6.setText("URL:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 40, 20));

        jLabel7.setText("Nombre:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 50, 20));

        url_logo2.setEnabled(false);
        getContentPane().add(url_logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 220, -1));

        nombre_logo2.setEnabled(false);
        getContentPane().add(nombre_logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 220, -1));

        jLabel8.setText("URL:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 40, 20));

        jLabel9.setText("Nombre:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 50, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 660, 10));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/exit.png"))); // NOI18N
        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 110, 40));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo_principal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo_principal.setText("IMG");
        jPanel1.add(logo_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 310, 180));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo_principal2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo_principal2.setText("IMG2");
        jPanel2.add(logo_principal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 160));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 310, 180));

        jSeparator2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 680, 10));

        menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu.setText("1");
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 50, 20));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/reload.png"))); // NOI18N
        jButton6.setText("Aplicar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/fondosistema.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        		
         try {
             st.close();
         } catch (SQLException ex) {
             Logger.getLogger(apariencia.class.getName()).log(Level.SEVERE, null, ex);
         }
		
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
         JFileChooser filechoose = new JFileChooser();
        filechoose.setFileFilter(filter);
        int opcion = filechoose.showOpenDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION) {
            //OBTENER EL NOMBRE DEL ARCHIVO SELECCIONADO
            String nombre_archivo = filechoose.getSelectedFile().getName();
            //OBTENER LA RUTA DEL ARCHIVO SELECCIONADO
            String ruta = filechoose.getSelectedFile().getPath();
            //seteamos el nombre del archivo
            nombre_logo.setText(nombre_archivo);
            //seteamos la ruta
            url_logo.setText(ruta);       
            logo_principal.setIcon(new ImageIcon(ruta));
            
        
        ImageIcon fot = new ImageIcon(ruta);
        Icon icono = new ImageIcon(fot.getImage().getScaledInstance(logo_principal.getWidth(), logo_principal.getHeight(), Image.SCALE_DEFAULT));
        logo_principal.setIcon(icono);
        this.repaint();
   
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
            JFileChooser filechoose = new JFileChooser();
        filechoose.setFileFilter(filter);
        int opcion = filechoose.showOpenDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION) {
            //OBTENER EL NOMBRE DEL ARCHIVO SELECCIONADO
            String nombre_archivo = filechoose.getSelectedFile().getName();
            //OBTENER LA RUTA DEL ARCHIVO SELECCIONADO
            String ruta = filechoose.getSelectedFile().getPath();
            //seteamos el nombre del archivo
            nombre_logo2.setText(nombre_archivo);
            //seteamos la ruta
            url_logo2.setText(ruta);       
            logo_principal2.setIcon(new ImageIcon(ruta));
            
        
        ImageIcon fot = new ImageIcon(ruta);
        Icon icono = new ImageIcon(fot.getImage().getScaledInstance(logo_principal2.getWidth(), logo_principal2.getHeight(), Image.SCALE_DEFAULT));
        logo_principal2.setIcon(icono);
        this.repaint();
   
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       
        JOptionPane.showMessageDialog(null,  "Modulo en Proceso, aún no aplica", "Apariencia", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void guardar_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_menuActionPerformed
        
            Conexion cc=new Conexion();
            Connection con=cc.conectar();
            try {

                String sql = "UPDATE apariencia SET apa_nombremenu = '"+nombre_logo.getText()+"', apa_urlmenu = '"+url_logo.getText()+"'"
                + " where apa_id = '"+menu.getText()+"'";

                st = con.createStatement();
                st.execute(sql);
                
                JOptionPane.showMessageDialog(null,  "Imagen de Menú Actualizado", "Apariencia", JOptionPane.INFORMATION_MESSAGE);
                
            } catch (SQLException ex) {
                System.out.println("ver error " + ex.getMessage());
            }
        
    }//GEN-LAST:event_guardar_menuActionPerformed

    private void guardar_submenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_submenuActionPerformed
            Conexion cc=new Conexion();
            Connection con=cc.conectar();
            try {

                String sql5 = "UPDATE apariencia SET apa_nombresubmenu = '"+nombre_logo2.getText()+"', apa_urlsubmenu = '"+url_logo2.getText()+"'"
                + " where apa_id = '"+menu.getText()+"'";

                st = con.createStatement();
                st.execute(sql5);
                
                JOptionPane.showMessageDialog(null,  "Imagen de Sub Menú Actualizado", "Apariencia", JOptionPane.INFORMATION_MESSAGE);
                
            } catch (SQLException ex) {
                System.out.println("ver error " + ex.getMessage());
            }
            
    }//GEN-LAST:event_guardar_submenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(apariencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(apariencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(apariencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(apariencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new apariencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guardar_menu;
    private javax.swing.JButton guardar_submenu;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo_principal;
    private javax.swing.JLabel logo_principal2;
    private javax.swing.JLabel menu;
    private javax.swing.JTextField nombre_logo;
    private javax.swing.JTextField nombre_logo2;
    private javax.swing.JTextField url_logo;
    private javax.swing.JTextField url_logo2;
    // End of variables declaration//GEN-END:variables
}
