/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbstock;

import static dbstock.Conexion.conn;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Derlis
 */
public class base_datos extends javax.swing.JFrame {

    /**
     * Creates new form base_datos
     */
    public static Connection conn;
    Statement st;
    Connection con;
    private FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos con Extension TXT y CSV", "csv", "txt");

    public base_datos() {
        initComponents();

        this.setLocationRelativeTo(null);//centra el formulario
        this.setTitle("BASE DE DATOS");
        setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE); //inabilida el uso del boton exit X
        this.setResizable(false); //Disable the Resize Button

        btn_base.setVisible(false);
        btn_ELIMINAR_TABLAS.setVisible(false);
        txt_pas.setVisible(false);
        txt_ruta1.setEnabled(false);
        btn_tablas1.setVisible(false);
        
        txt_suc.setEnabled(false);
        txt_caja.setEnabled(false);
        txt_host.setEnabled(false);
        txt_db.setEnabled(false);
        txt_contra.setEnabled(false);
        btn_txtcaja.setEnabled(false);
        btn_txthost.setEnabled(false);
        btn_txt_exa.setEnabled(false);
        jInternalFrame1.setVisible(false);
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        detpresupuesto = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        venta = new javax.swing.JCheckBox();
        detallevta = new javax.swing.JCheckBox();
        tmpdetallevta = new javax.swing.JCheckBox();
        cobranza = new javax.swing.JCheckBox();
        detcobranza = new javax.swing.JCheckBox();
        contador = new javax.swing.JCheckBox();
        detallespedido = new javax.swing.JCheckBox();
        gastos = new javax.swing.JCheckBox();
        ingreso = new javax.swing.JCheckBox();
        movimiento_caja = new javax.swing.JCheckBox();
        pedido = new javax.swing.JCheckBox();
        presupuesto = new javax.swing.JCheckBox();
        tmpedido = new javax.swing.JCheckBox();
        clientes = new javax.swing.JCheckBox();
        cotizar = new javax.swing.JCheckBox();
        proveedores = new javax.swing.JCheckBox();
        productos = new javax.swing.JCheckBox();
        cja = new javax.swing.JCheckBox();
        privilegios = new javax.swing.JCheckBox();
        config = new javax.swing.JCheckBox();
        grupopro = new javax.swing.JCheckBox();
        sucursal = new javax.swing.JCheckBox();
        usuarios = new javax.swing.JCheckBox();
        jButton7 = new javax.swing.JButton();
        apariencia = new javax.swing.JCheckBox();
        tmpdetpresu = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btn_base = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_ELIMINAR_TABLAS = new javax.swing.JButton();
        btn_avan = new javax.swing.JButton();
        btn_tablas1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt_pas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jpane_txt = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_caja = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_ruta1 = new javax.swing.JTextField();
        btn_txt_exa = new javax.swing.JButton();
        txt_db = new javax.swing.JTextField();
        txt_host = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        hos_txt = new javax.swing.JLabel();
        caja = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_suc = new javax.swing.JTextField();
        btn_txthost = new javax.swing.JButton();
        btn_txtcaja = new javax.swing.JButton();
        txt_contra = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(742, 493));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Fijos");
        jInternalFrame1.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 40, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Vaciar Tablas de la base de datos");
        jInternalFrame1.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Movimientos");
        jInternalFrame1.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        detpresupuesto.setText("detpresupuesto");
        jInternalFrame1.getContentPane().add(detpresupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        venta.setText("Venta");
        jInternalFrame1.getContentPane().add(venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        detallevta.setText("detallevta");
        jInternalFrame1.getContentPane().add(detallevta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        tmpdetallevta.setText("tmpdetallevta");
        jInternalFrame1.getContentPane().add(tmpdetallevta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        cobranza.setText("cobranza");
        jInternalFrame1.getContentPane().add(cobranza, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        detcobranza.setText("detcobranza");
        jInternalFrame1.getContentPane().add(detcobranza, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        contador.setText("contador");
        contador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contadorActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(contador, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        detallespedido.setText("detallespedido");
        jInternalFrame1.getContentPane().add(detallespedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        gastos.setText("gastos");
        jInternalFrame1.getContentPane().add(gastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        ingreso.setText("ingreso");
        jInternalFrame1.getContentPane().add(ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        movimiento_caja.setText("movimiento_caja");
        jInternalFrame1.getContentPane().add(movimiento_caja, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        pedido.setText("pedido");
        jInternalFrame1.getContentPane().add(pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        presupuesto.setText("presupuesto");
        jInternalFrame1.getContentPane().add(presupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        tmpedido.setText("tmpedido");
        jInternalFrame1.getContentPane().add(tmpedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        clientes.setText("clientes");
        jInternalFrame1.getContentPane().add(clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        cotizar.setText("cotizar");
        jInternalFrame1.getContentPane().add(cotizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        proveedores.setText("proveedores");
        jInternalFrame1.getContentPane().add(proveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        productos.setText("productos");
        jInternalFrame1.getContentPane().add(productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        cja.setText("caja");
        jInternalFrame1.getContentPane().add(cja, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        privilegios.setText("privilegios");
        jInternalFrame1.getContentPane().add(privilegios, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        config.setText("config");
        jInternalFrame1.getContentPane().add(config, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        grupopro.setText("grupopro");
        jInternalFrame1.getContentPane().add(grupopro, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        sucursal.setText("sucursal");
        jInternalFrame1.getContentPane().add(sucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        usuarios.setText("usuarios");
        jInternalFrame1.getContentPane().add(usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setText("Vaciar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 240, 90, -1));

        apariencia.setText("apariencia");
        jInternalFrame1.getContentPane().add(apariencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        tmpdetpresu.setText("tmpdetpresu");
        jInternalFrame1.getContentPane().add(tmpdetpresu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 470, 300));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("BASE DE DATOS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/exit.png"))); // NOI18N
        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 110, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Restaurar Sistema");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 160, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Backup");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Realizar Backup");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 160, 40));

        jButton5.setText("Examinar");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 280, -1));

        jButton6.setText("Examinar");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 80, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 280, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 410, 10));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_base.setText("Crear BD");
        btn_base.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_baseActionPerformed(evt);
            }
        });
        jPanel1.add(btn_base, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 120, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Crear Base de Datos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Eliminar Datos de las Tablas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        btn_ELIMINAR_TABLAS.setText("Eliminar Tablas");
        btn_ELIMINAR_TABLAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ELIMINAR_TABLASActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ELIMINAR_TABLAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 140, 30));

        btn_avan.setText("Configuraciones Avanzadas");
        btn_avan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_avanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_avan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, 40));

        btn_tablas1.setText("Crear Tablas");
        btn_tablas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tablas1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_tablas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 120, 30));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_pas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_pas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_pas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pasKeyPressed(evt);
            }
        });
        jPanel2.add(txt_pas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 180, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 200, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Crear Tablas");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 240, 300));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 410, 10));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Restaurar Respaldo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jpane_txt.setBackground(new java.awt.Color(204, 204, 204));
        jpane_txt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Crear Caja");
        jpane_txt.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txt_caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cajaActionPerformed(evt);
            }
        });
        jpane_txt.add(txt_caja, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 50, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("url");
        jpane_txt.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));
        jpane_txt.add(txt_ruta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 320, -1));

        btn_txt_exa.setText("Examinar");
        btn_txt_exa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_txt_exaActionPerformed(evt);
            }
        });
        jpane_txt.add(btn_txt_exa, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));
        jpane_txt.add(txt_db, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 100, -1));
        jpane_txt.add(txt_host, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 100, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Host:");
        jpane_txt.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("BD:");
        jpane_txt.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, 20));

        hos_txt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hos_txt.setText("host.txt");
        jpane_txt.add(hos_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        caja.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        caja.setText("caja.txt");
        jpane_txt.add(caja, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Crear Nro Suc.");
        jpane_txt.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        jpane_txt.add(txt_suc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 50, -1));

        btn_txthost.setText("Crear host");
        btn_txthost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_txthostActionPerformed(evt);
            }
        });
        jpane_txt.add(btn_txthost, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 107, -1, -1));

        btn_txtcaja.setText("Crear caja");
        btn_txtcaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_txtcajaActionPerformed(evt);
            }
        });
        jpane_txt.add(btn_txtcaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        jpane_txt.add(txt_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 100, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Contraseña:");
        jpane_txt.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, 20));

        getContentPane().add(jpane_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 460, 170));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/fondosistema.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_baseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_baseActionPerformed
       /*
        ------ejecutar script desde java
-- Database: dbstock

-- DROP DATABASE dbstock;

CREATE DATABASE dbstock
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Spanish_Mexico.1252'
    LC_CTYPE = 'Spanish_Mexico.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
        
        */

    }//GEN-LAST:event_btn_baseActionPerformed

    private void btn_ELIMINAR_TABLASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ELIMINAR_TABLASActionPerformed

        int aux  =  JOptionPane.showConfirmDialog(null, "Desea Eliminar todas las tablas","OBSERVACION", JOptionPane.YES_NO_OPTION);
        if(aux == JOptionPane.YES_OPTION){
           
            String respuesta = JOptionPane.showInputDialog("Ingresar Contraseña");
            
            if ("dbstock14512".equals(respuesta)) {
                 jInternalFrame1.setVisible(true);
            }else
            {
                JOptionPane.showMessageDialog(null, "Contraseña Equivocada");
            }
                
        }
        
       

    }//GEN-LAST:event_btn_ELIMINAR_TABLASActionPerformed

    private void btn_avanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_avanActionPerformed

        txt_pas.setVisible(true);
        txt_pas.requestFocus();


    }//GEN-LAST:event_btn_avanActionPerformed

    private void txt_pasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pasKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
           // int contra = 14512;
            
            String pass = txt_pas.getText();
            int contrase = parseInt(pass);
            
            if (contrase == 14512) {

                btn_base.setVisible(true);
                btn_ELIMINAR_TABLAS.setVisible(true);
                txt_pas.setVisible(false);
                btn_avan.setEnabled(false);
                
                txt_suc.setEnabled(true);
                txt_caja.setEnabled(true);
                txt_host.setEnabled(true);
                txt_db.setEnabled(true);
                txt_contra.setEnabled(true);
                btn_txtcaja.setEnabled(true);
                btn_txthost.setEnabled(true);
                btn_txt_exa.setEnabled(true);
                btn_ELIMINAR_TABLAS.setVisible(true);
                btn_tablas1.setVisible(true);

            }else{
                JOptionPane.showMessageDialog(null, "Contraseña ingresada es INCORRECTA, Ingrese Contraseña Unica");
            }

        }
    }//GEN-LAST:event_txt_pasKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            backup.backup();
        } catch (Exception e) {
        }
        
        try
        {
           /* directorio/ejecutable es el path del ejecutable y un nombre */
           Runtime.getRuntime().exec("cmd /c start C:\\Sistema\\dbstock\\cmbRespaldo.bat");
         
        }
        catch (Exception e)
        {
           /* Se lanza una excepción si no se encuentra en ejecutable o el fichero no es ejecutable. */
        }
//metobackup.BaseDatos.class.getMethods();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn_txthostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_txthostActionPerformed

    if ( txt_ruta1.getText().isEmpty() ) {
        
        JOptionPane.showMessageDialog(null, "Favor Examine dirección a ser creado el fichero");
            
    }else{
        
        String hos = hos_txt.getText();
        String ruta = txt_ruta1.getText();
        try {
        File archivo = new File(""+ruta+"\\"+hos+"");
        archivo.createNewFile();
       // System.out.println("se ha creado el archivo:"+archivo);
        BufferedWriter bw = null;

            if(archivo.exists()) {
            bw = new BufferedWriter(new FileWriter(archivo));
            bw.write("***HOST***");
            bw.newLine();
            bw.write(txt_host.getText());
            bw.newLine();
            bw.write("***BASE DE DATOS***");
            bw.newLine();
            bw.write(txt_db.getText());
            bw.newLine();
            bw.write("***CONTRASEÑA***");
            bw.newLine();
            bw.write(txt_contra.getText());
             JOptionPane.showMessageDialog(null, "El fichero de texto se creo exitosamente");
     
        } else {
            bw = new BufferedWriter(new FileWriter(archivo));
            bw.write("***HOST***");
            bw.newLine();
            bw.write(txt_host.getText());
            bw.newLine();
            bw.write("***BASE DE DATOS***");
            bw.newLine();
            bw.write(txt_db.getText());
            bw.newLine();
            bw.write("***CONTRASEÑA***");
            bw.newLine();
            bw.write(txt_contra.getText());
            
            JOptionPane.showMessageDialog(null, "El fichero de texto se actualizo exitosamente");
        }
        bw.close();
        } catch (IOException ex) {
                Logger.getLogger(base_datos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
        
    }//GEN-LAST:event_btn_txthostActionPerformed

    private void btn_txt_exaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_txt_exaActionPerformed

        
 JFileChooser chooser = new JFileChooser(); 
    chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); 
    int returnVal = chooser.showOpenDialog(this); 
    if(returnVal == JFileChooser.APPROVE_OPTION) { 

    txt_ruta1.setText(chooser.getSelectedFile().getAbsolutePath());
} 
        
    }//GEN-LAST:event_btn_txt_exaActionPerformed

    private void btn_txtcajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_txtcajaActionPerformed
         if ( txt_ruta1.getText().isEmpty() ) {
        
        JOptionPane.showMessageDialog(null, "Favor Examine dirección a ser creado el fichero");
            
    }else{
        
        String caj = caja.getText();
        String ruta = txt_ruta1.getText();
        try {
        File archivo = new File(""+ruta+"\\"+caj+"");
        archivo.createNewFile();
       // System.out.println("se ha creado el archivo:"+archivo);
        BufferedWriter bw = null;

            if(archivo.exists()) {
            bw = new BufferedWriter(new FileWriter(archivo));
            bw.write("***CAJA***");
            bw.newLine();
            bw.write(txt_caja.getText());
            bw.newLine();
            bw.write("***SUCURSAL***");
            bw.newLine();
            bw.write(txt_suc.getText());

 
             JOptionPane.showMessageDialog(null, "El fichero de texto se creo exitosamente");
     
        } else {
            bw = new BufferedWriter(new FileWriter(archivo));
            bw.write("***CAJA***");
            bw.newLine();
            bw.write(txt_caja.getText());
            bw.newLine();
            bw.write("***SUCURSAL***");
            bw.newLine();
            bw.write(txt_suc.getText());

            
            JOptionPane.showMessageDialog(null, "El fichero de texto se actualizo exitosamente");
        }
        bw.close();
        } catch (IOException ex) {
                Logger.getLogger(base_datos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    }//GEN-LAST:event_btn_txtcajaActionPerformed

    private void txt_cajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cajaActionPerformed

    private void btn_tablas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tablas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tablas1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                btn_ELIMINAR_TABLAS.setVisible(false);
                btn_tablas1.setVisible(false);
                btn_base.setVisible(false);
                
                jInternalFrame1.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
                     
        int aux  =  JOptionPane.showConfirmDialog(null, "Desea Eliminar Datos?","OBSERVACION", JOptionPane.YES_NO_OPTION);
        if(aux == JOptionPane.YES_OPTION){

            Conexion cc=new Conexion();
            Connection con=cc.conectar();
            try {
                
                if(cja.isSelected()){          
                    String sql = "TRUNCATE TABLE caja RESTART IDENTITY";
                    st = con.createStatement();
                    st.execute(sql);
                    JOptionPane.showMessageDialog(null, "Tabla Caja Vacio");
                }
                
                if(clientes.isSelected()){            
                    String sql1 = "TRUNCATE TABLE clientes RESTART IDENTITY";
                    st = con.createStatement();
                    st.execute(sql1);
                    JOptionPane.showMessageDialog(null, "Tabla clientes Vacio");
                }
                
                if(cobranza.isSelected()){
                    String sql2 = "TRUNCATE TABLE cobranza RESTART IDENTITY";
                    st = con.createStatement();
                    st.execute(sql2);
                    JOptionPane.showMessageDialog(null, "Tabla cobranza Vacio");  
                }

                if(config.isSelected()){
                    String sql3 = "TRUNCATE TABLE config RESTART IDENTITY";
                    st = con.createStatement();
                    st.execute(sql3);
                    JOptionPane.showMessageDialog(null, "Tabla config Vacio");
                }  
              
                if(contador.isSelected()){
                    String sql4 = "TRUNCATE TABLE contador RESTART IDENTITY";
                    st = con.createStatement();
                    st.execute(sql4);
                    JOptionPane.showMessageDialog(null, "Tabla contador Vacio");
                }
                
                if(detallespedido.isSelected()){
                    String sql5 = "TRUNCATE TABLE detallespedido RESTART IDENTITY";
                    st = con.createStatement();
                    st.execute(sql5);
                    JOptionPane.showMessageDialog(null, "Tabla detallespedido Vacio");
                }
                
                if(cotizar.isSelected()){
                    String sql6 = "TRUNCATE TABLE cotizar RESTART IDENTITY";
                    st = con.createStatement();
                    st.execute(sql6);
                    JOptionPane.showMessageDialog(null, "Tabla cotizar Vacio");
                }
                
                if(detallevta.isSelected()){
                    String sql7 = "TRUNCATE TABLE detallevta RESTART IDENTITY";
                    st = con.createStatement();
                    st.execute(sql7);
                    JOptionPane.showMessageDialog(null, "Tabla detallevta Vacio");
                }
                
                if(detcobranza.isSelected()){
                    String sql8 = "TRUNCATE TABLE detcobranza RESTART IDENTITY";
                    st = con.createStatement();
                    st.execute(sql8);
                    JOptionPane.showMessageDialog(null, "Tabla detcobranza Vacio");
                }
                
                if(gastos.isSelected()){
                    String sql9 = "TRUNCATE TABLE gastos RESTART IDENTITY";
                    st = con.createStatement();
                    st.execute(sql9);
                    JOptionPane.showMessageDialog(null, "Tabla gastos Vacio");
                }
                
                if(grupopro.isSelected()){
                    String sql10 = "TRUNCATE TABLE grupopro RESTART IDENTITY";
                    st = con.createStatement();
                    st.execute(sql10);
                    JOptionPane.showMessageDialog(null, "Tabla grupopro Vacio");
                }
                
                if(ingreso.isSelected()){
                    String sql11 = "TRUNCATE TABLE ingreso RESTART IDENTITY";
                    st = con.createStatement();
                    st.execute(sql11);
                    JOptionPane.showMessageDialog(null, "Tabla ingreso Vacio");
                }
                
                if(movimiento_caja.isSelected()){
                    String sql12 = "TRUNCATE TABLE movimiento_caja RESTART IDENTITY";
                    st = con.createStatement();
                    st.execute(sql12);
                    JOptionPane.showMessageDialog(null, "Tabla movimiento_caja Vacio");
                }
                
                if(pedido.isSelected()){
                    String sql13 = "TRUNCATE TABLE pedido RESTART IDENTITY";
                    st = con.createStatement();
                    st.execute(sql13);
                    JOptionPane.showMessageDialog(null, "Tabla pedido Vacio");
                }
                
                if(privilegios.isSelected()){
                    String sql14 = "TRUNCATE TABLE privilegios RESTART IDENTITY";
                    st = con.createStatement();
                    st.execute(sql14);
                    JOptionPane.showMessageDialog(null, "Tabla privilegios Vacio");
                }
                
                if(productos.isSelected()){
                    String sql15 = "TRUNCATE TABLE productos RESTART IDENTITY";
                    st = con.createStatement();
                    st.execute(sql15);
                    JOptionPane.showMessageDialog(null, "Tabla productos Vacio");
                }
                
                if(proveedores.isSelected()){
                    String sql16 = "TRUNCATE TABLE proveedores RESTART IDENTITY";
                    st = con.createStatement();
                    st.execute(sql16);
                    JOptionPane.showMessageDialog(null, "Tabla proveedores Vacio");
                }
                
                if(sucursal.isSelected()){
                    String sql17 = "TRUNCATE TABLE sucursal RESTART IDENTITY";
                    st = con.createStatement();
                    st.execute(sql17);
                    JOptionPane.showMessageDialog(null, "Tabla sucursal Vacio");
                }
                
                if(tmpdetallevta.isSelected()){
                    String sql18 = "TRUNCATE TABLE tmpdetallevta RESTART IDENTITY";
                    st = con.createStatement();
                    st.execute(sql18);
                    JOptionPane.showMessageDialog(null, "Tabla tmpdetallevta Vacio");
                }

                if(tmpedido.isSelected()){
                    String sql19 = "TRUNCATE TABLE tmpedido RESTART IDENTITY";
                    st = con.createStatement();
                    st.execute(sql19);
                    JOptionPane.showMessageDialog(null, "Tabla tmpedido Vacio");
                }
                
                if(usuarios.isSelected()){
                    String sql20 = "TRUNCATE TABLE usuarios RESTART IDENTITY";
                    st = con.createStatement();
                    st.execute(sql20);
                    JOptionPane.showMessageDialog(null, "Tabla usuarios Vacio");
                }
                
                if(venta.isSelected()){
                    String sql21 = "TRUNCATE TABLE venta RESTART IDENTITY";
                    st = con.createStatement();
                    st.execute(sql21);
                    JOptionPane.showMessageDialog(null, "Tabla venta Vacio");
                }
                
                if(presupuesto.isSelected()){
                    String sql22 = "TRUNCATE TABLE presupuesto RESTART IDENTITY";
                    st = con.createStatement();
                    st.execute(sql22);
                    JOptionPane.showMessageDialog(null, "Tabla presupuesto Vacio");
                }
                
                if(detpresupuesto.isSelected()){
                    String sql23 = "TRUNCATE TABLE detpresupuesto RESTART IDENTITY";
                    st = con.createStatement();
                    st.execute(sql23);
                    JOptionPane.showMessageDialog(null, "Tabla detpresupuesto Vacio");
                }
                
                if(tmpdetpresu.isSelected()){
                    String sql25 = "TRUNCATE TABLE tmpdetpresu RESTART IDENTITY";
                    st = con.createStatement();
                    st.execute(sql25);
                    JOptionPane.showMessageDialog(null, "Tabla tmpdetpresu Vacio");
                }
                
                if(apariencia.isSelected()){
                    String sql24 = "TRUNCATE TABLE apariencia RESTART IDENTITY";
                    st = con.createStatement();
                    st.execute(sql24);
                    JOptionPane.showMessageDialog(null, "Tabla apariencia Vacio");
                }
                
                
                btn_ELIMINAR_TABLAS.setVisible(false);
                btn_tablas1.setVisible(false);
                btn_base.setVisible(false);
                
                jInternalFrame1.setVisible(false);
                

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al Insertar Datos " + ex.getMessage());
               // System.out.println("ver error " );

            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void contadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(base_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(base_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(base_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(base_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new base_datos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox apariencia;
    private javax.swing.JButton btn_ELIMINAR_TABLAS;
    private javax.swing.JButton btn_avan;
    private javax.swing.JButton btn_base;
    private javax.swing.JButton btn_tablas1;
    private javax.swing.JButton btn_txt_exa;
    private javax.swing.JButton btn_txtcaja;
    private javax.swing.JButton btn_txthost;
    private javax.swing.JLabel caja;
    private javax.swing.JCheckBox cja;
    private javax.swing.JCheckBox clientes;
    private javax.swing.JCheckBox cobranza;
    private javax.swing.JCheckBox config;
    private javax.swing.JCheckBox contador;
    private javax.swing.JCheckBox cotizar;
    private javax.swing.JCheckBox detallespedido;
    private javax.swing.JCheckBox detallevta;
    private javax.swing.JCheckBox detcobranza;
    private javax.swing.JCheckBox detpresupuesto;
    private javax.swing.JCheckBox gastos;
    private javax.swing.JCheckBox grupopro;
    private javax.swing.JLabel hos_txt;
    private javax.swing.JCheckBox ingreso;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel jpane_txt;
    private javax.swing.JCheckBox movimiento_caja;
    private javax.swing.JCheckBox pedido;
    private javax.swing.JCheckBox presupuesto;
    private javax.swing.JCheckBox privilegios;
    private javax.swing.JCheckBox productos;
    private javax.swing.JCheckBox proveedores;
    private javax.swing.JCheckBox sucursal;
    private javax.swing.JCheckBox tmpdetallevta;
    private javax.swing.JCheckBox tmpdetpresu;
    private javax.swing.JCheckBox tmpedido;
    private javax.swing.JTextField txt_caja;
    private javax.swing.JTextField txt_contra;
    private javax.swing.JTextField txt_db;
    private javax.swing.JTextField txt_host;
    private javax.swing.JTextField txt_pas;
    private javax.swing.JTextField txt_ruta1;
    private javax.swing.JTextField txt_suc;
    private javax.swing.JCheckBox usuarios;
    private javax.swing.JCheckBox venta;
    // End of variables declaration//GEN-END:variables
}
