/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbstock;


import java.awt.KeyEventPostProcessor;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URISyntaxException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Derlis
 */
public class cliente extends javax.swing.JFrame {

    Statement st;
    Connection con;
    
    public static double sum,sumdeuda;
    
    public cliente() {
        initComponents();
        
        this.setLocationRelativeTo(null);//centra el formulario
        this.setTitle("Registro de Clientes");
        setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE); //inabilida el uso del boton exit X
        this.setResizable(false); //Disable the Resize Button
        

        
                cli_cedula.setEnabled(false);
                cli_nombre.setEnabled(false);
                cli_direccion.setEnabled(false);
                cli_telefono.setEnabled(false);
                cli_limite.setEnabled(false);
                cli_celular.setEnabled(false);
                cli_email.setEnabled(false);
                
            btn_usuguardar.setVisible(true);
            btn_usunuevo.setEnabled(true);
            btn_usuguardar.setEnabled(false);
            btn_usuactualizar.setEnabled(false);
            btn_usueditar.setEnabled(false);
            btn_usueliminar.setEnabled(false);
            btn_usucalcelar.setEnabled(false);
            btn_usuexit.setEnabled(true);

            btn_whats.setEnabled(false);
        metodos.CARGAR_JTABLE_cliente();
        
        btn_usunuevo.requestFocus();
        
        
        
        //////////////////////////////////CIERRA LA VENTANA CON ESCAPE////////////////////////
        KeyboardFocusManager kb = KeyboardFocusManager.getCurrentKeyboardFocusManager();
        kb.addKeyEventPostProcessor(new KeyEventPostProcessor(){
            public boolean postProcessKeyEvent(KeyEvent e){
//                Principal.jMenu_cliente.setEnabled(true);
//                Principal.btn_cliente.setEnabled(true);
                if (e.getKeyCode() == KeyEvent.VK_ESCAPE && this != null){
                    //System.out.println("probando...");
                    dispose();
                    return false;
                }
                return true;
            }
        });
       //////////////////////////////////////////////////////////////////////////////////////
       
       
       
        
    }

         public void goToURL(String URL){
           if (java.awt.Desktop.isDesktopSupported()) {
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();

            if (desktop.isSupported(java.awt.Desktop.Action.BROWSE)) {
                try {
                    java.net.URI uri = new java.net.URI(URL);
                    desktop.browse(uri);
                } catch (URISyntaxException | IOException ex) {
                   // Logger.getLogger(Acerca.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cli_cedula = new javax.swing.JTextField();
        cli_nombre = new javax.swing.JTextField();
        cli_direccion = new javax.swing.JTextField();
        cli_telefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_cliente = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        cli_email = new javax.swing.JTextField();
        buscar_cli = new javax.swing.JTextField();
        btn_usunuevo = new javax.swing.JButton();
        btn_usuguardar = new javax.swing.JButton();
        btn_usueditar = new javax.swing.JButton();
        btn_usucalcelar = new javax.swing.JButton();
        btn_usueliminar = new javax.swing.JButton();
        btn_usuexit = new javax.swing.JButton();
        btn_usuactualizar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        check_credito = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cli_celular = new javax.swing.JTextField();
        cli_limite = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btn_whats = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(830, 495));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("REGISTRO DE CLIENTES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Buscar Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, 20));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Dirección");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Nombre y Apellido");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 20));

        cli_cedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cli_cedulaFocusLost(evt);
            }
        });
        cli_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cli_cedulaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cli_cedulaKeyTyped(evt);
            }
        });
        getContentPane().add(cli_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 170, -1));

        cli_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cli_nombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cli_nombreKeyTyped(evt);
            }
        });
        getContentPane().add(cli_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 320, -1));

        cli_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cli_direccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cli_direccionKeyTyped(evt);
            }
        });
        getContentPane().add(cli_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 320, -1));

        cli_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cli_telefonoActionPerformed(evt);
            }
        });
        cli_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cli_telefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cli_telefonoKeyTyped(evt);
            }
        });
        getContentPane().add(cli_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 140, -1));

        jTable_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_clienteMouseClicked(evt);
            }
        });
        jTable_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable_clienteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable_clienteKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_cliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 440, 270));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Documento");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 20));

        cli_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cli_emailActionPerformed(evt);
            }
        });
        cli_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cli_emailKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cli_emailKeyTyped(evt);
            }
        });
        getContentPane().add(cli_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 260, -1));

        buscar_cli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscar_cliKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscar_cliKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscar_cliKeyTyped(evt);
            }
        });
        getContentPane().add(buscar_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 320, -1));

        btn_usunuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/add-file.png"))); // NOI18N
        btn_usunuevo.setText("Nuevo");
        btn_usunuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usunuevoActionPerformed(evt);
            }
        });
        btn_usunuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_usunuevoKeyPressed(evt);
            }
        });
        getContentPane().add(btn_usunuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 100, 40));

        btn_usuguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/save.png"))); // NOI18N
        btn_usuguardar.setText("Guardar");
        btn_usuguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuguardarActionPerformed(evt);
            }
        });
        btn_usuguardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_usuguardarKeyPressed(evt);
            }
        });
        getContentPane().add(btn_usuguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 110, 40));

        btn_usueditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/editar.png"))); // NOI18N
        btn_usueditar.setText("Editar");
        btn_usueditar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_usueditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usueditarActionPerformed(evt);
            }
        });
        btn_usueditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_usueditarKeyPressed(evt);
            }
        });
        getContentPane().add(btn_usueditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 100, 40));

        btn_usucalcelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/x-button.png"))); // NOI18N
        btn_usucalcelar.setText("Cancelar");
        btn_usucalcelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usucalcelarActionPerformed(evt);
            }
        });
        btn_usucalcelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_usucalcelarKeyPressed(evt);
            }
        });
        getContentPane().add(btn_usucalcelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 110, 40));

        btn_usueliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/eliminar.png"))); // NOI18N
        btn_usueliminar.setText("Eliminar");
        btn_usueliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usueliminarActionPerformed(evt);
            }
        });
        btn_usueliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_usueliminarKeyPressed(evt);
            }
        });
        getContentPane().add(btn_usueliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 110, 40));

        btn_usuexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/exit.png"))); // NOI18N
        btn_usuexit.setText("Salir");
        btn_usuexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuexitActionPerformed(evt);
            }
        });
        btn_usuexit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_usuexitKeyPressed(evt);
            }
        });
        getContentPane().add(btn_usuexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 110, 40));

        btn_usuactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/reload.png"))); // NOI18N
        btn_usuactualizar.setText("Actualizar");
        btn_usuactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuactualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usuactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 110, 40));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("Celular");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        check_credito.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        check_credito.setText("Tiene Cretido?");
        check_credito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_creditoActionPerformed(evt);
            }
        });
        check_credito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                check_creditoKeyPressed(evt);
            }
        });
        getContentPane().add(check_credito, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 120, 30));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 20));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setText("Monto Limite");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 20));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setText("Telefono");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        cli_celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cli_celularActionPerformed(evt);
            }
        });
        cli_celular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cli_celularKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cli_celularKeyTyped(evt);
            }
        });
        getContentPane().add(cli_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 140, -1));

        cli_limite.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cli_limite.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cli_limiteFocusLost(evt);
            }
        });
        cli_limite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cli_limiteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cli_limiteKeyTyped(evt);
            }
        });
        getContentPane().add(cli_limite, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 150, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setText("Contactar por WhatsApp");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, 40));

        btn_whats.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/whatsapp.png"))); // NOI18N
        btn_whats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_whatsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_whats, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/fondosistema.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_usunuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usunuevoActionPerformed

        
        cli_cedula.setText("");
        cli_nombre.setText("");
        cli_direccion.setText("");
        cli_telefono.setText("");
        cli_celular.setText("");
        cli_email.setText("");
        cli_limite.setText("");
        cli_limite.setText("0");
        
        cli_cedula.setEnabled(true);
        cli_nombre.setEnabled(true);
        cli_direccion.setEnabled(true);
        cli_telefono.setEnabled(true);
        cli_celular.setEnabled(true);
        cli_email.setEnabled(true);

        btn_usunuevo.setEnabled(false);
        btn_usuguardar.setEnabled(true);
        btn_usuactualizar.setEnabled(false);
        btn_usueditar.setEnabled(false);
        btn_usueliminar.setEnabled(false);
        btn_usucalcelar.setEnabled(true);
        btn_usuexit.setEnabled(true);
        cli_cedula.requestFocus();
        
        
        
    }//GEN-LAST:event_btn_usunuevoActionPerformed

    private void btn_usuguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuguardarActionPerformed

       // if (cli_cedula.equals("")  && cli_nombre.equals("")  && cli_direccion.equals("")  && cli_telefono.equals("") ) {
       
        int aux  =  JOptionPane.showConfirmDialog(null, "Desea Guardar el Registro?","OBSERVACION", JOptionPane.YES_NO_OPTION);
        if(aux == JOptionPane.YES_OPTION){

            Conexion cc=new Conexion();
            Connection con=cc.conectar();
            try {

                String sql = "INSERT INTO clientes (cli_cedula, cli_nombre, cli_direccion,cli_telefono,cli_celular, cli_email, cli_limite) "
                + "values ('"+cli_cedula.getText()+"','"+cli_nombre.getText()+"','"+cli_direccion.getText()+"','"+cli_telefono.getText()+"',"
                        + "'"+cli_celular.getText()+"','"+cli_email.getText()+"','"+cli_limite.getText()+"')";

                st = con.createStatement();
                st.execute(sql);
                metodos.CARGAR_JTABLE_cliente();

                btn_usueditar.setEnabled(true);
                btn_usueliminar.setEnabled(true);
                
                        cli_cedula.setEnabled(false);
                        cli_nombre.setEnabled(false);
                        cli_direccion.setEnabled(false);
                        cli_telefono.setEnabled(false);
                        cli_celular.setEnabled(false);
                        cli_email.setEnabled(false);
                        
                        cli_cedula.setText("");
                        cli_nombre.setText("");
                        cli_direccion.setText("");
                        cli_telefono.setText("");
                        cli_celular.setText("");
                        cli_email.setText("");

                        btn_usuguardar.setVisible(true);
                        btn_usunuevo.setEnabled(true);
                        btn_usuguardar.setEnabled(false);
                        btn_usuactualizar.setEnabled(false);
                        btn_usueditar.setEnabled(false);
                        btn_usueliminar.setEnabled(false);
                        btn_usucalcelar.setEnabled(false);
                        btn_usuexit.setEnabled(true);
                
                
                sum = Double.parseDouble(cli_limite.getText());
                DecimalFormat df = new DecimalFormat("#,###,###,###");
                String promedio = df.format(sum);
                cli_limite.setText("  "+promedio); 

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al Insertar Datos " + ex.getMessage());
               // System.out.println("ver error " );

            }
        }
        
       
    }//GEN-LAST:event_btn_usuguardarActionPerformed

    private void btn_usueditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usueditarActionPerformed

        cli_cedula.setEnabled(true);
        cli_nombre.setEnabled(true);
        cli_direccion.setEnabled(true);
        cli_telefono.setEnabled(true);

        btn_usuguardar.setVisible(false);
        btn_usuactualizar.setVisible(true);

        btn_usunuevo.setEnabled(false);
        btn_usuguardar.setEnabled(false);
        btn_usuactualizar.setEnabled(true);
        btn_usueditar.setEnabled(false);
        btn_usueliminar.setEnabled(false);
        btn_usucalcelar.setEnabled(true);
        btn_usuexit.setEnabled(true);
    }//GEN-LAST:event_btn_usueditarActionPerformed

    private void btn_usucalcelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usucalcelarActionPerformed

        int aux  =  JOptionPane.showConfirmDialog(null, "Desea Cancelar Registro?","OBSERVACION", JOptionPane.YES_NO_OPTION);
        if(aux == JOptionPane.YES_OPTION){

        cli_cedula.setEnabled(false);
        cli_nombre.setEnabled(false);
        cli_direccion.setEnabled(false);
        cli_telefono.setEnabled(false);
        cli_celular.setEnabled(false);
        cli_email.setEnabled(false);

            btn_usuguardar.setVisible(true);
            btn_usunuevo.setEnabled(true);
            btn_usuguardar.setEnabled(false);
            btn_usuactualizar.setEnabled(false);
            btn_usueditar.setEnabled(false);
            btn_usueliminar.setEnabled(false);
            btn_usucalcelar.setEnabled(false);
            btn_usuexit.setEnabled(true);

        }
    }//GEN-LAST:event_btn_usucalcelarActionPerformed

    private void btn_usueliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usueliminarActionPerformed

        int aux  =  JOptionPane.showConfirmDialog(null, "Desea eliminar ","Sistema", JOptionPane.YES_NO_OPTION);

        if(aux == JOptionPane.YES_OPTION){

            int nz = jTable_cliente.getSelectedRow();
            String id = jTable_cliente.getValueAt(nz, 0).toString();
            cli_cedula.setText(id);

            Conexion cc=new Conexion();
            Connection con=cc.conectar();

            try {

                String sql = "delete from provedores where pro_ruc = '"+cli_cedula.getText()+"' ";
                st = con.createStatement();

                st.execute(sql);

                metodos.CARGAR_JTABLE();

                cli_cedula.setText("");
                cli_nombre.setText("");
                cli_direccion.setText("");
                cli_telefono.setText("");
                // cmb_privilegios.setText("");

                cli_cedula.setEnabled(false);
                cli_nombre.setEnabled(false);
                cli_direccion.setEnabled(false);
                cli_telefono.setEnabled(false);

                btn_usuguardar.setVisible(true);
                btn_usunuevo.setEnabled(true);
                btn_usuguardar.setEnabled(false);
                btn_usuactualizar.setEnabled(false);
                btn_usueditar.setEnabled(false);
                btn_usueliminar.setEnabled(false);
                btn_usucalcelar.setEnabled(false);
                btn_usuexit.setEnabled(true);

            }catch (Exception ee) {
                ee.printStackTrace();
            }

        }else{if(aux == JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(null,  "Cancelado", "Sistema", JOptionPane.INFORMATION_MESSAGE);

        }

        }
    }//GEN-LAST:event_btn_usueliminarActionPerformed

    private void btn_usuexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuexitActionPerformed
        dispose();
        
       
          Principal.jMenu_cliente.setEnabled(true);
          Principal.btn_cliente.setEnabled(true);
    }//GEN-LAST:event_btn_usuexitActionPerformed

    private void btn_usuactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuactualizarActionPerformed

        int aux  =  JOptionPane.showConfirmDialog(null, "Desea Actualizar los Datos","OBSERVACION", JOptionPane.YES_NO_OPTION);
        if(aux == JOptionPane.YES_OPTION){

            Conexion cc=new Conexion();
            Connection con=cc.conectar();
            try {

                String sql = "UPDATE clientes SET cli_cedula = '"+cli_cedula.getText()+"', cli_nombre = '"+cli_nombre.getText()+"',"
                + " cli_direccion= '"+cli_direccion.getText()+"', cli_telefono= '"+cli_telefono.getText()+"', cli_celular= '"+cli_celular.getText()+"',"
                + " cli_email= '"+cli_email.getText()+"',cli_limite= '"+cli_limite.getText()+"' where cli_cedula = '"+cli_cedula.getText()+"'";

                st = con.createStatement();

                st.execute(sql);

                JOptionPane.showMessageDialog(null,  "Registro Actualizado", "Clientes", JOptionPane.INFORMATION_MESSAGE);

                metodos.CARGAR_JTABLE_cliente();

                btn_usuguardar.setVisible(true);
                btn_usuactualizar.setVisible(false);

                btn_usunuevo.setEnabled(true);
                btn_usuguardar.setEnabled(false);
                btn_usuactualizar.setEnabled(false);
                btn_usueditar.setEnabled(false);
                btn_usueliminar.setEnabled(false);
                btn_usucalcelar.setEnabled(false);
                btn_usuexit.setEnabled(true);

                metodos.CARGAR_JTABLE_cliente();
                cli_cedula.setEnabled(false);
                cli_nombre.setEnabled(false);
                cli_direccion.setEnabled(false);
                cli_telefono.setEnabled(false);
                cli_celular.setEnabled(false);
                cli_email.setEnabled(false);
                

            } catch (SQLException ex) {
                System.out.println("ver error " + ex.getMessage());

            }
        }
    }//GEN-LAST:event_btn_usuactualizarActionPerformed

    private void cli_cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cli_cedulaKeyTyped
         ////convertir a mayusculas
        char c6 = evt.getKeyChar(); 
        if(Character.isLowerCase(c6)){
            String cad = ("" + c6).toUpperCase();
            c6 = cad.charAt(0);
            evt.setKeyChar(c6);
        }
    }//GEN-LAST:event_cli_cedulaKeyTyped

    private void cli_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cli_nombreKeyTyped
        ////convertir a mayusculas
        char c6 = evt.getKeyChar(); 
        if(Character.isLowerCase(c6)){
            String cad = ("" + c6).toUpperCase();
            c6 = cad.charAt(0);
            evt.setKeyChar(c6);
        }
    }//GEN-LAST:event_cli_nombreKeyTyped

    private void cli_direccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cli_direccionKeyTyped
                ////convertir a mayusculas
        char c6 = evt.getKeyChar(); 
        if(Character.isLowerCase(c6)){
            String cad = ("" + c6).toUpperCase();
            c6 = cad.charAt(0);
            evt.setKeyChar(c6);
        }
    }//GEN-LAST:event_cli_direccionKeyTyped

    private void cli_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cli_telefonoKeyTyped
        ////convertir a mayusculas
        char c6 = evt.getKeyChar(); 
        if(Character.isLowerCase(c6)){
            String cad = ("" + c6).toUpperCase();
            c6 = cad.charAt(0);
            evt.setKeyChar(c6);
        }
    }//GEN-LAST:event_cli_telefonoKeyTyped

    private void buscar_cliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscar_cliKeyTyped
        
        String sql="SELECT * FROM clientes WHERE cli_nombre  LIKE '%"+cliente.buscar_cli.getText()+"%' ORDER BY cli_codigo";
		
		String[] titulo={"Documento","Nombre","Telefono","Limite"};
		DefaultTableModel mod=new DefaultTableModel(null,titulo);
		Object[] reg=new Object[7];
		Conexion cc=new Conexion();
		Connection con=cc.conectar();
		Statement st;
		try {
			st = con.createStatement();
			ResultSet rs=st.executeQuery(sql);
			while(rs.next()){
				reg[0]=rs.getString("cli_cedula");
                                reg[1]=rs.getString("cli_nombre");
                                reg[2]=rs.getString("cli_telefono");
                                reg[3]=rs.getString("cli_limite");

				mod.addRow(reg);
			}
			cliente.jTable_cliente.setModel(mod);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		//forma de quetenga la barra orizontal////////////
		cliente.jTable_cliente.setAutoResizeMode(cliente.jTable_cliente.AUTO_RESIZE_OFF);
		cliente.jTable_cliente.doLayout();
                
		TableColumnModel columnModel = cliente.jTable_cliente.getColumnModel();

                columnModel.getColumn(0).setPreferredWidth(80);
                columnModel.getColumn(1).setPreferredWidth(200);
                columnModel.getColumn(2).setPreferredWidth(100);
                columnModel.getColumn(3).setPreferredWidth(70);
		//////////////////////////////////////////////////
        
    }//GEN-LAST:event_buscar_cliKeyTyped

    private void buscar_cliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscar_cliKeyReleased
        metodos.convertiraMayusculasEnJtextfield(buscar_cli);
    }//GEN-LAST:event_buscar_cliKeyReleased

    private void jTable_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_clienteMouseClicked
       
        cli_cedula.setEnabled(false);
        cli_nombre.setEnabled(false);
        cli_direccion.setEnabled(false);
        cli_telefono.setEnabled(false);
        
          btn_usunuevo.setEnabled(true);
          btn_usuguardar.setEnabled(false);
          btn_usuactualizar.setEnabled(false);
          btn_usueditar.setEnabled(true);
          btn_usueliminar.setEnabled(true);
          btn_usucalcelar.setEnabled(false);
          btn_usuexit.setEnabled(true);
        
          btn_whats.setEnabled(true);
          
        int n1 = jTable_cliente.getSelectedRow();
        String id = jTable_cliente.getValueAt(n1, 0).toString();
        cli_cedula.setText(id);
        
 		Conexion cc=new Conexion();
		Connection con=cc.conectar();;
        	try {

		String sql = "Select * from clientes where cli_cedula = '"+cli_cedula.getText()+"'";
		//ResultSet resultado = st.executeQuery(sql);
                st = con.createStatement();
                ResultSet rs=st.executeQuery(sql);
		if (rs.next()) {
                        cli_cedula.setText(rs.getString("cli_cedula"));
                        cli_nombre.setText(rs.getString("cli_nombre"));
                        cli_direccion.setText(rs.getString("cli_direccion"));
                        cli_telefono.setText(rs.getString("cli_telefono"));
                        cli_celular.setText(rs.getString("cli_celular"));
                        cli_email.setText(rs.getString("cli_email"));
                        cli_limite.setText(rs.getString("cli_limite"));
                       // cmb_privilegios.setSelectedItem("usu_privilegios");         //***************************

                    }
			rs.close();
			st.close();
			con.close();

		} catch (SQLException e) {
			JOptionPane.showMessageDialog(null, e.getMessage());
		}
        
    }//GEN-LAST:event_jTable_clienteMouseClicked

    private void cli_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cli_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cli_telefonoActionPerformed

    private void cli_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cli_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cli_emailActionPerformed

    private void cli_emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cli_emailKeyTyped
                ////convertir a mayusculas
        char c6 = evt.getKeyChar(); 
        if(Character.isLowerCase(c6)){
            String cad = ("" + c6).toUpperCase();
            c6 = cad.charAt(0);
            evt.setKeyChar(c6);
        }
    }//GEN-LAST:event_cli_emailKeyTyped

    private void cli_celularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cli_celularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cli_celularActionPerformed

    private void cli_celularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cli_celularKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cli_celularKeyTyped

    private void check_creditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_creditoActionPerformed
        
       if(check_credito.isSelected()){
           cli_limite.setEnabled(true);
           cli_limite.setText("0");

       }else{
           cli_limite.setEnabled(false);
            cli_limite.setText("0");
       }
        
    }//GEN-LAST:event_check_creditoActionPerformed

    private void cli_limiteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cli_limiteKeyTyped
                

        
    }//GEN-LAST:event_cli_limiteKeyTyped

    private void cli_limiteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cli_limiteKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            } 
        

    }//GEN-LAST:event_cli_limiteKeyPressed

    private void cli_limiteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cli_limiteFocusLost

    }//GEN-LAST:event_cli_limiteFocusLost

    private void cli_cedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cli_cedulaFocusLost
       cli_nombre.requestFocus();
    }//GEN-LAST:event_cli_cedulaFocusLost

    private void btn_usunuevoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_usunuevoKeyPressed
        
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btn_usunuevo.doClick();
        }
 
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            } 
    }//GEN-LAST:event_btn_usunuevoKeyPressed

    private void cli_cedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cli_cedulaKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_cli_cedulaKeyPressed

    private void cli_nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cli_nombreKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }         // TODO add your handling code here:
    }//GEN-LAST:event_cli_nombreKeyPressed

    private void cli_direccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cli_direccionKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }         // TODO add your handling code here:
    }//GEN-LAST:event_cli_direccionKeyPressed

    private void cli_telefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cli_telefonoKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }         // TODO add your handling code here:
    }//GEN-LAST:event_cli_telefonoKeyPressed

    private void cli_celularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cli_celularKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }         // TODO add your handling code here:
    }//GEN-LAST:event_cli_celularKeyPressed

    private void cli_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cli_emailKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }         // TODO add your handling code here:
    }//GEN-LAST:event_cli_emailKeyPressed

    private void check_creditoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_check_creditoKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }         // TODO add your handling code here:
    }//GEN-LAST:event_check_creditoKeyPressed

    private void jTable_clienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable_clienteKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }         // TODO add your handling code here:
    }//GEN-LAST:event_jTable_clienteKeyPressed

    private void buscar_cliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscar_cliKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }         // TODO add your handling code here:
    }//GEN-LAST:event_buscar_cliKeyPressed

    private void btn_usuguardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_usuguardarKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }         // TODO add your handling code here:
    }//GEN-LAST:event_btn_usuguardarKeyPressed

    private void btn_usueditarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_usueditarKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }         // TODO add your handling code here:
    }//GEN-LAST:event_btn_usueditarKeyPressed

    private void btn_usucalcelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_usucalcelarKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }         // TODO add your handling code here:
    }//GEN-LAST:event_btn_usucalcelarKeyPressed

    private void btn_usueliminarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_usueliminarKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }         // TODO add your handling code here:
    }//GEN-LAST:event_btn_usueliminarKeyPressed

    private void btn_usuexitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_usuexitKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }         // TODO add your handling code here:
    }//GEN-LAST:event_btn_usuexitKeyPressed

    private void jTable_clienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable_clienteKeyReleased
        
        if ((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_UP)) {
                int filaSeleccionada = this.jTable_cliente.getSelectedRow();//Identificamos que fila ha sido seleccionada

                try {
                    this.cli_cedula.setText(jTable_cliente.getValueAt(filaSeleccionada, 0).toString());
                    this.cli_nombre.setText(jTable_cliente.getValueAt(filaSeleccionada, 1).toString());
                    this.cli_direccion.setText(jTable_cliente.getValueAt(filaSeleccionada, 2).toString());
                    //this.cli_direccion.setSelectedItem(jTable_cliente.getValueAt(filaSeleccionada, 2).toString());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error al leer datos de la tabla", "Error", JOptionPane.WARNING_MESSAGE);
                }
        }
        
    }//GEN-LAST:event_jTable_clienteKeyReleased

    private void btn_whatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_whatsActionPerformed
        goToURL("https://api.whatsapp.com/send?phone=+595'"+cli_celular.getText()+"'");
    }//GEN-LAST:event_btn_whatsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_usuactualizar;
    private javax.swing.JButton btn_usucalcelar;
    private javax.swing.JButton btn_usueditar;
    private javax.swing.JButton btn_usueliminar;
    private javax.swing.JButton btn_usuexit;
    private javax.swing.JButton btn_usuguardar;
    private javax.swing.JButton btn_usunuevo;
    private javax.swing.JButton btn_whats;
    public static javax.swing.JTextField buscar_cli;
    private javax.swing.JCheckBox check_credito;
    private javax.swing.JTextField cli_cedula;
    private javax.swing.JTextField cli_celular;
    private javax.swing.JTextField cli_direccion;
    private javax.swing.JTextField cli_email;
    private javax.swing.JTextField cli_limite;
    private javax.swing.JTextField cli_nombre;
    private javax.swing.JTextField cli_telefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_cliente;
    // End of variables declaration//GEN-END:variables
}
