/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbstock;

import java.awt.Image;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Derlis
 */
public class config extends javax.swing.JFrame {

    Statement st;
    Connection con;
    private FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos con Extension JPG y PNG", "jpg", "png");
    public config() {
        initComponents();
        
        this.setLocationRelativeTo(null);//centra el formulario
        this.setTitle("Configuraciones");
        
        conf_denominacion.setEnabled(false);
        conf_ruc.setEnabled(false);
        conf_telefono.setEnabled(false);
        conf_direccion.setEnabled(false);
        conf_actividad.setEnabled(false);
        conf_email.setEnabled(false);
        conf_web.setEnabled(false);
        Conf_autoimpresor.setEnabled(false);
        conf_timbrado.setEnabled(false);
        conf_timbradoini.setEnabled(false);
        conf_timbradoven.setEnabled(false);    
        conf_sucursal.setEnabled(false);
        conf_ciudad.setEnabled(false);
        nombre_logo.setEnabled(false);
        url_logo.setEnabled(false);
        iva1.setEnabled(false);
        divisor1.setEnabled(false);
        iva2.setEnabled(false);
        divisor2.setEnabled(false);
        jCheckBox_sinfact.setEnabled(false);
        jCheckBox_confact.setEnabled(false);
        id_pro.setEnabled(false);
        id_barra.setEnabled(false);
        btn_usuactualizar.setEnabled(false);
        btn_contador.setEnabled(false);
        jCheckBox1.setEnabled(false);
        txt_sec.setEnabled(false);
        btn_save.setEnabled(false);        
        btn_confcancelar.setEnabled(false);
        jbox_matricial.setEnabled(false);
        
        btn_examinar.setEnabled(false);
        
        caj_cod.setVisible(false);////invisible dato estirado para actuazliar secuencia
        su_cod.setVisible(false);////invisible dato estirado para actuazliar secuencia
        
        metodos.estirardatos_conf();
        metodos.estirardatos_SECUENCIA();
        mostrar_fac.setEnabled(false);
               ///////////////////para factura
               
        String vacio = mostrar_fac.getText();

        if (vacio.length() == 0 && (vacio != null) && (!vacio.equals(" "))) {
            // cadena no está vacía
            //JOptionPane.showMessageDialog(this, "No dejar campos Vacíos", "Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            if (mostrar_fac.getText().equals("0")) { //sin factura
                jCheckBox_sinfact.setSelected(true);
            }

            if (mostrar_fac.getText().equals("1")) { //sin factura
                jCheckBox_confact.setSelected(true);
            }

            if (mostrar_fac.getText().equals("2")) { //sin factura matricial
                jbox_matricial.setSelected(true);
            }

            if (mostrar_bus.getText().equals("0")) {// PARA BUSCAR LECTOR
                id_pro.setSelected(true);
            }

            if (mostrar_bus.getText().equals("1")) {// PARA BUSCAR DESCRI 
                id_barra.setSelected(true);
            }
        }
               

        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        conf_denominacion = new javax.swing.JTextField();
        btn_usuexit = new javax.swing.JButton();
        btn_usueditar = new javax.swing.JButton();
        btn_usuactualizar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Conf_autoimpresor = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        conf_sucursal = new javax.swing.JTextField();
        conf_ruc = new javax.swing.JTextField();
        conf_telefono = new javax.swing.JTextField();
        conf_direccion = new javax.swing.JTextField();
        conf_actividad = new javax.swing.JTextField();
        conf_email = new javax.swing.JTextField();
        conf_web = new javax.swing.JTextField();
        conf_timbrado = new javax.swing.JTextField();
        conf_timbradoini = new javax.swing.JTextField();
        conf_timbradoven = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        conf_ciudad = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        iva2 = new javax.swing.JTextField();
        divisor2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        iva1 = new javax.swing.JTextField();
        divisor1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        btn_confcancelar = new javax.swing.JButton();
        milogo = new javax.swing.JLabel();
        btn_examinar = new javax.swing.JButton();
        url_logo = new javax.swing.JTextField();
        nombre_logo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        id_barra = new javax.swing.JCheckBox();
        jCheckBox_confact = new javax.swing.JCheckBox();
        jCheckBox_sinfact = new javax.swing.JCheckBox();
        id_pro = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btn_contador = new javax.swing.JButton();
        txt_sec = new javax.swing.JTextField();
        mostrar_bus = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        caj_cod = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        su_cod = new javax.swing.JLabel();
        jbox_matricial = new javax.swing.JCheckBox();
        id_conf = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mostrar_fac = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(880, 580));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("CONFIGURACIONES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Telefono:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 70, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("RUC:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 40, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Actividad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 70, 20));
        getContentPane().add(conf_denominacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 410, -1));

        btn_usuexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/exit.png"))); // NOI18N
        btn_usuexit.setText("Salir");
        btn_usuexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuexitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usuexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 110, 40));

        btn_usueditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/editar.png"))); // NOI18N
        btn_usueditar.setText("Editar");
        btn_usueditar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_usueditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usueditarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usueditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 100, 40));

        btn_usuactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/reload.png"))); // NOI18N
        btn_usuactualizar.setText("Actualizar");
        btn_usuactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuactualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usuactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 120, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Dirección:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 70, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Timbrado Nro:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 100, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Correo Electronico:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 130, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("De:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 30, 20));

        Conf_autoimpresor.setColumns(20);
        Conf_autoimpresor.setRows(5);
        jScrollPane1.setViewportView(Conf_autoimpresor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 350, 60));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Resolucion Autoimpresor:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 160, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Timbrado Fecha Inicio - Fin:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 180, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Timbrado Vencimiento:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 160, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Sucursal:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 70, 20));
        getContentPane().add(conf_sucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 450, -1));
        getContentPane().add(conf_ruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 180, -1));

        conf_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conf_telefonoActionPerformed(evt);
            }
        });
        getContentPane().add(conf_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 210, -1));
        getContentPane().add(conf_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 440, -1));
        getContentPane().add(conf_actividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 440, -1));
        getContentPane().add(conf_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 390, -1));
        getContentPane().add(conf_web, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 470, -1));
        getContentPane().add(conf_timbrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 420, -1));
        getContentPane().add(conf_timbradoini, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 340, -1));
        getContentPane().add(conf_timbradoven, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 360, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Ciudad:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 50, 20));
        getContentPane().add(conf_ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 450, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Denominación:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 110, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Divisor");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 50, 20));

        iva2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(iva2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 40, -1));

        divisor2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(divisor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 50, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("iva menor %:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 90, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Divisor:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 50, 20));

        iva1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(iva1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 40, -1));

        divisor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(divisor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 50, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Buscar producto por:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, 140, 20));

        btn_confcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/x-button.png"))); // NOI18N
        btn_confcancelar.setText("Cancelar");
        btn_confcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confcancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_confcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, 110, 40));

        milogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        milogo.setText("Mi Logo");
        getContentPane().add(milogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 220, 190));

        btn_examinar.setText("Buscar LOGO");
        btn_examinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_examinarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_examinar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 110, -1));
        getContentPane().add(url_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 300, -1));
        getContentPane().add(nombre_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 200, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 10, 470));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 332, 290, 10));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("iva mayor %:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 450, -1, 20));

        id_barra.setText("Descripción ");
        id_barra.setOpaque(false);
        id_barra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_barraActionPerformed(evt);
            }
        });
        getContentPane().add(id_barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, -1, -1));

        jCheckBox_confact.setText("Ticket con Factura");
        jCheckBox_confact.setOpaque(false);
        jCheckBox_confact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_confactActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox_confact, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, -1, -1));

        jCheckBox_sinfact.setText("Ticket sin Factura");
        jCheckBox_sinfact.setOpaque(false);
        jCheckBox_sinfact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_sinfactActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox_sinfact, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, -1, -1));

        id_pro.setText("Código de Bara");
        id_pro.setOpaque(false);
        id_pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_proActionPerformed(evt);
            }
        });
        getContentPane().add(id_pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 120, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Condición de impresión");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 130, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Inicializar Numero de Factura");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 190, -1));

        btn_contador.setText("Vaciar contador de secuencia");
        btn_contador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_contadorActionPerformed(evt);
            }
        });
        getContentPane().add(btn_contador, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, -1, 30));

        txt_sec.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_sec.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_sec, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 70, 30));
        getContentPane().add(mostrar_bus, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 360, 30, 20));

        btn_save.setText("Actualizar");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        getContentPane().add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, 100, 30));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 530, -1));
        getContentPane().add(caj_cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 40, 20));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel24.setText("Vaciar Secuencia de Contador de Factura caso cambio de timbrado ");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 310, -1));

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, -1, -1));
        getContentPane().add(su_cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 40, 20));

        jbox_matricial.setText("Matricial sin Factura");
        jbox_matricial.setOpaque(false);
        jbox_matricial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbox_matricialActionPerformed(evt);
            }
        });
        getContentPane().add(jbox_matricial, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, -1, -1));
        getContentPane().add(id_conf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 30, 20));

        jButton1.setText("LICENCIA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 480, 100, -1));
        getContentPane().add(mostrar_fac, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 20, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/fondosistema.jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-360, -10, 1270, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_usuexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuexitActionPerformed

        dispose();
        
    }//GEN-LAST:event_btn_usuexitActionPerformed

    private void btn_usueditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usueditarActionPerformed

        conf_denominacion.setEnabled(true);
        conf_ruc.setEnabled(true);
        conf_telefono.setEnabled(true);
        conf_direccion.setEnabled(true);
        conf_actividad.setEnabled(true);
        conf_email.setEnabled(true);
        conf_web.setEnabled(true);
        Conf_autoimpresor.setEnabled(true);
        conf_timbrado.setEnabled(true);
        conf_timbradoini.setEnabled(true);
        conf_timbradoven.setEnabled(true);    
        conf_sucursal.setEnabled(true);
        conf_ciudad.setEnabled(true);
        nombre_logo.setEnabled(true);
        url_logo.setEnabled(true);
        iva1.setEnabled(true);
        divisor1.setEnabled(true);
        iva2.setEnabled(true);
        divisor2.setEnabled(true);
        btn_examinar.setEnabled(true);
        jCheckBox_sinfact.setEnabled(true);
        jCheckBox_confact.setEnabled(true);
        id_pro.setEnabled(true);
        id_barra.setEnabled(true);
        btn_contador.setEnabled(true);
        jCheckBox1.setEnabled(true);
        btn_confcancelar.setEnabled(true);
        jbox_matricial.setEnabled(true);


        btn_usuactualizar.setVisible(true);


        btn_usuactualizar.setEnabled(true);
        btn_usueditar.setEnabled(false);

        btn_usuexit.setEnabled(true);
        btn_usuexit.setEnabled(true);
    }//GEN-LAST:event_btn_usueditarActionPerformed

    private void btn_usuactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuactualizarActionPerformed

        int aux  =  JOptionPane.showConfirmDialog(null, "Desea Actualizar los Datos","OBSERVACION", JOptionPane.YES_NO_OPTION);
        if(aux == JOptionPane.YES_OPTION){

            Conexion cc=new Conexion();
            Connection con=cc.conectar();
            try {

                String sql = "UPDATE config SET conf_denominacion = '"+conf_denominacion.getText()+"', conf_ruc = '"+conf_ruc.getText()+"',"
                + " conf_direccion= '"+conf_direccion.getText()+"', conf_telefono= '"+conf_telefono.getText()+"',"
                        + " conf_actividad= '"+conf_actividad.getText()+"', conf_email= '"+conf_email.getText()+"',"
                        + " conf_web= '"+conf_web.getText()+"', conf_autoimpresor= '"+Conf_autoimpresor.getText()+"', conf_timbrado= '"+conf_timbrado.getText()+"',"
                        + " conf_timbradoini= '"+conf_timbradoini.getText()+"', conf_timbradoven = '"+conf_timbradoven.getText()+"',"
                        + " conf_sucursal = '"+conf_sucursal.getText()+"', conf_ciudad = '"+conf_ciudad.getText()+"'"
                        + ", conf_url = '"+url_logo.getText()+"', conf_iva1 = '"+iva1.getText()+"', conf_divisor1 = '"+divisor1.getText()+"'"
                        + ", conf_divisor2 = '"+divisor2.getText()+"', conf_iva2 = '"+iva2.getText()+"' , conf_factura = '"+mostrar_fac.getText()+"' , conf_buspro = '"+mostrar_bus.getText()+"' where conf_id = '"+id_conf.getText()+"'";

                st = con.createStatement();

                st.execute(sql);

                JOptionPane.showMessageDialog(null,  "Registro Actualizado", "Configuración", JOptionPane.INFORMATION_MESSAGE);
                metodos.estirardatos_conf();
                
                btn_usuactualizar.setEnabled(false);
                btn_usueditar.setEnabled(true);
                btn_usuexit.setEnabled(false);
                btn_usuexit.setEnabled(true);
                
                conf_denominacion.setEnabled(false);
                conf_ruc.setEnabled(false);
                conf_telefono.setEnabled(false);
                conf_direccion.setEnabled(false);
                conf_actividad.setEnabled(false);
                conf_email.setEnabled(false);
                conf_web.setEnabled(false);
                Conf_autoimpresor.setEnabled(false);
                conf_timbrado.setEnabled(false);
                conf_timbradoini.setEnabled(false);
                conf_timbradoven.setEnabled(false);    
                conf_sucursal.setEnabled(false);
                conf_ciudad.setEnabled(false);
                jCheckBox_sinfact.setEnabled(false);
                jCheckBox_confact.setEnabled(false);
                id_pro.setEnabled(false);
                id_barra.setEnabled(false);
                btn_contador.setEnabled(false);
                btn_examinar.setEnabled(false);
                jbox_matricial.setEnabled(false);
                
                jCheckBox1.setEnabled(true);

            } catch (SQLException ex) {
                System.out.println("ver error " + ex.getMessage());
                JOptionPane.showMessageDialog(null,  "Registro NO Actualizado", "Configuración", JOptionPane.WARNING_MESSAGE);

            }
        }
    }//GEN-LAST:event_btn_usuactualizarActionPerformed

    private void conf_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conf_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conf_telefonoActionPerformed

    private void btn_confcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confcancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_confcancelarActionPerformed

    private void btn_examinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_examinarActionPerformed
        JFileChooser filechoose = new JFileChooser();
        filechoose.setFileFilter(filter);
        int opcion = filechoose.showOpenDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION) {
            //OBTENER EL NOMBRE DEL ARCHIVO SELECCIONADO
            String nombre_archivo = filechoose.getSelectedFile().getName();
            //OBTENER LA RUTA DEL ARCHIVO SELECCIONADO
            String ruta = filechoose.getSelectedFile().getPath();
            //seteamos el nombre del archivo
            nombre_logo.setText(nombre_archivo);
            //seteamos la ruta
            url_logo.setText(ruta);
           
            System.out.println(ruta);
            
            milogo.setIcon(new ImageIcon(ruta));
            
          ////////ajustar imagen se puede colocar en boton                                       
 //      ImageIcon imgIcon = new ImageIcon(getClass().getResource(nombre_archivo));
 //      Image imgEscalada = imgIcon.getImage().getScaledInstance(milogo.getWidth(),
 //      milogo.getHeight(), Image.SCALE_SMOOTH);
 //      Icon iconoEscalado = new ImageIcon(imgEscalada);
//        milogo.setIcon(iconoEscalado);
        /////////fin de ajustar imagen
        
        ImageIcon fot = new ImageIcon(ruta);
        Icon icono = new ImageIcon(fot.getImage().getScaledInstance(milogo.getWidth(), milogo.getHeight(), Image.SCALE_DEFAULT));
        milogo.setIcon(icono);
        this.repaint();
   
        }
    }//GEN-LAST:event_btn_examinarActionPerformed

    private void jCheckBox_sinfactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_sinfactActionPerformed
   
        if(jCheckBox_sinfact.isSelected()){
           this.jCheckBox_sinfact.setSelected(true);
           this.jCheckBox_confact.setSelected(false);
           this.jbox_matricial.setSelected(false);
           
           mostrar_fac.setText("0");
        } 
        
    }//GEN-LAST:event_jCheckBox_sinfactActionPerformed

    private void jCheckBox_confactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_confactActionPerformed
        if(jCheckBox_confact.isSelected()){
           this.jCheckBox_sinfact.setSelected(false);
           this.jCheckBox_confact.setSelected(true);
           this.jbox_matricial.setSelected(false);
           
           mostrar_fac.setText("1");
        } 
    }//GEN-LAST:event_jCheckBox_confactActionPerformed

    private void id_proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_proActionPerformed
        if(id_pro.isSelected()){
           this.id_pro.setSelected(true);
           this.id_barra.setSelected(false);
           mostrar_bus.setText("0");
        } 
        
    }//GEN-LAST:event_id_proActionPerformed

    private void id_barraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_barraActionPerformed
        if(id_barra.isSelected()){
           this.id_pro.setSelected(false);
           this.id_barra.setSelected(true);
           mostrar_bus.setText("1");
        } 
    }//GEN-LAST:event_id_barraActionPerformed

    private void btn_contadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_contadorActionPerformed
        
        
        int aux  =  JOptionPane.showConfirmDialog(null, "Esta seguro que desea iniciar de cero contador de factura?","OBSERVACION", JOptionPane.YES_NO_OPTION);
        if(aux == JOptionPane.YES_OPTION){

                      
            String respuesta = JOptionPane.showInputDialog("Ingresar Contraseña");
            
            if ("dbstock14512".equals(respuesta)) {
                
            Conexion cc=new Conexion();
            Connection con=cc.conectar();
            try {
                int ceroo= 0;
                String sqlcerar = "UPDATE contador SET cont_secuencia = '"+ceroo+"'";

                st = con.createStatement();

                st.execute(sqlcerar);

                JOptionPane.showMessageDialog(null,  "Proceso realizado exitosamente", "Contador", JOptionPane.INFORMATION_MESSAGE);
               // metodos.estirardatos_conf();
                btn_contador.setEnabled(false);

            } catch (SQLException ex) {
                System.out.println("ver error " + ex.getMessage());

            }
            }
            

        }
        
    }//GEN-LAST:event_btn_contadorActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected()){
             txt_sec.setEnabled(true);
             btn_save.setEnabled(true);
        }else{
             txt_sec.setEnabled(false);
             btn_save.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        
        int aux  =  JOptionPane.showConfirmDialog(null, "Desea Actualizar Datos de Secuencia de Factura","OBSERVACION", JOptionPane.YES_NO_OPTION);
        if(aux == JOptionPane.YES_OPTION){
           
            String respuesta = JOptionPane.showInputDialog("Ingresar Contraseña");
            
            if ("dbstock14512".equals(respuesta)) {
                
            Conexion cc=new Conexion();
            Connection con=cc.conectar();
                try {

                    String sql01 = "UPDATE contador SET cont_secuencia = '"+txt_sec.getText()+"' where caj_codigo = '"+caj_cod.getText()+"' and  cont_id = '"+su_cod.getText()+"'";

                    st = con.createStatement();

                    st.execute(sql01);

                    JOptionPane.showMessageDialog(null,  "Registro Actualizado", "Secuencia", JOptionPane.INFORMATION_MESSAGE);
                    metodos.estirardatos_SECUENCIA();
                    
                    txt_sec.setEnabled(false);
                    btn_save.setEnabled(false);
                    jCheckBox1.isSelected();
                    

                } catch (SQLException ex) {
                    System.out.println("ver error " + ex.getMessage());

                }
            }else{
                String respuesta1 = JOptionPane.showInputDialog(null, "Escriba nuevamente la contraseña", "Error!", JOptionPane.ERROR_MESSAGE);
                
            }
            

        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void jbox_matricialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbox_matricialActionPerformed
        if(jbox_matricial.isSelected()){
           this.jCheckBox_sinfact.setSelected(false);
           this.jCheckBox_confact.setSelected(false);
           this.jbox_matricial.setSelected(true);
           mostrar_fac.setText("2");
        } 
    }//GEN-LAST:event_jbox_matricialActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        int aux = JOptionPane.showConfirmDialog(null, "Desea Actualizar LICENCIA", "OBSERVACION", JOptionPane.YES_NO_OPTION);
        if (aux == JOptionPane.YES_OPTION) {

            String respuesta = JOptionPane.showInputDialog("Ingresar Contraseña");

            if ("dbstock14512".equals(respuesta)) {

                licencia ver99 = new licencia();
                ver99.setVisible(true);
            } else {
                JOptionPane.showInputDialog(null, "Necesita Privilegios Para Acceder", "Error!", JOptionPane.ERROR_MESSAGE);

            }

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new config().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea Conf_autoimpresor;
    private javax.swing.JButton btn_confcancelar;
    private javax.swing.JButton btn_contador;
    private javax.swing.JButton btn_examinar;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_usuactualizar;
    private javax.swing.JButton btn_usueditar;
    private javax.swing.JButton btn_usuexit;
    public static javax.swing.JLabel caj_cod;
    public static javax.swing.JTextField conf_actividad;
    public static javax.swing.JTextField conf_ciudad;
    public static javax.swing.JTextField conf_denominacion;
    public static javax.swing.JTextField conf_direccion;
    public static javax.swing.JTextField conf_email;
    public static javax.swing.JTextField conf_ruc;
    public static javax.swing.JTextField conf_sucursal;
    public static javax.swing.JTextField conf_telefono;
    public static javax.swing.JTextField conf_timbrado;
    public static javax.swing.JTextField conf_timbradoini;
    public static javax.swing.JTextField conf_timbradoven;
    public static javax.swing.JTextField conf_web;
    public static javax.swing.JTextField divisor1;
    public static javax.swing.JTextField divisor2;
    private javax.swing.JCheckBox id_barra;
    public static javax.swing.JLabel id_conf;
    private javax.swing.JCheckBox id_pro;
    public static javax.swing.JTextField iva1;
    public static javax.swing.JTextField iva2;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox_confact;
    private javax.swing.JCheckBox jCheckBox_sinfact;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JCheckBox jbox_matricial;
    public static javax.swing.JLabel milogo;
    public static javax.swing.JLabel mostrar_bus;
    public static javax.swing.JTextField mostrar_fac;
    private javax.swing.JTextField nombre_logo;
    public static javax.swing.JLabel su_cod;
    public static javax.swing.JTextField txt_sec;
    public static javax.swing.JTextField url_logo;
    // End of variables declaration//GEN-END:variables
}
