/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbstock;

import com.toedter.calendar.JDateChooser;
import static dbstock.Principal.btn_venta;
import static dbstock.Principal.jMenu_vta;
import static dbstock.Principal.sucursal_id;
import static dbstock.caja_exten.cierre_fecha;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;

import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import static jdk.nashorn.internal.runtime.regexp.joni.Syntax.Java;

/**
 *
 * @author Derlis
 */
public class DetalleVta extends javax.swing.JFrame {

    
        Statement st;
    Connection con;
    clsExportarExcel obj;
    
    /**
     * Creates new form DetalleVta
     */
    public DetalleVta() {
        initComponents();

        this.setLocationRelativeTo(null);//centra el formulario
        this.setTitle("Detalle Venta");
        setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE); //inabilida el uso del boton exit X

//        //MOSTRAR FECHA Y HORA DEL SISTEMA
//        Calendar Cal = Calendar.getInstance();
//        int currentday = (Cal.get(Cal.DATE));
//        int currentMonth = (Cal.get(Cal.MONTH) + 1);
//        int currentYear = (Cal.get(Cal.YEAR));
//
//        int mes, anyo, numDias = 0;
//        mes = currentMonth;
//        anyo = currentYear;
//        Calendar fecha = Calendar.getInstance();
//        fecha.set(anyo, mes, 0);
//        numDias = fecha.getActualMaximum(Calendar.DAY_OF_MONTH);
//        System.out.println("\nEl mes " + mes + " del año " + anyo + " tiene " + numDias + " días.");

        Calendar Cal= Calendar.getInstance();
        String fecha= Cal.get(Cal.DATE)+"/"+(Cal.get(Cal.MONTH)+1)+"/"+Cal.get(Cal.YEAR);
        fecha_txt.setText(fecha);
        


        
        
        metodoventa.CARGAR_JTABLE_venta_detalle();
        
        Conexion cc = new Conexion();
        Connection con = cc.conectar();
        String suma_pa = "select SUM(vta_montogs) from venta where vta_fecha='" + DetalleVta.fecha_txt.getText() + "'  and vta_anulado = 1 ";
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(suma_pa);
            if (rs.next()) {
                TXT_MONTO.setText(rs.getString("sum"));
            }
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(null, "error" + ex);
        }

        String count = "select count(*) from venta where vta_fecha='" + DetalleVta.fecha_txt.getText() + "'  and vta_anulado = 1 ";
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(count);
            if (rs.next()) {
                TXT_CANT.setText(rs.getString("count"));
            }
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(null, "error" + ex);
        }
           
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_vta = new javax.swing.JTable();
        btn_condicion = new javax.swing.JButton();
        jXSearch_bus = new org.jdesktop.swingx.JXSearchField();
        jCheckBox_contado = new javax.swing.JCheckBox();
        jCheckBox_credito = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        fecha_txt = new javax.swing.JLabel();
        TXT_MONTO = new javax.swing.JLabel();
        TXT_CANT = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        reload = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_vta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_vta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable_vtaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_vta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 1110, 480));

        btn_condicion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_condicion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/add-file.png"))); // NOI18N
        btn_condicion.setText("Nueva Venta");
        btn_condicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_condicionActionPerformed(evt);
            }
        });
        btn_condicion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_condicionKeyPressed(evt);
            }
        });
        getContentPane().add(btn_condicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, 40));

        jXSearch_bus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jXSearch_busKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jXSearch_busKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jXSearch_busKeyTyped(evt);
            }
        });
        getContentPane().add(jXSearch_bus, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 310, 40));

        jCheckBox_contado.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBox_contado.setForeground(new java.awt.Color(0, 102, 0));
        jCheckBox_contado.setSelected(true);
        jCheckBox_contado.setText("CONTADO");
        jCheckBox_contado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_contadoMouseClicked(evt);
            }
        });
        jCheckBox_contado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_contadoActionPerformed(evt);
            }
        });
        jCheckBox_contado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCheckBox_contadoKeyPressed(evt);
            }
        });
        getContentPane().add(jCheckBox_contado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 14, -1, 30));

        jCheckBox_credito.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBox_credito.setForeground(new java.awt.Color(204, 102, 0));
        jCheckBox_credito.setText("CREDITO");
        jCheckBox_credito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_creditoActionPerformed(evt);
            }
        });
        jCheckBox_credito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCheckBox_creditoKeyPressed(evt);
            }
        });
        getContentPane().add(jCheckBox_credito, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 14, -1, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/printer_2.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 90, 40));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/excel.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton6KeyPressed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 80, 40));

        fecha_txt.setBackground(new java.awt.Color(51, 51, 51));
        fecha_txt.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        fecha_txt.setForeground(new java.awt.Color(51, 51, 51));
        fecha_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecha_txt.setText("jLabel1");
        getContentPane().add(fecha_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 120, 40));

        TXT_MONTO.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        TXT_MONTO.setText("TXT_MONTO");
        getContentPane().add(TXT_MONTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 550, 150, -1));

        TXT_CANT.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        TXT_CANT.setText("TXT_CANT");
        getContentPane().add(TXT_CANT, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 550, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setText("CANTIDAD:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("MONTO TOTAL:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 550, -1, -1));

        reload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/reload.png"))); // NOI18N
        reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadActionPerformed(evt);
            }
        });
        reload.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                reloadKeyPressed(evt);
            }
        });
        getContentPane().add(reload, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 80, 40));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 1110, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/fondosistema.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 1160, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_condicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_condicionActionPerformed
        if (jCheckBox_contado.isSelected()) {
            vtacredito ver = new vtacredito();
            ver.setVisible(true);

            vtacredito.sucursal_vta.setText(sucursal_id.getText());

            String condicion = "CONTADO";
            vtacredito.cond.setText(condicion);
            vtacredito.jLabel_venta.setForeground((new Color(0, 153, 0)));

            jMenu_vta.setEnabled(false);
            btn_venta.setEnabled(false);
        }

        if (jCheckBox_credito.isSelected()) {
            vtacredito ver = new vtacredito();
            ver.setVisible(true);

            vtacredito.sucursal_vta.setText(sucursal_id.getText());

            String condicion = "CREDITO";
            vtacredito.cond.setText(condicion);
            vtacredito.jLabel_venta.setForeground(Color.ORANGE);

            jMenu_vta.setEnabled(false);
            btn_venta.setEnabled(false);
        }
        
    }//GEN-LAST:event_btn_condicionActionPerformed

    private void jCheckBox_contadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_contadoActionPerformed
        if (jCheckBox_contado.isSelected()) {
            jCheckBox_credito.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBox_contadoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            obj = new clsExportarExcel();
            obj.exportarExcel(jTable_vta);
        } catch (IOException ex) {
            //Logger.getLogger(JFExportar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jCheckBox_contadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_contadoMouseClicked
       
        

        
    }//GEN-LAST:event_jCheckBox_contadoMouseClicked

    private void jCheckBox_creditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_creditoActionPerformed
        if (jCheckBox_credito.isSelected()) {
            jCheckBox_contado.setSelected(false);
        }
        

    }//GEN-LAST:event_jCheckBox_creditoActionPerformed

    private void jXSearch_busKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jXSearch_busKeyTyped
        
        
        
                    
        String sql = "SELECT * FROM venta WHERE vta_cliente_nom  LIKE '%" + jXSearch_bus.getText() + "%' and vta_fecha = '"+fecha_txt.getText()+"' ORDER BY vta_num_deta";
        //System.out.println(sql);
        String[] titulo = {"ID", "Codigo", "Documento", "Nombre y Apellido", "Monto GS", "Monto US", "Item", "Caja", "Suc", "Condicion", "Fecha", "Vendedor"};
        DefaultTableModel mod = new DefaultTableModel(null, titulo);
        Object[] reg = new Object[12];
        Conexion cc = new Conexion();
        Connection con = cc.conectar();
        Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {

                DecimalFormat formatea = new DecimalFormat("###,###,###.##");
                reg[0] = rs.getString("vta_num_deta");
                reg[1] = rs.getString("vta_codigo");
                reg[2] = rs.getString("vta_cliente_id");
                reg[3] = rs.getString("vta_cliente_nom");
                reg[4] = formatea.format(rs.getInt("vta_montogs"));
                //reg[4]=rs.getString("vta_montogs");
                reg[5] = rs.getString("vta_montous");
                reg[6] = rs.getString("vta_cant");
                reg[7] = rs.getString("vta_caja");
                reg[8] = rs.getString("vta_suc");
                reg[9] = rs.getString("vta_condicion");
                reg[10] = rs.getString("vta_fecha");
                reg[11] = rs.getString("vta_vendedor");
                mod.addRow(reg);
            }
            jTable_vta.setModel(mod);
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "error " + e);
        }
        //forma de quetenga la barra orizontal////////////
        jTable_vta.setAutoResizeMode(jTable_vta.AUTO_RESIZE_OFF);
        jTable_vta.doLayout();

        //////////////////////////////////////////////////
        TableColumnModel columnModel = jTable_vta.getColumnModel();

        columnModel.getColumn(0).setPreferredWidth(50);
        columnModel.getColumn(1).setPreferredWidth(90);
        columnModel.getColumn(2).setPreferredWidth(100);
        columnModel.getColumn(3).setPreferredWidth(250);
        columnModel.getColumn(4).setPreferredWidth(90);
        columnModel.getColumn(5).setPreferredWidth(80);
        columnModel.getColumn(6).setPreferredWidth(50);
        columnModel.getColumn(7).setPreferredWidth(50);
        columnModel.getColumn(8).setPreferredWidth(50);
        columnModel.getColumn(9).setPreferredWidth(80);
        columnModel.getColumn(10).setPreferredWidth(90);
        columnModel.getColumn(11).setPreferredWidth(120);
	
        
    }//GEN-LAST:event_jXSearch_busKeyTyped

    private void jXSearch_busKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jXSearch_busKeyReleased
        metodos.convertiraMayusculasEnJtextfield(jXSearch_bus);
    }//GEN-LAST:event_jXSearch_busKeyReleased

    private void btn_condicionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_condicionKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            
            btn_condicion.doClick();
        }
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE) {
            jMenu_vta.setEnabled(true);
            btn_venta.setEnabled(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_condicionKeyPressed

    private void jCheckBox_contadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCheckBox_contadoKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE) {
            jMenu_vta.setEnabled(true);
            btn_venta.setEnabled(true);
            this.dispose();
        }
    }//GEN-LAST:event_jCheckBox_contadoKeyPressed

    private void jCheckBox_creditoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCheckBox_creditoKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE) {
            jMenu_vta.setEnabled(true);
            btn_venta.setEnabled(true);
            this.dispose();
        }
    }//GEN-LAST:event_jCheckBox_creditoKeyPressed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE) {
            jMenu_vta.setEnabled(true);
            btn_venta.setEnabled(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton4KeyPressed

    private void jButton6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton6KeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE) {
            jMenu_vta.setEnabled(true);
            btn_venta.setEnabled(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton6KeyPressed

    private void jXSearch_busKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jXSearch_busKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE) {
            jMenu_vta.setEnabled(true);
            btn_venta.setEnabled(true);
            this.dispose();
        }
    }//GEN-LAST:event_jXSearch_busKeyPressed

    private void jTable_vtaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable_vtaKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE) {
            jMenu_vta.setEnabled(true);
            btn_venta.setEnabled(true);
            this.dispose();
        }
    }//GEN-LAST:event_jTable_vtaKeyPressed

    private void reloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadActionPerformed
                metodoventa.CARGAR_JTABLE_venta_detalle();
        
        Conexion cc = new Conexion();
        Connection con = cc.conectar();
        String suma_pa = "select SUM(vta_montogs) from venta where vta_fecha='" + DetalleVta.fecha_txt.getText() + "'  and vta_anulado = 1 ";
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(suma_pa);
            if (rs.next()) {
                TXT_MONTO.setText(rs.getString("sum"));
            }
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(null, "error" + ex);
        }

        String count = "select count(*) from venta where vta_fecha='" + DetalleVta.fecha_txt.getText() + "'  and vta_anulado = 1 ";
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(count);
            if (rs.next()) {
                TXT_CANT.setText(rs.getString("count"));
            }
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(null, "error" + ex);
        }
    }//GEN-LAST:event_reloadActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            consulta_vta consulta = new consulta_vta();
            consulta.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void reloadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reloadKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE) {
            jMenu_vta.setEnabled(true);
            btn_venta.setEnabled(true);
            this.dispose();
        }
    }//GEN-LAST:event_reloadKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalleVta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalleVta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalleVta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalleVta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalleVta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TXT_CANT;
    private javax.swing.JLabel TXT_MONTO;
    public static javax.swing.JButton btn_condicion;
    public static javax.swing.JLabel fecha_txt;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox_contado;
    private javax.swing.JCheckBox jCheckBox_credito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_vta;
    private org.jdesktop.swingx.JXSearchField jXSearch_bus;
    public static javax.swing.JButton reload;
    // End of variables declaration//GEN-END:variables
}
