/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbstock;

import java.awt.event.KeyEvent;
import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;

/**
 *
 * @author Derlis
 */
public class gastos extends javax.swing.JFrame {

    /**
     * Creates new form gastos
     */
    
    Statement st;
    Connection con;
    DateFormat df = DateFormat.getDateInstance();
    public gastos() {
        initComponents();
        
        this.setLocationRelativeTo(null);//centra el formulario
        this.setTitle("Gastos");
        setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE); //inabilida el uso del boton exit X
        this.setResizable(false); //Disable the Resize Button
        
        metodoventa.cmb_sucursal_GASTO();
        metodogasto.cmb_sucursal_gasto();
        metodogasto.CARGAR_JTABLE_gasto();
        jpanel_filter.setVisible(false);

        
        Calendar Cal1= Calendar.getInstance();
        fecha_fin.setCalendar(Cal1);
        fecha_ini.setCalendar(Cal1);

        Calendar Cal= Calendar.getInstance();
        String fecha= Cal.get(Cal.DATE)+"/"+(Cal.get(Cal.MONTH)+1)+"/"+Cal.get(Cal.YEAR);
        fecha_inicial.setText(fecha);
        fecha_final.setText(fecha);
        
        fecha_inicial.setVisible(false);
        fecha_final.setVisible(false);
        monto.setVisible(false);
        id_caja1.setVisible(false);
        monto_gasto.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable_caja1 = new javax.swing.JTable();
        descri = new javax.swing.JLabel();
        cmb_sucu_gasto = new javax.swing.JComboBox<>();
        monto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        monto_gasto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        id_caja1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        obs_gasto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable_gasto = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        check_filter = new javax.swing.JCheckBox();
        check_todos = new javax.swing.JCheckBox();
        jpanel_filter = new javax.swing.JPanel();
        fecha_fin = new com.toedter.calendar.JDateChooser();
        fecha_ini = new com.toedter.calendar.JDateChooser();
        jButton5 = new javax.swing.JButton();
        cmb_suc_gasto = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fecha_inicial = new javax.swing.JTextField();
        fecha_final = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(619, 419));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(204, 255, 204));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Caja:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        jtable_caja1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable_caja1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_caja1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtable_caja1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 310, 150));

        descri.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        descri.setText("caja");
        jPanel1.add(descri, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 50, -1));

        cmb_sucu_gasto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_sucu_gasto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_sucu_gasto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_sucu_gastoMouseClicked(evt);
            }
        });
        cmb_sucu_gasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_sucu_gastoActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_sucu_gasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 230, -1));
        jPanel1.add(monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 120, -1));

        jLabel3.setText("Seleccione Caja");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        id.setText("id");
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 40, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("GASTOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/bien.png"))); // NOI18N
        jButton2.setText("Confirmar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 120, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/log-in.png"))); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 100, 40));

        monto_gasto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        monto_gasto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        monto_gasto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                monto_gastoKeyPressed(evt);
            }
        });
        jPanel1.add(monto_gasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 220, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Codigo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));
        jPanel1.add(id_caja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 40, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Observación");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Monto en GUARANIES");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        jLabel12.setText("Seleccione Sucursal");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        obs_gasto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                obs_gastoKeyPressed(evt);
            }
        });
        jPanel1.add(obs_gasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 560, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/fondosistema.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 350));

        jTabbedPane1.addTab("Gastos", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtable_gasto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtable_gasto);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 580, 200));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 110, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Imprimir");
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 110, 30));

        check_filter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        check_filter.setText("Filtrar");
        check_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_filterActionPerformed(evt);
            }
        });
        jPanel2.add(check_filter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        check_todos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        check_todos.setSelected(true);
        check_todos.setText("Todos los Gastos");
        check_todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_todosActionPerformed(evt);
            }
        });
        jPanel2.add(check_todos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jpanel_filter.setBackground(new java.awt.Color(204, 204, 204));
        jpanel_filter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jpanel_filter.add(fecha_fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 140, -1));
        jpanel_filter.add(fecha_ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/buscarcli.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jpanel_filter.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 13, 50, 40));

        cmb_suc_gasto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jpanel_filter.add(cmb_suc_gasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 210, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Seleccione Sucursal");
        jpanel_filter.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Hasta");
        jpanel_filter.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Desde");
        jpanel_filter.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel2.add(jpanel_filter, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 370, 90));
        jPanel2.add(fecha_inicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 60, -1));
        jPanel2.add(fecha_final, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 60, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/fondosistema.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 350));

        jTabbedPane1.addTab("Detalle de Gastos", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_sucu_gastoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_sucu_gastoMouseClicked
        metodoventa.gasto();

        Conexion cc = new Conexion();
        Connection con = cc.conectar();;
        try {
            String[] titulo = {"Codigo", "Descripcion", "Monto GS"};
            DefaultTableModel mod = new DefaultTableModel(null, titulo);
            Object[] reg = new Object[7];
            String sql = "Select * from caja where '" +id_caja1.getText()+ "' = caj_suc ";
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {

                reg[0] = rs.getString("caj_codigo");
                reg[1] = rs.getString("caj_descri");
                reg[2] = rs.getString("caj_montogs");
                mod.addRow(reg);
            }
            jtable_caja1.setModel(mod);

            TableColumnModel columnModel = jtable_caja1.getColumnModel();

            columnModel.getColumn(0).setPreferredWidth(50);
            columnModel.getColumn(1).setPreferredWidth(120);
            columnModel.getColumn(2).setPreferredWidth(100);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_cmb_sucu_gastoMouseClicked

    private void cmb_sucu_gastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_sucu_gastoActionPerformed
        metodoventa.gasto();

        Conexion cc = new Conexion();
        Connection con = cc.conectar();;
        try {
            String[] titulo = {"Codigo", "Descripcion", "Monto GS"};
            DefaultTableModel mod = new DefaultTableModel(null, titulo);
            Object[] reg = new Object[7];
            String sql = "Select * from caja where '" +id_caja1.getText()+ "' = caj_suc ";
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {

                reg[0] = rs.getString("caj_codigo");
                reg[1] = rs.getString("caj_descri");
                reg[2] = rs.getString("caj_montogs");
                mod.addRow(reg);
            }
            jtable_caja1.setModel(mod);

            TableColumnModel columnModel = jtable_caja1.getColumnModel();

            columnModel.getColumn(0).setPreferredWidth(50);
            columnModel.getColumn(1).setPreferredWidth(120);
            columnModel.getColumn(2).setPreferredWidth(100);
        } catch (SQLException e) {
            //JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_cmb_sucu_gastoActionPerformed

    private void jtable_caja1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_caja1MouseClicked

        int n1 = jtable_caja1.getSelectedRow();
        String id1 = jtable_caja1.getValueAt(n1, 0).toString();
        id.setText(id1);

        int n2 = jtable_caja1.getSelectedRow();
        String id2 = jtable_caja1.getValueAt(n2, 1).toString();
        descri.setText(id2);

        int n3 = jtable_caja1.getSelectedRow();
        String id3 = jtable_caja1.getValueAt(n3, 2).toString();
        monto.setText(id3);
        
        monto_gasto.setEnabled(true);      
        monto_gasto.requestFocus();

    }//GEN-LAST:event_jtable_caja1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //caja_exten.reload_button.doClick();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(obs_gasto.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Agregue una Observación sobre el gasto");
            obs_gasto.requestFocus();
        }else{
                    
                String monto1 = monto.getText();
                String monto_ingre = monto_gasto.getText();
                                
                int montoo = parseInt(monto1);
                int monto_ingresa = parseInt(monto_ingre);
                
                if (monto_ingresa <= montoo) {
                    
                    int rest = montoo - monto_ingresa;
                    
                    Conexion cc=new Conexion();
                    Connection con=cc.conectar();
                    try {
                    String updarest = "UPDATE caja SET caj_montogs = '"+rest+"'"
                    + " where caj_codigo = '"+id.getText()+"' and caj_suc = '"+id_caja1.getText()+"' ";
                    st = con.createStatement();
                    st.execute(updarest);              

                    }catch(SQLException ex){
                            System.out.println("ver error " + ex.getMessage());
                    }
                    
                    int estadogasto=1;
                    try {       
                    String sqlinser = "INSERT INTO gastos (gas_suc, gas_cajaid, gas_cajades, gas_montogs,"
                    + "gas_obs,gas_fecha,gas_sucdes, gas_usuario,ci_estado) "
                    + "values ('"+id_caja1.getText()+"','"+id.getText()+"','"+descri.getText()+"','"+monto_gasto.getText()+"',"
                    + "'"+obs_gasto.getText()+"','"+Principal.fecha_ini.getText()+"','"+cmb_sucu_gasto.getSelectedItem()+"',"
                            + " '"+Principal.usuario_ini.getText()+"','"+estadogasto+"')";	

                    st = con.createStatement();			
                    st.execute(sqlinser); 
                    
                    JOptionPane.showMessageDialog(null, "Gasto realizado con exito"); 
                   } catch (SQLException ex) {
                      System.out.println("ver error " + ex.getMessage());

                   }  
                    monto_gasto.setText("");
                    obs_gasto.setText("");
                }else{
                   JOptionPane.showMessageDialog(null, "Gasto no puede ser mayor al monto que hay en caja"); 
                   monto_gasto.setText("");
                   monto_gasto.requestFocus();
                }
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void check_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_filterActionPerformed
      if(check_filter.isSelected()){
         this.check_todos.setSelected(false);
         jpanel_filter.setVisible(true);
      }else{
         this.check_todos.setSelected(true);
         jpanel_filter.setVisible(false);
      }
        
    }//GEN-LAST:event_check_filterActionPerformed

    private void check_todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_todosActionPerformed
        if(check_todos.isSelected()){
         this.check_filter.setSelected(false);
         jpanel_filter.setVisible(false);
         metodogasto.CARGAR_JTABLE_gasto();
      }else{
         this.check_filter.setSelected(true);
         jpanel_filter.setVisible(true);
            
        }
    }//GEN-LAST:event_check_todosActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String fechaObtenida = df.format(fecha_ini.getDate());
        fecha_inicial.setText(fechaObtenida);

        String fechafinal = df.format(fecha_fin.getDate());
        fecha_final.setText(fechafinal);  
        
        metodogasto.CARGAR_JTABLE_gasto_bus();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void monto_gastoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monto_gastoKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
          obs_gasto.requestFocus();
      }
    }//GEN-LAST:event_monto_gastoKeyPressed

    private void obs_gastoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_obs_gastoKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
          jButton2.requestFocus();
          
      }
    }//GEN-LAST:event_obs_gastoKeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
          jButton2.doClick();
          
      }
    }//GEN-LAST:event_jButton2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gastos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox check_filter;
    private javax.swing.JCheckBox check_todos;
    public static javax.swing.JComboBox<String> cmb_suc_gasto;
    public static javax.swing.JComboBox<String> cmb_sucu_gasto;
    private javax.swing.JLabel descri;
    private com.toedter.calendar.JDateChooser fecha_fin;
    public static javax.swing.JTextField fecha_final;
    private com.toedter.calendar.JDateChooser fecha_ini;
    public static javax.swing.JTextField fecha_inicial;
    private javax.swing.JLabel id;
    public static javax.swing.JTextField id_caja1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpanel_filter;
    public static javax.swing.JTable jtable_caja1;
    public static javax.swing.JTable jtable_gasto;
    private javax.swing.JTextField monto;
    private javax.swing.JTextField monto_gasto;
    private javax.swing.JTextField obs_gasto;
    // End of variables declaration//GEN-END:variables
}
