/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbstock;

import static dbstock.usuario.cmb_privilegios;
import static dbstock.usuario.jTable_usuario;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Derlis
 */
public class grupo_prov extends javax.swing.JFrame {

    
    Statement st;
    Connection con;
    /**
     * Creates new form grupo_prov
     */
    public grupo_prov() {
        initComponents();
        this.setLocationRelativeTo(null);//centra el formulario
        this.setTitle("Grupo de Productos");
        
        metodos.CARGAR_JTABLE_grupo();
        
       grupo_id.setEnabled(false);
       grupo_desc.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        grupo_desc = new javax.swing.JTextField();
        grupo_id = new javax.swing.JTextField();
        btn_usunuevo = new javax.swing.JButton();
        btn_usuguardar = new javax.swing.JButton();
        btn_usueditar = new javax.swing.JButton();
        btn_usucalcelar = new javax.swing.JButton();
        btn_usueliminar = new javax.swing.JButton();
        btn_usuexit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_grupo = new javax.swing.JTable();
        btn_usuactualizar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(590, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("REGISTRO DE GRUPO DE PRODUCTOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Descripción:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 80, 20));

        grupo_desc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        grupo_desc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                grupo_descKeyTyped(evt);
            }
        });
        getContentPane().add(grupo_desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 350, -1));

        grupo_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        grupo_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                grupo_idKeyTyped(evt);
            }
        });
        getContentPane().add(grupo_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 50, -1));

        btn_usunuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/add-file.png"))); // NOI18N
        btn_usunuevo.setText("Nuevo");
        btn_usunuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usunuevoActionPerformed(evt);
            }
        });
        btn_usunuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_usunuevoKeyPressed(evt);
            }
        });
        getContentPane().add(btn_usunuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 40));

        btn_usuguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/save.png"))); // NOI18N
        btn_usuguardar.setText("Guardar");
        btn_usuguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usuguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 100, 40));

        btn_usueditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/editar.png"))); // NOI18N
        btn_usueditar.setText("Editar");
        btn_usueditar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_usueditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usueditarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usueditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 90, 40));

        btn_usucalcelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/x-button.png"))); // NOI18N
        btn_usucalcelar.setText("Cancelar");
        btn_usucalcelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usucalcelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usucalcelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, 40));

        btn_usueliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/eliminar.png"))); // NOI18N
        btn_usueliminar.setText("Eliminar");
        btn_usueliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usueliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usueliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 100, 40));

        btn_usuexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/exit.png"))); // NOI18N
        btn_usuexit.setText("Salir");
        btn_usuexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuexitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usuexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 90, 40));

        jTable_grupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_grupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_grupoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_grupo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 450, 150));

        btn_usuactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/reload.png"))); // NOI18N
        btn_usuactualizar.setText("Actualizar");
        btn_usuactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuactualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usuactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 100, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Id Grupo:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 80, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/fondosistema.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grupo_descKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_grupo_descKeyTyped
         ////convertir a mayusculas
        char c6 = evt.getKeyChar(); 
        if(Character.isLowerCase(c6)){
            String cad = ("" + c6).toUpperCase();
            c6 = cad.charAt(0);
            evt.setKeyChar(c6);
        }

    }//GEN-LAST:event_grupo_descKeyTyped

    private void grupo_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_grupo_idKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_grupo_idKeyTyped

    private void btn_usunuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usunuevoActionPerformed

        //////////////////////////////fecha del sistema
        //  SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        //	Date fechaActual = new Date();
        //	pro_vencimineto.setText(sdf.format(fechaActual));
        //////////////////////////////

        grupo_id.setEnabled(false);
        grupo_desc.setEnabled(true);
      

        btn_usunuevo.setEnabled(false);
        btn_usuguardar.setEnabled(true);
        btn_usuactualizar.setEnabled(false);
        btn_usueditar.setEnabled(false);
        btn_usueliminar.setEnabled(false);
        btn_usucalcelar.setEnabled(true);
        btn_usuexit.setEnabled(true);
        
        grupo_desc.requestFocus();

        
                grupo_desc.setText("");
                //productos.cmb_grupo.setSelectedItem("");
                grupo_id.setText("");
   
       
    }//GEN-LAST:event_btn_usunuevoActionPerformed

    private void btn_usuguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuguardarActionPerformed

        int aux  =  JOptionPane.showConfirmDialog(null, "Desea Guardar el Registro?","OBSERVACION", JOptionPane.YES_NO_OPTION);
        if(aux == JOptionPane.YES_OPTION){

            Conexion cc=new Conexion();
            Connection con=cc.conectar();
            try {

                String sql = "INSERT INTO grupopro (grup_desc) "
                + "values ('"+grupo_desc.getText()+"')";

                st = con.createStatement();
                st.execute(sql);
              
              metodos.CARGAR_JTABLE_grupo();
              
                grupo_id.setEnabled(false);
                grupo_desc.setEnabled(false);
                
                grupo_id.setText("");
                grupo_desc.setText("");

                btn_usuguardar.setVisible(true);
                btn_usunuevo.setEnabled(true);
                btn_usuguardar.setEnabled(false);
                btn_usuactualizar.setEnabled(false);
                btn_usueditar.setEnabled(false);
                btn_usueliminar.setEnabled(false);
                btn_usucalcelar.setEnabled(false);
                btn_usuexit.setEnabled(true);
            
                grupo_desc.setEnabled(false);
       

            } catch (SQLException ex) {
                System.out.println("ver error " + ex.getMessage());
                JOptionPane.showMessageDialog(null, "error" + ex);
            }
        }
    }//GEN-LAST:event_btn_usuguardarActionPerformed

    private void btn_usueditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usueditarActionPerformed

        grupo_id.setEnabled(true);
        grupo_desc.setEnabled(true);


        btn_usuguardar.setVisible(false);
        btn_usuactualizar.setVisible(true);

        btn_usunuevo.setEnabled(false);
        btn_usuguardar.setEnabled(false);
        btn_usuactualizar.setEnabled(true);
        btn_usueditar.setEnabled(false);
        btn_usueliminar.setEnabled(false);
        btn_usucalcelar.setEnabled(true);
        btn_usuexit.setEnabled(true);

    //    grupo_id.setText("");
    //    grupo_desc.setText("");
      
    }//GEN-LAST:event_btn_usueditarActionPerformed

    private void btn_usucalcelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usucalcelarActionPerformed

        int aux  =  JOptionPane.showConfirmDialog(null, "Desea Cancelar Registro?","OBSERVACION", JOptionPane.YES_NO_OPTION);
        if(aux == JOptionPane.YES_OPTION){

        grupo_id.setEnabled(false);
        grupo_desc.setEnabled(false);

            btn_usuguardar.setVisible(true);
            btn_usunuevo.setEnabled(true);
            btn_usuguardar.setEnabled(false);
            btn_usuactualizar.setEnabled(false);
            btn_usueditar.setEnabled(false);
            btn_usueliminar.setEnabled(false);
            btn_usucalcelar.setEnabled(false);
            btn_usuexit.setEnabled(true);

        }
    }//GEN-LAST:event_btn_usucalcelarActionPerformed

    private void btn_usueliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usueliminarActionPerformed

        int aux  =  JOptionPane.showConfirmDialog(null, "Desea eliminar ","Sistema Ficha del cliente", JOptionPane.YES_NO_OPTION);

        if(aux == JOptionPane.YES_OPTION){

            int nz = jTable_grupo.getSelectedRow();
            String id = jTable_grupo.getValueAt(nz, 0).toString();
            grupo_id.setText(id);

            Conexion cc=new Conexion();
            Connection con=cc.conectar();

            try {

                String sql = "delete from productos where pro_id = '"+grupo_id.getText()+"' ";
                st = con.createStatement();

                st.execute(sql);
                
                metodos.CARGAR_JTABLE_grupo();
                
                grupo_id.setText("");
                grupo_desc.setText("");
                
                grupo_id.setEnabled(false);
                grupo_desc.setEnabled(false);


                btn_usuguardar.setVisible(true);
                btn_usunuevo.setEnabled(true);
                btn_usuguardar.setEnabled(false);
                btn_usuactualizar.setEnabled(false);
                btn_usueditar.setEnabled(false);
                btn_usueliminar.setEnabled(false);
                btn_usucalcelar.setEnabled(false);
                btn_usuexit.setEnabled(true);

            }catch (Exception ee) {
                ee.printStackTrace();
            }

        }else{if(aux == JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(null,  "Cancelado", "Sistema", JOptionPane.INFORMATION_MESSAGE);

        }

        }
    }//GEN-LAST:event_btn_usueliminarActionPerformed

    private void btn_usuexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuexitActionPerformed
        dispose();

    }//GEN-LAST:event_btn_usuexitActionPerformed

    private void btn_usuactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuactualizarActionPerformed

        int aux  =  JOptionPane.showConfirmDialog(null, "Desea Actualizar los Datos","OBSERVACION", JOptionPane.YES_NO_OPTION);
        if(aux == JOptionPane.YES_OPTION){

            Conexion cc=new Conexion();
            Connection con=cc.conectar();
            try {

                String sql = "UPDATE productos SET grupopro = '"+grupo_desc.getText()+"'  where pro_id = '"+grupo_id.getText()+"'";

                st = con.createStatement();

                st.execute(sql);

                JOptionPane.showMessageDialog(null,  "Registro Actualizado", "Usuarios", JOptionPane.INFORMATION_MESSAGE);

             metodos.CARGAR_JTABLE_grupo();

                btn_usuguardar.setVisible(true);
                btn_usuactualizar.setVisible(false);

                btn_usunuevo.setEnabled(true);
                btn_usuguardar.setEnabled(false);
                btn_usuactualizar.setEnabled(false);
                btn_usueditar.setEnabled(false);
                btn_usueliminar.setEnabled(false);
                btn_usucalcelar.setEnabled(false);
                btn_usuexit.setEnabled(true);

            metodos.CARGAR_JTABLE_grupo();
                grupo_id.setEnabled(false);
                grupo_desc.setEnabled(false);

            } catch (SQLException ex) {
                System.out.println("ver error " + ex.getMessage());

            }
        }
    }//GEN-LAST:event_btn_usuactualizarActionPerformed

    private void jTable_grupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_grupoMouseClicked
        
        grupo_id.setEnabled(false);
        grupo_desc.setEnabled(false);

          btn_usunuevo.setEnabled(true);
          btn_usuguardar.setEnabled(false);
          btn_usuactualizar.setEnabled(false);
          btn_usueditar.setEnabled(true);
          btn_usueliminar.setEnabled(true);
          btn_usucalcelar.setEnabled(false);
          btn_usuexit.setEnabled(true);
        
        int n0 = jTable_grupo.getSelectedRow();
        String id = jTable_grupo.getValueAt(n0, 0).toString();
        grupo_id.setText(id);
        
 		Conexion cc=new Conexion();
		Connection con=cc.conectar();;
        	try {

		String sql = "Select * from grupopro where grup_id = '"+grupo_id.getText()+"'";
		//ResultSet resultado = st.executeQuery(sql);
                st = con.createStatement();
                ResultSet rs=st.executeQuery(sql);
		if (rs.next()) {
                        grupo_id.setText(rs.getString("grup_id"));
                        grupo_desc.setText(rs.getString("grup_desc"));

                    }
			rs.close();
			st.close();
			con.close();

		} catch (SQLException e) {
			JOptionPane.showMessageDialog(null, e.getMessage());
		}
        
    }//GEN-LAST:event_jTable_grupoMouseClicked

    private void btn_usunuevoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_usunuevoKeyPressed
    
         if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
             btn_usunuevo.doClick();
         }
        
        
    }//GEN-LAST:event_btn_usunuevoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(grupo_prov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(grupo_prov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(grupo_prov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(grupo_prov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new grupo_prov().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_usuactualizar;
    private javax.swing.JButton btn_usucalcelar;
    private javax.swing.JButton btn_usueditar;
    private javax.swing.JButton btn_usueliminar;
    private javax.swing.JButton btn_usuexit;
    private javax.swing.JButton btn_usuguardar;
    private javax.swing.JButton btn_usunuevo;
    public static javax.swing.JTextField grupo_desc;
    public static javax.swing.JTextField grupo_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_grupo;
    // End of variables declaration//GEN-END:variables
}
