/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbstock;

import static dbstock.metodos.st;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author de_britez
 */
public class licencia extends javax.swing.JFrame {

    /**
     * Creates new form licencia
     */
    public licencia() {
        initComponents();

        this.setLocationRelativeTo(null);//centra el formulario

        Calendar Cal = Calendar.getInstance();
        jDatelicencia.setCalendar(Cal);

        
        id.setVisible(false);
        estirar();

        Conexion cc = new Conexion();
        Connection con = cc.conectar();;
        try {

            //String sql = "Select * from config where conf_ruc = '"+config.conf_ruc.getText()+"'";
            String sql = "Select * from config";
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {

                id.setText(rs.getString("conf_id"));

            }
            rs.close();
            st.close();
            con.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

    public void estirar() {

        Conexion cc = new Conexion();
        Connection con = cc.conectar();;
        try {

            String sql = "Select * from config";
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {

                txt_licencia.setText(rs.getString("conf_licencia"));

            }
//            rs.close();
//            st.close();
//            con.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        
        password.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        password = new org.edisoncor.gui.passwordField.PasswordFieldRound();
        jDatelicencia = new com.toedter.calendar.JDateChooser();
        buttonNice1 = new org.edisoncor.gui.button.ButtonNice();
        clockFace1 = new org.edisoncor.gui.varios.ClockFace();
        id = new javax.swing.JLabel();
        txt_licencia = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 170, 30));

        jDatelicencia.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jDatelicencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDatelicenciaKeyPressed(evt);
            }
        });
        getContentPane().add(jDatelicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 170, -1));

        buttonNice1.setBackground(new java.awt.Color(102, 102, 102));
        buttonNice1.setForeground(new java.awt.Color(51, 51, 51));
        buttonNice1.setText("ACTIVAR");
        buttonNice1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        buttonNice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNice1ActionPerformed(evt);
            }
        });
        buttonNice1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonNice1KeyPressed(evt);
            }
        });
        getContentPane().add(buttonNice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 200, 30));
        getContentPane().add(clockFace1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 100, 100));

        id.setText("id");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 40, 30));

        txt_licencia.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txt_licencia.setForeground(new java.awt.Color(204, 0, 0));
        txt_licencia.setText("txt_licen");
        getContentPane().add(txt_licencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 130, 20));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nueva Fecha");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 170, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Licencia Expira :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 120, 20));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/fondo_licencia.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 360));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Licencias");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 200, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void buttonNice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNice1ActionPerformed

        int aux = JOptionPane.showConfirmDialog(null, "Actualizar Fecha de Expiración", "OBSERVACION", JOptionPane.YES_NO_OPTION);
        if (aux == JOptionPane.YES_OPTION) {

            //char[] contraseña = password.getPassword();
            String passText = new String(password.getPassword());

            if ("dbstock14512".equals(passText)) {

                Conexion cc = new Conexion();
                Connection con = cc.conectar();
                try {

                    String sql = "UPDATE config SET conf_licencia = '" + jDatelicencia.getDate() + "' where conf_id = '" + id.getText() + "'";

                    st = con.createStatement();

                    st.execute(sql);

                    Icon icono = new ImageIcon(getClass().getResource("\\img\\comprobado.png"));
                    JOptionPane.showMessageDialog(null, " Licencia Activada Exitosamente hasta la fecha " + jDatelicencia.getDate(), "EXITOSO", JOptionPane.PLAIN_MESSAGE, icono);
                    JOptionPane.showMessageDialog(null, " ACTIVADO EXITOSAMENTE ", "EXITOSO", JOptionPane.PLAIN_MESSAGE, icono);
                    //JOptionPane.showMessageDialog(null, "Licencia Activada Exitosamente hasta la fecha "+ jDatelicencia.getDate() );

                    estirar();
                    
                    password.setText("");
                    
                    jDatelicencia.setEnabled(false);
                    
                    
                    Principal.licencia_porvencer.setVisible(false);
                    Principal.licencia_porvencer1.setVisible(false);
                    Principal.licencia_porvencer2.setVisible(false);
                    Principal.btn_licencia.setVisible(false); 
                    this.dispose();
                    
                    
                    
                } catch (Exception e) {
                    
                    JOptionPane.showMessageDialog(null, "Error nose Actualizo la Licencia");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Contraseña Equivocada");
                password.setText("");
                password.requestFocus();
            }

        }

    }//GEN-LAST:event_buttonNice1ActionPerformed

    private void jDatelicenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDatelicenciaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_jDatelicenciaKeyPressed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buttonNice1.requestFocus();
        }

    }//GEN-LAST:event_passwordKeyPressed

    private void buttonNice1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonNice1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buttonNice1.doClick();
        }
    }//GEN-LAST:event_buttonNice1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(licencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(licencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(licencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(licencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new licencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonNice buttonNice1;
    private org.edisoncor.gui.varios.ClockFace clockFace1;
    private javax.swing.JLabel id;
    private com.toedter.calendar.JDateChooser jDatelicencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private org.edisoncor.gui.passwordField.PasswordFieldRound password;
    private javax.swing.JLabel txt_licencia;
    // End of variables declaration//GEN-END:variables
}
