/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbstock;

import static dbstock.metodos.st;
import static dbstock.saldo_caja.jtable_caja;
import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;

/**
 *
 * @author Derlis
 */
public class mov_caja extends javax.swing.JFrame {

    /**
     * Creates new form mov_caja
     */
    public mov_caja() {
        initComponents();
        
        this.setLocationRelativeTo(null);//centra el formulario
        this.setTitle("Movimiento entre Cajas");
        
        metodoventa.cmb_sucursal_mov2();
        metodoventa.cmb_sucursal_mov1();
        
        cmb_sucu2.setVisible(false);
        jtable_caja2.setVisible(false);
        id.setVisible(false);
        descri.setVisible(false);
        monto.setVisible(false);
        id2.setVisible(false);
        descri2.setVisible(false);
        monto2.setVisible(false);
        id_caja2.setVisible(false);
        id_caja1.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmb_sucu1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmb_sucu2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable_caja2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable_caja1 = new javax.swing.JTable();
        monto_ingresado = new javax.swing.JTextField();
        obs_mov1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        id_caja1 = new javax.swing.JTextField();
        id_caja2 = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        monto = new javax.swing.JTextField();
        descri = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        id2 = new javax.swing.JTextField();
        descri2 = new javax.swing.JTextField();
        monto2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        obs_mov2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ENVIAR A:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 100, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("MOVIMIENTO ENTRE CAJAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 430, -1));

        cmb_sucu1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_sucu1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_sucu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_sucu1MouseClicked(evt);
            }
        });
        cmb_sucu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_sucu1ActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_sucu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 230, -1));

        jLabel3.setText("Seleccione Sucursal");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        cmb_sucu2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_sucu2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_sucu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_sucu2MouseClicked(evt);
            }
        });
        cmb_sucu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_sucu2ActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_sucu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 230, -1));

        jLabel4.setText("Seleccione Sucursal");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        jtable_caja2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable_caja2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_caja2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtable_caja2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 310, 170));

        jtable_caja1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable_caja1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_caja1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtable_caja1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 310, 170));

        monto_ingresado.setBackground(new java.awt.Color(204, 255, 204));
        monto_ingresado.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        monto_ingresado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(monto_ingresado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 210, 40));

        obs_mov1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(obs_mov1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 380, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/exit.png"))); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 90, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/sent.png"))); // NOI18N
        jButton2.setText("Enviar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 120, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("ENVIAR DE:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/shuffle.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 40, -1));
        getContentPane().add(id_caja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 40, -1));
        getContentPane().add(id_caja2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 40, -1));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 70, -1));
        getContentPane().add(monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 120, -1));
        getContentPane().add(descri, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 110, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Monto GS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, 20));
        getContentPane().add(id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 60, -1));
        getContentPane().add(descri2, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 320, 110, -1));
        getContentPane().add(monto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 340, 120, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Observación:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        obs_mov2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(obs_mov2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 380, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/fondosistema.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmb_sucu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_sucu1MouseClicked
        metodoventa.mov_entrecaja(); 
        
        Conexion cc = new Conexion();
        Connection con = cc.conectar();;
        try {
            String[] titulo = {"Codigo", "Descripcion", "Monto GS"};
            DefaultTableModel mod = new DefaultTableModel(null, titulo);
            Object[] reg = new Object[7];
            String sql = "Select * from caja where '" +id_caja1.getText()+ "' = caj_suc ";
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {

                reg[0] = rs.getString("caj_codigo");
                reg[1] = rs.getString("caj_descri");
                reg[2] = rs.getString("caj_montogs");
                mod.addRow(reg);
            }
            jtable_caja1.setModel(mod);

            TableColumnModel columnModel = jtable_caja1.getColumnModel();

            columnModel.getColumn(0).setPreferredWidth(50);
            columnModel.getColumn(1).setPreferredWidth(120);
            columnModel.getColumn(2).setPreferredWidth(100);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_cmb_sucu1MouseClicked

    private void cmb_sucu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_sucu1ActionPerformed
        metodoventa.mov_entrecaja();
        
        Conexion cc = new Conexion();
        Connection con = cc.conectar();;
        try {
            String[] titulo = {"Codigo", "Descripcion", "Monto GS"};
            DefaultTableModel mod = new DefaultTableModel(null, titulo);
            Object[] reg = new Object[7];
            String sql = "Select * from caja where '" +id_caja1.getText()+ "' = caj_suc ";
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {

                reg[0] = rs.getString("caj_codigo");
                reg[1] = rs.getString("caj_descri");
                reg[2] = rs.getString("caj_montogs");
                mod.addRow(reg);
            }
            jtable_caja1.setModel(mod);

            TableColumnModel columnModel = jtable_caja1.getColumnModel();

            columnModel.getColumn(0).setPreferredWidth(50);
            columnModel.getColumn(1).setPreferredWidth(120);
            columnModel.getColumn(2).setPreferredWidth(100);
        } catch (SQLException e) {
            //JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_cmb_sucu1ActionPerformed

    private void jtable_caja2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_caja2MouseClicked

        
        int n4 = jtable_caja2.getSelectedRow();
        String id1 = jtable_caja2.getValueAt(n4, 0).toString();
        id2.setText(id1);
        
        int n5 = jtable_caja2.getSelectedRow();
        String id2 = jtable_caja2.getValueAt(n5, 1).toString();
        descri2.setText(id2);
        
        int n6 = jtable_caja2.getSelectedRow();
        String id3 = jtable_caja2.getValueAt(n6, 2).toString();
        monto2.setText(id3);
        
        
    }//GEN-LAST:event_jtable_caja2MouseClicked

    private void cmb_sucu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_sucu2ActionPerformed
        metodoventa.mov_entrecaja2();
        
        Conexion cc = new Conexion();
        Connection con = cc.conectar();;
        try {
            String[] titulo = {"Codigo", "Descripcion", "Monto GS"};
            DefaultTableModel mod = new DefaultTableModel(null, titulo);
            Object[] reg = new Object[7];
            String sql = "Select * from caja where '" +id_caja2.getText()+ "' = caj_suc ";
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {

                reg[0] = rs.getString("caj_codigo");
                reg[1] = rs.getString("caj_descri");
                reg[2] = rs.getString("caj_montogs");
                mod.addRow(reg);
            }
            jtable_caja2.setModel(mod);

            TableColumnModel columnModel = jtable_caja2.getColumnModel();

            columnModel.getColumn(0).setPreferredWidth(50);
            columnModel.getColumn(1).setPreferredWidth(120);
            columnModel.getColumn(2).setPreferredWidth(100);
        } catch (SQLException e) {
           // JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_cmb_sucu2ActionPerformed

    private void cmb_sucu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_sucu2MouseClicked
        metodoventa.mov_entrecaja2();
        
        Conexion cc = new Conexion();
        Connection con = cc.conectar();
        try {
            String[] titulo = {"Codigo", "Descripcion", "Monto GS"};
            DefaultTableModel mod = new DefaultTableModel(null, titulo);
            Object[] reg = new Object[7];
            String sql = "Select * from caja where '" +id_caja2.getText()+ "' = caj_suc ";
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {

                reg[0] = rs.getString("caj_codigo");
                reg[1] = rs.getString("caj_descri");
                reg[2] = rs.getString("caj_montogs");
                mod.addRow(reg);
            }
            jtable_caja2.setModel(mod);

            TableColumnModel columnModel = jtable_caja2.getColumnModel();

            columnModel.getColumn(0).setPreferredWidth(50);
            columnModel.getColumn(1).setPreferredWidth(120);
            columnModel.getColumn(2).setPreferredWidth(100);
        } catch (SQLException e) {
           // JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_cmb_sucu2MouseClicked

    private void jtable_caja1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_caja1MouseClicked
      
        int n1 = jtable_caja1.getSelectedRow();
        String id1 = jtable_caja1.getValueAt(n1, 0).toString();
        id.setText(id1);
        
        int n2 = jtable_caja1.getSelectedRow();
        String id2 = jtable_caja1.getValueAt(n2, 1).toString();
        descri.setText(id2);
        
        int n3 = jtable_caja1.getSelectedRow();
        String id3 = jtable_caja1.getValueAt(n3, 2).toString();
        monto.setText(id3);
        
        
        cmb_sucu2.setVisible(true);
        jtable_caja2.setVisible(true);
        
    }//GEN-LAST:event_jtable_caja1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        if(id2.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "SELECCIONE CAJA RECEPTOR");
        }else{
            String cja1 = id.getText();
            String cja2 = id2.getText();
            
            String suc1 = id_caja1.getText();
            String suc2 = id_caja2.getText();
            
            int entero123 = parseInt(suc1);
            int entero233 = parseInt(suc2);
            
            int ent1 = parseInt(cja1);
            int ent2 = parseInt(cja2);
            
            if( (entero233 == entero123)&& (ent1 == ent2 ) ){
               JOptionPane.showMessageDialog(null, "No puede enviar a la misma caja");

            }else{
                             
                String monto1 = monto.getText();
                String monto_ingre = monto_ingresado.getText();
                String monto_recibi = monto2.getText();
                
                int montoo = parseInt(monto1);
                int monto_ingresa = parseInt(monto_ingre);
                int monto_recibido = parseInt(monto_recibi);
                
                if (monto_ingresa <= montoo) {
                    int suma_caja = monto_ingresa + monto_recibido;                
                    int resta_caja = montoo - monto_ingresa;
                    
                    Conexion cc = new Conexion();
                    Connection con = cc.conectar();
                    try {
                    String upda = "UPDATE caja SET caj_montogs = '"+suma_caja+"'"
                    + " where caj_codigo = '"+id2.getText()+"' and caj_suc = '"+id_caja2.getText()+"' ";
                    st = con.createStatement();
                    st.execute(upda);              
                                  
                    metodoventa.mov_entrecaja();
                    metodoventa.mov_entrecaja2();
                    }catch(SQLException ex){

                    }
                    
                    
                    try {
                    String updaresta = "UPDATE caja SET caj_montogs = '"+resta_caja+"'"
                    + " where caj_codigo = '"+id.getText()+"' and caj_suc = '"+id_caja1.getText()+"' ";
                    st = con.createStatement();
                    st.execute(updaresta);              
                                  
                    metodoventa.mov_entrecaja();
                    metodoventa.mov_entrecaja2();
                    }catch(SQLException ex){

                    }
                    
                           String des = "DE:   Caja:  "+id.getText()+"   Sucursal:  "+cmb_sucu1.getSelectedItem()+" ";     
                            obs_mov1.setText(des);

                            String des1 = "  A:   Caja:  "+id2.getText()+"   Sucursal:  "+cmb_sucu2.getSelectedItem()+"";
                            obs_mov2.setText(des1);
                    
                    try {       
                    String sqlinsert = "INSERT INTO movimiento_caja (mov_fecha, mov_sucremit, mov_sucbenef, mov_cajaremit,"
                    + "mov_cajabenef, mov_montoenvia, mov_obsremit, mov_obsbenefi) "
                    + "values ('"+Principal.fecha_ini.getText()+"','"+id_caja1.getText()+"','"+id_caja2.getText()+"','"+id.getText()+"',"
                    + "'"+id2.getText()+"','"+monto_ingresado.getText()+"','"+obs_mov1.getText()+"','"+obs_mov2.getText()+"')";	

                    st = con.createStatement();			
                    st.execute(sqlinsert); 

                   } catch (SQLException ex) {
                      System.out.println("ver error " + ex.getMessage());

                   }
                    
                    
                    monto_ingresado.setText("");
                    JOptionPane.showMessageDialog(null, "Movimiento realizado con exito");
                
                }else{
                    JOptionPane.showMessageDialog(null, "No puede enviar un monto mayor al que existe en la caja");
                }

                
            
                
            }
        }
        
        

       
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mov_caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mov_caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mov_caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mov_caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mov_caja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> cmb_sucu1;
    public static javax.swing.JComboBox<String> cmb_sucu2;
    private javax.swing.JTextField descri;
    private javax.swing.JTextField descri2;
    private javax.swing.JTextField id;
    private javax.swing.JTextField id2;
    public static javax.swing.JTextField id_caja1;
    public static javax.swing.JTextField id_caja2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtable_caja1;
    private javax.swing.JTable jtable_caja2;
    private javax.swing.JTextField monto;
    private javax.swing.JTextField monto2;
    private javax.swing.JTextField monto_ingresado;
    private javax.swing.JLabel obs_mov1;
    private javax.swing.JLabel obs_mov2;
    // End of variables declaration//GEN-END:variables
}
