/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbstock;


import static dbstock.pedido_entregado.jTable_pedidoentregado;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Derlis
 */
public class pedido_entregado extends javax.swing.JFrame {

    /**
     * Creates new form pedido_entregado
     */
    DateFormat df = DateFormat.getDateInstance();
    public static Statement st;
    public static Connection con; 
   
    public pedido_entregado() throws ParseException {
        initComponents();
        
        this.setLocationRelativeTo(null);//centra el formulario
        this.setTitle("Pedidos Entregados");
         
        met_pedrealizados.JTABLE_TAMANHO_pedido3();
        
        Calendar Cal= Calendar.getInstance();
        fecha_final.setCalendar(Cal);
        fecha_inicial.setCalendar(Cal);
  
        
        	String[] titulo={"id Ped.","Proveedor","Fecha","Monto","Condición","Estado","Sucursal"};
		DefaultTableModel mod=new DefaultTableModel(null,titulo);
		
			pedido_entregado.jTable_pedidoentregado.setModel(mod);
	
		//forma de quetenga la barra orizontal////////////
		pedido_entregado.jTable_pedidoentregado.setAutoResizeMode(pedido_entregado.jTable_pedidoentregado.AUTO_RESIZE_OFF);
		pedido_entregado.jTable_pedidoentregado.doLayout();
                
		    TableColumnModel columnModel = pedido_entregado.jTable_pedidoentregado.getColumnModel();

                    columnModel.getColumn(0).setPreferredWidth(70);
                    columnModel.getColumn(1).setPreferredWidth(250);
                    columnModel.getColumn(2).setPreferredWidth(100);
                    columnModel.getColumn(3).setPreferredWidth(100);
        
        
                 

            String[] titulo1={"id Ped","id prov.","Descripción","Cantidad","Precio"};
            DefaultTableModel mod1=new DefaultTableModel(null,titulo1);


            jTable_peddetalles.setModel(mod1);

            TableColumnModel columnModel1 = jTable_peddetalles.getColumnModel();

            columnModel1.getColumn(0).setPreferredWidth(50);
            columnModel1.getColumn(1).setPreferredWidth(50);
            columnModel1.getColumn(2).setPreferredWidth(250);
            columnModel1.getColumn(3).setPreferredWidth(70);
            columnModel1.getColumn(4).setPreferredWidth(150);
        
            
            
            id_ped.setVisible(false);
            id_detalle.setVisible(false);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_pedidoentregado = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_peddetalles = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        fecha_inicial = new com.toedter.calendar.JDateChooser();
        fecha_final = new com.toedter.calendar.JDateChooser();
        fecha_fin = new javax.swing.JTextField();
        fecha_ini = new javax.swing.JTextField();
        btn_calcular = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_usuexit1 = new javax.swing.JButton();
        cantidad2 = new javax.swing.JLabel();
        id_ped = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cant_detalle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cant_id = new javax.swing.JTextField();
        monto_id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        id_detalle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_pedidoentregado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id Pedido", "Proveedor", "Fecha", "Monto"
            }
        ));
        jTable_pedidoentregado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_pedidoentregadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_pedidoentregado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 760, 180));

        jTable_peddetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Título 1", "Título 2", "Título 3", "Título 4"
            }
        ));
        jTable_peddetalles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_peddetallesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_peddetalles);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 630, 190));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Hasta:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 50, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Detalles");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 80, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Desde:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 50, 20));

        fecha_inicial.setDateFormatString("dd/MM/yyyy");
        getContentPane().add(fecha_inicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, -1));

        fecha_final.setDateFormatString("dd/MM/yyyy");
        getContentPane().add(fecha_final, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 130, -1));
        getContentPane().add(fecha_fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 100, -1));
        getContentPane().add(fecha_ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 100, -1));

        btn_calcular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_calcular.setText("Calcular");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });
        getContentPane().add(btn_calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 100, 50));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Buscar Fecha");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Pedidos");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, 20));

        btn_usuexit1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_usuexit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/exit.png"))); // NOI18N
        btn_usuexit1.setText("Salir");
        btn_usuexit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuexit1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usuexit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, 140, 40));

        cantidad2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cantidad2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cantidad2.setText("cant");
        getContentPane().add(cantidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 50, 20));
        getContentPane().add(id_ped, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 70, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Cant.Pedido:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 80, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Cantidad Entregado");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 140, 20));

        cant_detalle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cant_detalle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cant_detalle.setText("cant");
        getContentPane().add(cant_detalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 60, 20));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PEDIDOS ENTREGADOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 310, 40));

        cant_id.setBackground(new java.awt.Color(0, 204, 51));
        cant_id.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cant_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cant_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cant_idActionPerformed(evt);
            }
        });
        getContentPane().add(cant_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 50, 40));

        monto_id.setBackground(new java.awt.Color(0, 204, 51));
        monto_id.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        monto_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        monto_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monto_idActionPerformed(evt);
            }
        });
        getContentPane().add(monto_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, 140, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/agregarvta.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, -1, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Cant.Detalle:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 80, 20));

        id_detalle.setText("id");
        getContentPane().add(id_detalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 30, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/fon.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_usuexit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuexit1ActionPerformed
        dispose();
    }//GEN-LAST:event_btn_usuexit1ActionPerformed

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed

        String fechaObtenida = df.format(fecha_inicial.getDate());
        fecha_ini.setText(fechaObtenida);

        String fechafinal = df.format(fecha_final.getDate());
        fecha_fin.setText(fechafinal);

        met_pedrealizados.CARGAR_JTABLE_pedido2();

        Conexion cc=new Conexion();
        Connection con=cc.conectar();
        String sql="select count(*) from pedido where ped_fecha>='"+fecha_ini.getText()+"' and ped_fecha>='"+fecha_fin.getText()+"'";
        try {
            st = con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            if(rs.next())
            {
                cantidad2.setText(rs.getString("count"));
            }

        } catch (SQLException ex) {
            //Logger.getLogger(Factura1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void jTable_pedidoentregadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_pedidoentregadoMouseClicked



        ////////////////////////////////////////

        int n1 = jTable_pedidoentregado.getSelectedRow();
        String id1 = jTable_pedidoentregado.getValueAt(n1, 0).toString();
        id_ped.setText(id1);

        Conexion cc=new Conexion();    
        Connection con=cc.conectar();
         boolean falsebo= false;
        try {

            String[] titulo={"id Ped","id prov.","Descripción","Cantidad","Precio"};
            DefaultTableModel mod=new DefaultTableModel(null,titulo);

            Object[] reg=new Object[7];
            String sql = "Select * from detallespedido where '"+id_ped.getText()+"' = pedido_id and pedido_bolean =  '"+falsebo+"' ";

            st = con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while (rs.next()) {

                reg[0]=rs.getString("pedido_id");
                reg[1]=rs.getString("pedido_cod_prod");
                reg[2]=rs.getString("pedido_desc");
                reg[3]=rs.getString("pedido_cant");
                reg[4]=rs.getString("pedido_preciocompra");


                mod.addRow(reg);

            }
            jTable_peddetalles.setModel(mod);

            TableColumnModel columnModel = jTable_peddetalles.getColumnModel();

            columnModel.getColumn(0).setPreferredWidth(50);
            columnModel.getColumn(1).setPreferredWidth(50);
            columnModel.getColumn(2).setPreferredWidth(250);
            columnModel.getColumn(3).setPreferredWidth(70);
            columnModel.getColumn(4).setPreferredWidth(150);


            rs.close();
            st.close();
            con.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jTable_pedidoentregadoMouseClicked

    private void cant_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cant_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cant_idActionPerformed

    private void jTable_peddetallesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_peddetallesMouseClicked
        int n0 = jTable_peddetalles.getSelectedRow();
        String id = jTable_peddetalles.getValueAt(n0, 3).toString();
        cant_id.setText(id);
        
        int n1 = jTable_peddetalles.getSelectedRow();
        String id1 = jTable_peddetalles.getValueAt(n1, 4).toString();
        monto_id.setText(id1);
        
        int n2 = jTable_peddetalles.getSelectedRow();
        String id2 = jTable_peddetalles.getValueAt(n2, 1).toString();
        id_detalle.setText(id2);
        
        
        
        
    }//GEN-LAST:event_jTable_peddetallesMouseClicked

    private void monto_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monto_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monto_idActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int aux  =  JOptionPane.showConfirmDialog(null, "Desea Confirmar Pedido ","Sistema", JOptionPane.YES_NO_OPTION);

        if(aux == JOptionPane.YES_OPTION){
            
            Conexion cc=new Conexion();
            Connection con=cc.conectar();
            String condicion = "ENTREGADO";
            boolean nro= true;
            try {

                String sql = "UPDATE detallespedido SET pedido_entregado = '"+cant_id.getText()+"', pedido_bolean = '"+nro+"' where pedido_cod_prod = '"+id_detalle.getText()+"'";
                st = con.createStatement();
                st.execute(sql);
                
            } catch (Exception e) {
            }
            
            try {

                String sql1 = "UPDATE pedido SET ped_estado = '"+condicion+"' where ped_num_lg = '"+id_ped.getText()+"'";
                st = con.createStatement();
                st.execute(sql1);
                
            } catch (Exception e) {
            }
            
            try {
                String sql1 = "UPDATE productos SET pro_stock=pro_stock + '"+cant_id.getText()+"' where pro_id = '"+id_detalle.getText()+"'";
                st = con.createStatement();
                st.execute(sql1);
                
            } catch (Exception e) {
            }
            
            
        }else{if(aux == JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(null,  "Cancelado", "Sistema", JOptionPane.INFORMATION_MESSAGE);

        }
        }
            Conexion cc=new Conexion();
            Connection con=cc.conectar();
            boolean falsebo= false;
         try {

            String[] titulo={"id Ped","id prov.","Descripción","Cantidad","Precio"};
            DefaultTableModel mod=new DefaultTableModel(null,titulo);

            Object[] reg=new Object[7];
            String sql = "Select * from detallespedido where '"+id_ped.getText()+"' = pedido_id and pedido_bolean =  '"+falsebo+"' ";

            st = con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while (rs.next()) {

                reg[0]=rs.getString("pedido_id");
                reg[1]=rs.getString("pedido_cod_prod");
                reg[2]=rs.getString("pedido_desc");
                reg[3]=rs.getString("pedido_cant");
                reg[4]=rs.getString("pedido_preciocompra");


                mod.addRow(reg);

            }
            jTable_peddetalles.setModel(mod);

            TableColumnModel columnModel = jTable_peddetalles.getColumnModel();

            columnModel.getColumn(0).setPreferredWidth(50);
            columnModel.getColumn(1).setPreferredWidth(50);
            columnModel.getColumn(2).setPreferredWidth(250);
            columnModel.getColumn(3).setPreferredWidth(70);
            columnModel.getColumn(4).setPreferredWidth(150);


            rs.close();
            st.close();
            con.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pedido_entregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pedido_entregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pedido_entregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pedido_entregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new pedido_entregado().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(pedido_entregado.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular;
    private javax.swing.JButton btn_usuexit1;
    private javax.swing.JLabel cant_detalle;
    private javax.swing.JTextField cant_id;
    private javax.swing.JLabel cantidad2;
    public static javax.swing.JTextField fecha_fin;
    public static com.toedter.calendar.JDateChooser fecha_final;
    public static javax.swing.JTextField fecha_ini;
    public static com.toedter.calendar.JDateChooser fecha_inicial;
    private javax.swing.JLabel id_detalle;
    private javax.swing.JTextField id_ped;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_peddetalles;
    public static javax.swing.JTable jTable_pedidoentregado;
    private javax.swing.JTextField monto_id;
    // End of variables declaration//GEN-END:variables
}
