/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbstock;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Derlis
 */
public class privilegio extends javax.swing.JFrame {

    Statement st;
    Connection con;
    /**
     * Creates new form privilegio
     */
    public privilegio() {
        initComponents();
        
        this.setLocationRelativeTo(null);//centra el formulario
        this.setTitle("Privilegios");
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE); //inabilida el uso del boton exit X
        this.setResizable(false); //Disable the Resize Button
        
        metodos.CARGAR_JTABLE_PRIVILEGIOS();
        
           base_datos.setEnabled(false);
           adm_usuarios.setEnabled(false);
           pri_usuarios.setEnabled(false);
           apariencia.setEnabled(false);
           configuracion.setEnabled(false);
           sucursal.setEnabled(false);
            proveedores.setEnabled(false);
            productos.setEnabled(false);
            add_stock.setEnabled(false);
            add_caja.setEnabled(false);
            add_cliente.setEnabled(false);
            grupo_pro.setEnabled(false);
            cotizaciones.setEnabled(false);
            compras.setEnabled(false);
            ped_realizados.setEnabled(false);
            confirmar_entrega.setEnabled(false);
            vta_1.setEnabled(false);
            presupuesto.setEnabled(false);
            cons_ventas.setEnabled(false);
            consu_presu.setEnabled(false);
            consu_cliente.setEnabled(false);
            consu_vendedor.setEnabled(false);
            saldo_caja.setEnabled(false);
            mov_caja.setEnabled(false);
            cobranza.setEnabled(false);
            gastos.setEnabled(false);
            ingresos.setEnabled(false);
            saldo_caja.setEnabled(false);
            mov_caja.setEnabled(false);
            cobranza.setEnabled(false);
            gastos.setEnabled(false);
            ingresos.setEnabled(false);
            listado.setEnabled(false);
            cierrecaja.setEnabled(false);
           
           
           pri_id.setEnabled(false);
           pri_des.setEnabled(false);
           pri_obs.setEnabled(false);
           
           btn_guardar.setEnabled(false);
           btn_editar.setEnabled(false);
           btn_eliminar.setEnabled(false);
           btn_cancelar.setEnabled(false);
           
           
        ///////////////////////////////////label
        base_datos_lb.setVisible(false);
        adm_privilegios.setVisible(false);
        privi_usuari.setVisible(false);
        apariencia_1.setVisible(false);
        config_1.setVisible(false);
        sucu_1.setVisible(false);
        vta_lb.setVisible(false);
        presupu.setVisible(false);
        proveedores_1.setVisible(false);
        producto_1.setVisible(false);
        add_stock_1.setVisible(false);
        add_caja_1.setVisible(false);
        add_cliente_1.setVisible(false);
        grupo_pro_1.setVisible(false);
        cotiza.setVisible(false);
        cons_vta.setVisible(false);
        cons_presu.setVisible(false);
        cons_clie.setVisible(false);
        cons_vende.setVisible(false);
        compras_1.setVisible(false);
        ped_realiz.setVisible(false);
        confirmar_entre.setVisible(false);
        saldo_cja.setVisible(false);
        movimi.setVisible(false);
        cobz.setVisible(false);
        gtos.setVisible(false);
        ingres.setVisible(false);
        listad.setVisible(false);  
        label_cierrecaja.setVisible(false);  
        ///////////////////////////////////////////////////////////////
          
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable_pri = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        pri_obs = new javax.swing.JTextField();
        pri_id = new javax.swing.JTextField();
        base_datos = new javax.swing.JCheckBox();
        adm_usuarios = new javax.swing.JCheckBox();
        pri_usuarios = new javax.swing.JCheckBox();
        apariencia = new javax.swing.JCheckBox();
        configuracion = new javax.swing.JCheckBox();
        sucursal = new javax.swing.JCheckBox();
        add_stock = new javax.swing.JCheckBox();
        add_caja = new javax.swing.JCheckBox();
        productos = new javax.swing.JCheckBox();
        compras = new javax.swing.JCheckBox();
        listado = new javax.swing.JCheckBox();
        add_cliente = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        pri_des = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        grupo_pro = new javax.swing.JCheckBox();
        cotizaciones = new javax.swing.JCheckBox();
        ped_realizados = new javax.swing.JCheckBox();
        confirmar_entrega = new javax.swing.JCheckBox();
        vta_1 = new javax.swing.JCheckBox();
        presupuesto = new javax.swing.JCheckBox();
        informe = new javax.swing.JCheckBox();
        sistema = new javax.swing.JCheckBox();
        registros = new javax.swing.JCheckBox();
        cpa = new javax.swing.JCheckBox();
        ventas = new javax.swing.JCheckBox();
        consultas = new javax.swing.JCheckBox();
        caja = new javax.swing.JCheckBox();
        proveedores = new javax.swing.JCheckBox();
        ingresos = new javax.swing.JCheckBox();
        consu_presu = new javax.swing.JCheckBox();
        consu_cliente = new javax.swing.JCheckBox();
        cons_ventas = new javax.swing.JCheckBox();
        saldo_caja = new javax.swing.JCheckBox();
        mov_caja = new javax.swing.JCheckBox();
        cobranza = new javax.swing.JCheckBox();
        gastos = new javax.swing.JCheckBox();
        consu_vendedor = new javax.swing.JCheckBox();
        base_datos_lb = new javax.swing.JLabel();
        adm_privilegios = new javax.swing.JLabel();
        privi_usuari = new javax.swing.JLabel();
        apariencia_1 = new javax.swing.JLabel();
        config_1 = new javax.swing.JLabel();
        sucu_1 = new javax.swing.JLabel();
        producto_1 = new javax.swing.JLabel();
        add_stock_1 = new javax.swing.JLabel();
        add_caja_1 = new javax.swing.JLabel();
        add_cliente_1 = new javax.swing.JLabel();
        grupo_pro_1 = new javax.swing.JLabel();
        cotiza = new javax.swing.JLabel();
        compras_1 = new javax.swing.JLabel();
        ped_realiz = new javax.swing.JLabel();
        confirmar_entre = new javax.swing.JLabel();
        vta_lb = new javax.swing.JLabel();
        presupu = new javax.swing.JLabel();
        cons_vta = new javax.swing.JLabel();
        cons_presu = new javax.swing.JLabel();
        cons_clie = new javax.swing.JLabel();
        cons_vende = new javax.swing.JLabel();
        saldo_cja = new javax.swing.JLabel();
        movimi = new javax.swing.JLabel();
        cobz = new javax.swing.JLabel();
        gtos = new javax.swing.JLabel();
        ingres = new javax.swing.JLabel();
        listad = new javax.swing.JLabel();
        btn_editar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_nuevo = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        proveedores_1 = new javax.swing.JLabel();
        cierrecaja = new javax.swing.JCheckBox();
        label_cierrecaja = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(890, 510));
        setPreferredSize(new java.awt.Dimension(890, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PRIVILEGIOS DEL SISTEMA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jtable_pri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable_pri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_priMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtable_pri);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 400, 210));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Descripción:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        pri_obs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pri_obsKeyTyped(evt);
            }
        });
        getContentPane().add(pri_obs, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 360, -1));
        getContentPane().add(pri_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 50, -1));

        base_datos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        base_datos.setText("Base de Datos");
        base_datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                base_datosActionPerformed(evt);
            }
        });
        getContentPane().add(base_datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        adm_usuarios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        adm_usuarios.setText("Adm. de Usuarios");
        adm_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adm_usuariosActionPerformed(evt);
            }
        });
        getContentPane().add(adm_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        pri_usuarios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pri_usuarios.setText("Privilegios de Usuarios");
        pri_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pri_usuariosActionPerformed(evt);
            }
        });
        getContentPane().add(pri_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        apariencia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        apariencia.setText("Apariencia");
        apariencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aparienciaActionPerformed(evt);
            }
        });
        getContentPane().add(apariencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        configuracion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        configuracion.setText("Configuración");
        configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configuracionActionPerformed(evt);
            }
        });
        getContentPane().add(configuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        sucursal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sucursal.setText("Sucursal");
        sucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucursalActionPerformed(evt);
            }
        });
        getContentPane().add(sucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        add_stock.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add_stock.setText("Agregar Stock");
        add_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_stockActionPerformed(evt);
            }
        });
        getContentPane().add(add_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, -1, -1));

        add_caja.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add_caja.setText("Agregar Caja");
        add_caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_cajaActionPerformed(evt);
            }
        });
        getContentPane().add(add_caja, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, -1, 20));

        productos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        productos.setText("Productos");
        productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productosActionPerformed(evt);
            }
        });
        getContentPane().add(productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, -1));

        compras.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        compras.setText("Compras");
        compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprasActionPerformed(evt);
            }
        });
        getContentPane().add(compras, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, -1, 20));

        listado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        listado.setText("Listados");
        listado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadoActionPerformed(evt);
            }
        });
        getContentPane().add(listado, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, -1, -1));

        add_cliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add_cliente.setText("Agregar Cliente");
        add_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_clienteActionPerformed(evt);
            }
        });
        getContentPane().add(add_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Obs.:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        pri_des.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pri_desKeyTyped(evt);
            }
        });
        getContentPane().add(pri_des, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 200, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Código:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        btn_exit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/exit.png"))); // NOI18N
        btn_exit.setText("Salir");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, -1, 40));

        grupo_pro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        grupo_pro.setText("Grupo de Productos");
        grupo_pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupo_proActionPerformed(evt);
            }
        });
        getContentPane().add(grupo_pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, -1, -1));

        cotizaciones.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cotizaciones.setText("Cotizaciones");
        cotizaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cotizacionesActionPerformed(evt);
            }
        });
        getContentPane().add(cotizaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, -1, -1));

        ped_realizados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ped_realizados.setText("Pedidos Realizados");
        ped_realizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ped_realizadosActionPerformed(evt);
            }
        });
        getContentPane().add(ped_realizados, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, -1, -1));

        confirmar_entrega.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        confirmar_entrega.setText("Confirmar Entrega");
        confirmar_entrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmar_entregaActionPerformed(evt);
            }
        });
        getContentPane().add(confirmar_entrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, -1, 20));

        vta_1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        vta_1.setText("Ventas");
        vta_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vta_1ActionPerformed(evt);
            }
        });
        getContentPane().add(vta_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, 20));

        presupuesto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        presupuesto.setText("Presupuesto");
        presupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presupuestoActionPerformed(evt);
            }
        });
        getContentPane().add(presupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, 20));

        informe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        informe.setForeground(new java.awt.Color(0, 153, 0));
        informe.setText("INFORME");
        informe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informeActionPerformed(evt);
            }
        });
        getContentPane().add(informe, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, -1, -1));

        sistema.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sistema.setForeground(new java.awt.Color(0, 153, 0));
        sistema.setText("SISTEMA");
        sistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sistemaActionPerformed(evt);
            }
        });
        getContentPane().add(sistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        registros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        registros.setForeground(new java.awt.Color(0, 153, 0));
        registros.setText("REGISTROS");
        registros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrosActionPerformed(evt);
            }
        });
        getContentPane().add(registros, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, -1));

        cpa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cpa.setForeground(new java.awt.Color(0, 153, 0));
        cpa.setText("COMPRAS");
        cpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpaActionPerformed(evt);
            }
        });
        getContentPane().add(cpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, -1, -1));

        ventas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ventas.setForeground(new java.awt.Color(0, 153, 0));
        ventas.setText("VENTAS");
        ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasActionPerformed(evt);
            }
        });
        getContentPane().add(ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        consultas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        consultas.setForeground(new java.awt.Color(0, 153, 0));
        consultas.setText("CONSULTAS");
        consultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultasActionPerformed(evt);
            }
        });
        getContentPane().add(consultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));

        caja.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        caja.setForeground(new java.awt.Color(0, 153, 0));
        caja.setText("CAJA");
        caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaActionPerformed(evt);
            }
        });
        getContentPane().add(caja, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, -1, -1));

        proveedores.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        proveedores.setText("Proveedores");
        proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedoresActionPerformed(evt);
            }
        });
        getContentPane().add(proveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, -1, -1));

        ingresos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ingresos.setText("Ingresos");
        ingresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresosActionPerformed(evt);
            }
        });
        getContentPane().add(ingresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, -1, -1));

        consu_presu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        consu_presu.setText("Consultas de Presupuestos");
        consu_presu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consu_presuActionPerformed(evt);
            }
        });
        getContentPane().add(consu_presu, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, -1, -1));

        consu_cliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        consu_cliente.setText("Consultas de Clientes");
        consu_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consu_clienteActionPerformed(evt);
            }
        });
        getContentPane().add(consu_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, -1, -1));

        cons_ventas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cons_ventas.setText("Consultas de Ventas");
        cons_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cons_ventasActionPerformed(evt);
            }
        });
        getContentPane().add(cons_ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, -1));

        saldo_caja.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        saldo_caja.setText("Saldo de Caja");
        saldo_caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldo_cajaActionPerformed(evt);
            }
        });
        getContentPane().add(saldo_caja, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, -1, -1));

        mov_caja.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mov_caja.setText("Movimiento de caja");
        mov_caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mov_cajaActionPerformed(evt);
            }
        });
        getContentPane().add(mov_caja, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, -1, 30));

        cobranza.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cobranza.setText("Cobranza");
        cobranza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobranzaActionPerformed(evt);
            }
        });
        getContentPane().add(cobranza, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, -1, -1));

        gastos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gastos.setText("Gastos");
        gastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gastosActionPerformed(evt);
            }
        });
        getContentPane().add(gastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, -1, -1));

        consu_vendedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        consu_vendedor.setText("Consultas de Vendedor");
        consu_vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consu_vendedorActionPerformed(evt);
            }
        });
        getContentPane().add(consu_vendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, -1, -1));

        base_datos_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(base_datos_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 20, 20));

        adm_privilegios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(adm_privilegios, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 20, 20));

        privi_usuari.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(privi_usuari, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 20, 20));

        apariencia_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(apariencia_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 20, 20));

        config_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(config_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 20, 20));

        sucu_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(sucu_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 20, 20));

        producto_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(producto_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 20, 20));

        add_stock_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(add_stock_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 20, 20));

        add_caja_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(add_caja_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 20, 20));

        add_cliente_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(add_cliente_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 20, 20));

        grupo_pro_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(grupo_pro_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 20, 20));

        cotiza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cotiza, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 20, 20));

        compras_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(compras_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, 20, 20));

        ped_realiz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ped_realiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 20, 20));

        confirmar_entre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(confirmar_entre, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 20, 20));

        vta_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(vta_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 20, 20));

        presupu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(presupu, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 20, 20));

        cons_vta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cons_vta, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 20, 20));

        cons_presu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cons_presu, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 20, 20));

        cons_clie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cons_clie, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 20, 20));

        cons_vende.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cons_vende, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 20, 20));

        saldo_cja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(saldo_cja, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 20, 20));

        movimi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(movimi, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, 20, 20));

        cobz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cobz, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 20, 20));

        gtos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(gtos, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 20, 20));

        ingres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ingres, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 20, 20));
        getContentPane().add(listad, new org.netbeans.lib.awtextra.AbsoluteConstraints(724, 400, 20, 20));

        btn_editar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/editar.png"))); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 100, 40));

        btn_cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/close.png"))); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 120, 40));

        btn_nuevo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/add-file.png"))); // NOI18N
        btn_nuevo.setText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 100, 40));

        btn_guardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/save.png"))); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 110, 40));

        btn_eliminar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/eliminar.png"))); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 120, 40));

        btn_update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/reload.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 110, 40));

        proveedores_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(proveedores_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 20, 20));

        cierrecaja.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cierrecaja.setText("Cierre de Caja");
        cierrecaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cierrecajaActionPerformed(evt);
            }
        });
        getContentPane().add(cierrecaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, -1, -1));

        label_cierrecaja.setText("jLabel7");
        getContentPane().add(label_cierrecaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 240, -1, 20));

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Privilegios");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 430, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/fondosistema.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        dispose();

       // Principal.jMenu_usuario.setEnabled(true);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void jtable_priMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_priMouseClicked
       
        int n0 = jtable_pri.getSelectedRow();
        String id = jtable_pri.getValueAt(n0, 0).toString();
        pri_id.setText(id);
        
        int n1 = jtable_pri.getSelectedRow();
        String id1 = jtable_pri.getValueAt(n1, 1).toString();
        pri_des.setText(id1);
        
        int n2 = jtable_pri.getSelectedRow();
        String id2 = jtable_pri.getValueAt(n2, 2).toString();
        pri_obs.setText(id2);
        
        btn_editar.setEnabled(true);
        btn_eliminar.setEnabled(true);
        btn_cancelar.setEnabled(false);
         btn_guardar.setEnabled(false);
         
           pri_id.setEnabled(false);
           pri_des.setEnabled(false);
           pri_obs.setEnabled(false);
           
        
         metodos.estirardatos_privilegios();
         
        if(base_datos_lb.getText().equals("1")){
            base_datos.setSelected(true);
        }else{
            base_datos.setSelected(false);
        }
            
        
        if(adm_privilegios.getText().equals("1")){
            adm_usuarios.setSelected(true);
        }else{
            adm_usuarios.setSelected(false);
        }
        
        if(privi_usuari.getText().equals("1")){
            pri_usuarios.setSelected(true);
        }else{
            pri_usuarios.setSelected(false);
        }
        
        if(apariencia_1.getText().equals("1")){
            apariencia.setSelected(true);
        }else{
            apariencia.setSelected(false);
        }
        
        if(config_1.getText().equals("1")){
            configuracion.setSelected(true);
        }else{
            configuracion.setSelected(false);
        }
        
        if(sucu_1.getText().equals("1")){
            sucursal.setSelected(true);
        }else{
            sucursal.setSelected(false);
        }
        
        if(proveedores_1.getText().equals("1")){
            proveedores.setSelected(true);
        }else{
            proveedores.setSelected(false);
        }
        
        if(producto_1.getText().equals("1")){
            productos.setSelected(true);
        }else{
            productos.setSelected(false);
        }
        
        if(add_stock_1.getText().equals("1")){
            add_stock.setSelected(true);
        }else{
            add_stock.setSelected(false);
        }

        if(add_caja_1.getText().equals("1")){
            add_caja.setSelected(true);
        }else{
            add_caja.setSelected(false);
        }
        
        if(add_cliente_1.getText().equals("1")){
            add_cliente.setSelected(true);
        }else{
            add_cliente.setSelected(false);
        }
        
        if(grupo_pro_1.getText().equals("1")){
            grupo_pro.setSelected(true);
        }else{
            grupo_pro.setSelected(false);
        }
        
        if(cotiza.getText().equals("1")){
            cotizaciones.setSelected(true);
        }else{
            cotizaciones.setSelected(false);
        }
             
        if(compras_1.getText().equals("1")){
            compras.setSelected(true);
        }else{
            compras.setSelected(false);
        }
        
        if(ped_realiz.getText().equals("1")){
            ped_realizados.setSelected(true);
        }else{
            ped_realizados.setSelected(false);
        }
        
        if(confirmar_entre.getText().equals("1")){
            confirmar_entrega.setSelected(true);
        }else{
            confirmar_entrega.setSelected(false);
        }
        
        if(vta_lb.getText().equals("1")){
            vta_1.setSelected(true);
        }else{
            vta_1.setSelected(false);
        }
        
        if(presupu.getText().equals("1")){
            presupuesto.setSelected(true);
        }else{
            presupuesto.setSelected(false);
        }
        
        if(cons_vta.getText().equals("1")){
            cons_ventas.setSelected(true);
        }else{
            cons_ventas.setSelected(false);
        }
        
        if(cons_presu.getText().equals("1")){
            consu_presu.setSelected(true);
        }else{
            consu_presu.setSelected(false);
        }
        
        if(cons_clie.getText().equals("1")){
            consu_cliente.setSelected(true);
        }else{
            consu_cliente.setSelected(false);
        }
        
        if(cons_vende.getText().equals("1")){
            consu_vendedor.setSelected(true);
        }else{
            consu_vendedor.setSelected(false);
        }
        
        if(saldo_cja.getText().equals("1")){
            saldo_caja.setSelected(true);
        }else{
            saldo_caja.setSelected(false);
        }
        
        if(movimi.getText().equals("1")){
            mov_caja.setSelected(true);
        }else{
            mov_caja.setSelected(false);
        }
        
        if(cobz.getText().equals("1")){
            cobranza.setSelected(true);
        }else{
            cobranza.setSelected(false);
        }
        
        if(gtos.getText().equals("1")){
            gastos.setSelected(true);
        }else{
            gastos.setSelected(false);
        }
        
        if(ingres.getText().equals("1")){
            ingresos.setSelected(true);
        }else{
            ingresos.setSelected(false);
        }
           
        if(listad.getText().equals("1")){
            listado.setSelected(true);
        }else{
            listado.setSelected(false);
        }
        
        if(label_cierrecaja.getText().equals("1")){
            cierrecaja.setSelected(true);
        }else{
            cierrecaja.setSelected(false);
        }
        
        
        
        
        
    }//GEN-LAST:event_jtable_priMouseClicked

    private void informeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informeActionPerformed
        if(informe.isSelected()){     
            listado.setEnabled(true);

       }else{
            listado.setEnabled(false);

       }
    }//GEN-LAST:event_informeActionPerformed

    private void registrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrosActionPerformed
        if(registros.isSelected()){
           
            proveedores.setEnabled(true);
            productos.setEnabled(true);
            add_stock.setEnabled(true);
            add_caja.setEnabled(true);
            add_cliente.setEnabled(true);
            grupo_pro.setEnabled(true);
            cotizaciones.setEnabled(true);
           
          
       }else{
            proveedores.setEnabled(false);
            productos.setEnabled(false);
            add_stock.setEnabled(false);
            add_caja.setEnabled(false);
            add_cliente.setEnabled(false);
            grupo_pro.setEnabled(false);
           cotizaciones.setEnabled(false);
       }
    }//GEN-LAST:event_registrosActionPerformed

    private void cpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpaActionPerformed
        if(cpa.isSelected()){
           
            compras.setEnabled(true);
            ped_realizados.setEnabled(true);
            confirmar_entrega.setEnabled(true);

       }else{
            compras.setEnabled(false);
            ped_realizados.setEnabled(false);
            confirmar_entrega.setEnabled(false);

       }
    }//GEN-LAST:event_cpaActionPerformed

    private void ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasActionPerformed
        if(ventas.isSelected()){
            vta_1.setEnabled(true);
            presupuesto.setEnabled(true);

       }else{
            vta_1.setEnabled(false);
            presupuesto.setEnabled(false);
       }
    }//GEN-LAST:event_ventasActionPerformed

    private void consultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultasActionPerformed
        if(consultas.isSelected()){
            cons_ventas.setEnabled(true);
            consu_presu.setEnabled(true);
            consu_cliente.setEnabled(true);
            consu_vendedor.setEnabled(true);
       }else{
             cons_ventas.setEnabled(false);
            consu_presu.setEnabled(false);
            consu_cliente.setEnabled(false);
            consu_vendedor.setEnabled(false);
       }
    }//GEN-LAST:event_consultasActionPerformed

    private void cajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaActionPerformed
       
        if(caja.isSelected()){     
            saldo_caja.setEnabled(true);
            mov_caja.setEnabled(true);
            cobranza.setEnabled(true);
            gastos.setEnabled(true);
            ingresos.setEnabled(true);

       }else{
            saldo_caja.setEnabled(false);
            mov_caja.setEnabled(false);
            cobranza.setEnabled(false);
            gastos.setEnabled(false);
            ingresos.setEnabled(false);

       }
        
    }//GEN-LAST:event_cajaActionPerformed

    private void listadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadoActionPerformed
        
       if(listado.isSelected()){
           listad.setText("1");
       }else{
           listad.setText("0");
       }
        
    }//GEN-LAST:event_listadoActionPerformed

    private void ingresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresosActionPerformed
        
       if(ingresos.isSelected()){
           ingres.setText("1");
       }else{
           ingres.setText("0");
       }
        
    }//GEN-LAST:event_ingresosActionPerformed

    private void consu_presuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consu_presuActionPerformed
        
       if(consu_presu.isSelected()){
           cons_presu.setText("1");
       }else{
           cons_presu.setText("0");
       }
        
    }//GEN-LAST:event_consu_presuActionPerformed

    private void consu_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consu_clienteActionPerformed
      
       if(consu_cliente.isSelected()){
           cons_clie.setText("1");
       }else{
           cons_clie.setText("0");
       }
        
    }//GEN-LAST:event_consu_clienteActionPerformed

    private void cons_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cons_ventasActionPerformed

       if(cons_ventas.isSelected()){
           cons_vta.setText("1");
       }else{
           cons_vta.setText("0");
       }
        
    }//GEN-LAST:event_cons_ventasActionPerformed

    private void saldo_cajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldo_cajaActionPerformed
       if(saldo_caja.isSelected()){
           saldo_cja.setText("1");
       }else{
           saldo_cja.setText("0");
       }
        
    }//GEN-LAST:event_saldo_cajaActionPerformed

    private void mov_cajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mov_cajaActionPerformed
       if(mov_caja.isSelected()){
           movimi.setText("1");
       }else{
           movimi.setText("0");
       }
        
    }//GEN-LAST:event_mov_cajaActionPerformed

    private void cobranzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobranzaActionPerformed
       if(cobranza.isSelected()){
           cobz.setText("1");
       }else{
           cobz.setText("0");
       }
        
    }//GEN-LAST:event_cobranzaActionPerformed

    private void gastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gastosActionPerformed
       if(gastos.isSelected()){
           gtos.setText("1");
       }else{
           gtos.setText("0");
       }
        
    }//GEN-LAST:event_gastosActionPerformed

    private void consu_vendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consu_vendedorActionPerformed
        
       if(consu_vendedor.isSelected()){
           cons_vende.setText("1");
       }else{
           cons_vende.setText("0");
       }
        
    }//GEN-LAST:event_consu_vendedorActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
           pri_id.setEnabled(true);
           pri_des.setEnabled(true);
           pri_obs.setEnabled(true);
           
          btn_guardar.setVisible(false);
          btn_update.setVisible(true);
          btn_nuevo.setEnabled(false);
          btn_guardar.setEnabled(false);
          btn_update.setEnabled(true);
          btn_editar.setEnabled(false);
          btn_eliminar.setEnabled(false);
          btn_cancelar.setEnabled(true);

           pri_des.requestFocus();
           
           base_datos.setEnabled(true);
           adm_usuarios.setEnabled(true);
           pri_usuarios.setEnabled(true);
           apariencia.setEnabled(true);
           configuracion.setEnabled(true);
           sucursal.setEnabled(true);
            proveedores.setEnabled(true);
            productos.setEnabled(true);
            add_stock.setEnabled(true);
            add_caja.setEnabled(true);
            add_cliente.setEnabled(true);
            grupo_pro.setEnabled(true);
            cotizaciones.setEnabled(true);
            compras.setEnabled(true);
            ped_realizados.setEnabled(true);
            confirmar_entrega.setEnabled(true);
            vta_1.setEnabled(true);
            presupuesto.setEnabled(true);
            cons_ventas.setEnabled(true);
            consu_presu.setEnabled(true);
            consu_cliente.setEnabled(true);
            consu_vendedor.setEnabled(true);
            saldo_caja.setEnabled(true);
            mov_caja.setEnabled(true);
            cobranza.setEnabled(true);
            gastos.setEnabled(true);
            ingresos.setEnabled(true);
            saldo_caja.setEnabled(true);
            mov_caja.setEnabled(true);
            cobranza.setEnabled(true);
            gastos.setEnabled(true);
            ingresos.setEnabled(true);
            listado.setEnabled(true);
            
            cierrecaja.setEnabled(true);
           
           
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
           btn_guardar.setEnabled(false);
           btn_editar.setEnabled(false);
           btn_eliminar.setEnabled(false);
           btn_cancelar.setEnabled(false);
           btn_nuevo.setEnabled(true);
           btn_update.setVisible(false);
           btn_guardar.setVisible(true);
           pri_id.setEnabled(false);
           pri_des.setEnabled(false);
           pri_obs.setEnabled(false);
           
           pri_id.setText("");
           pri_des.setText("");
           pri_obs.setText("");
           
           base_datos_lb.setText("0");
           base_datos.setSelected(false);
           
           adm_privilegios.setText("0");
           adm_usuarios.setSelected(false);
           
           privi_usuari.setText("0");
           pri_usuarios.setSelected(false);
                   
           apariencia_1.setText("0");
           apariencia.setSelected(false);
        
           config_1.setText("0");
           configuracion.setSelected(false);

           sucu_1.setText("0");
           sucursal.setSelected(false);

           proveedores_1.setText("0");
           proveedores.setSelected(false);

           producto_1.setText("0");
           productos.setSelected(false);

           add_stock_1.setText("0");
           add_stock.setSelected(false);

           add_caja_1.setText("0");
           add_caja.setSelected(false);

           add_cliente_1.setText("0");
           add_cliente.setSelected(false);
           
           grupo_pro_1.setText("0");
           grupo_pro.setSelected(false);
           
           cotiza.setText("0");
           cotizaciones.setSelected(false);
        
           compras_1.setText("0");
           compras.setSelected(false);

           ped_realiz.setText("0");
           ped_realizados.setSelected(false);

           confirmar_entre.setText("0");
           confirmar_entrega.setSelected(false); 

           vta_lb.setText("0");
           vta_1.setSelected(false);

           presupu.setText("0");
           presupuesto.setSelected(false);

           cons_vta.setText("0");
           cons_ventas.setSelected(false);

           cons_presu.setText("0");
           consu_presu.setSelected(false);

           cons_clie.setText("0");
           consu_cliente.setSelected(false);

           cons_vende.setText("0");
           consu_vendedor.setSelected(false);

           saldo_cja.setText("0");
           saldo_caja.setSelected(false);

           movimi.setText("0");
           mov_caja.setSelected(false);

           cobz.setText("0");
           cobranza.setSelected(false);

           gtos.setText("0");
           gastos.setSelected(false);
 
           ingres.setText("0");
           ingresos.setSelected(false);

           listad.setText("0");
           listado.setSelected(false);
           
           
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
           pri_id.setEnabled(true);
           pri_des.setEnabled(true);
           pri_obs.setEnabled(true);
           
           
           pri_id.setText("");
           pri_des.setText("");
           pri_obs.setText("");
           
           btn_guardar.setEnabled(true);
           btn_cancelar.setEnabled(true);
           btn_nuevo.setEnabled(false);
           btn_editar.setEnabled(false);
           btn_eliminar.setEnabled(false);
           
           base_datos_lb.setText("0");
           base_datos.setSelected(false);
           
           adm_privilegios.setText("0");
           adm_usuarios.setSelected(false);
           
           privi_usuari.setText("0");
           pri_usuarios.setSelected(false);
                   
           apariencia_1.setText("0");
           apariencia.setSelected(false);
        
           config_1.setText("0");
           configuracion.setSelected(false);

           sucu_1.setText("0");
           sucursal.setSelected(false);

           proveedores_1.setText("0");
           proveedores.setSelected(false);

           producto_1.setText("0");
           productos.setSelected(false);

           add_stock_1.setText("0");
           add_stock.setSelected(false);

           add_caja_1.setText("0");
           add_caja.setSelected(false);

           add_cliente_1.setText("0");
           add_cliente.setSelected(false);
           
           grupo_pro_1.setText("0");
           grupo_pro.setSelected(false);
           
           cotiza.setText("0");
           cotizaciones.setSelected(false);
        
           compras_1.setText("0");
           compras.setSelected(false);

           ped_realiz.setText("0");
           ped_realizados.setSelected(false);

           confirmar_entre.setText("0");
           confirmar_entrega.setSelected(false); 

           vta_lb.setText("0");
           vta_1.setSelected(false);

           presupu.setText("0");
           presupuesto.setSelected(false);

           cons_vta.setText("0");
           cons_ventas.setSelected(false);

           cons_presu.setText("0");
           consu_presu.setSelected(false);

           cons_clie.setText("0");
           consu_cliente.setSelected(false);

           cons_vende.setText("0");
           consu_vendedor.setSelected(false);

           saldo_cja.setText("0");
           saldo_caja.setSelected(false);

           movimi.setText("0");
           mov_caja.setSelected(false);

           cobz.setText("0");
           cobranza.setSelected(false);

           gtos.setText("0");
           gastos.setSelected(false);
 
           ingres.setText("0");
           ingresos.setSelected(false);

           listad.setText("0");
           listado.setSelected(false);

      
    
           
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        
        
               
        int aux  =  JOptionPane.showConfirmDialog(null, "Desea Guardar el Registro?","OBSERVACION", JOptionPane.YES_NO_OPTION);
        if(aux == JOptionPane.YES_OPTION){

            Conexion cc=new Conexion();
            Connection con=cc.conectar();
            try {

                String sql = "INSERT INTO privilegios (pri_desc, pri_obs, pri_base_datos, pri_adm_usuario, pri_usuarios, pri_apariencia,"
                + " pri_configuracion, pri_sucursal, pri_proveedores, pri_productos, pri_addstock, pri_addcaja, pri_addcliente, "
                + "pri_grupo_pro, pri_cotiza, pri_compra, pri_pedirealiz, pri_confentrega, pri_venta, pri_presupuesto, pri_consultavta,"
                + " pri_consultapresu, pri_consultacli, pri_consultavendedor, pri_saldo, pri_movimiento, pri_cobranza, pri_gasto, pri_ingreso, pri_listado) "
                + "values ('"+pri_des.getText()+"','"+pri_obs.getText()+"','"+base_datos_lb.getText()+"','"+adm_privilegios.getText()+"',"
                + "'"+privi_usuari.getText()+"','"+apariencia_1.getText()+"','"+config_1.getText()+"','"+sucu_1.getText()+"',"
                + "'"+proveedores_1.getText()+"','"+producto_1.getText()+"','"+add_stock_1.getText()+"','"+add_caja_1.getText()+"',"
                + "'"+add_cliente_1.getText()+"', '"+grupo_pro_1.getText()+"', '"+cotiza.getText()+"', '"+compras_1.getText()+"',"
                + " '"+ped_realiz.getText()+"', '"+confirmar_entre.getText()+"', '"+vta_lb.getText()+"', '"+presupu.getText()+"',"
                + " '"+cons_vta.getText()+"', '"+cons_presu.getText()+"','"+cons_clie.getText()+"','"+cons_vende.getText()+"',"
                + "'"+saldo_cja.getText()+"','"+movimi.getText()+"','"+cobz.getText()+"','"+gtos.getText()+"','"+ingres.getText()+"','"+listad.getText()+"')";

                st = con.createStatement();
                st.execute(sql);
                
                metodos.CARGAR_JTABLE_PRIVILEGIOS();
                
                btn_editar.setEnabled(true);
                btn_eliminar.setEnabled(true);


            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al Insertar Datos " + ex.getMessage());
               // System.out.println("ver error " );

            }
        }
        
       
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
             int aux  =  JOptionPane.showConfirmDialog(null, "Desea eliminar ","Sistema", JOptionPane.YES_NO_OPTION);

        if(aux == JOptionPane.YES_OPTION){

            Conexion cc=new Conexion();
            Connection con=cc.conectar();

            try {

                String sql = "delete from privilegios where pri_id = '"+pri_id.getText()+"' ";
                st = con.createStatement();

                st.execute(sql);

                metodos.CARGAR_JTABLE_PRIVILEGIOS();

                pri_des.setText("");
                pri_id.setText("");
                pri_obs.setText("");


                pri_des.setEnabled(false);
                pri_id.setEnabled(false);
                pri_obs.setEnabled(false);

                btn_guardar.setVisible(true);
                btn_nuevo.setEnabled(true);
                btn_guardar.setEnabled(false);
                btn_update.setEnabled(false);
                btn_editar.setEnabled(false);
                btn_eliminar.setEnabled(false);
                btn_cancelar.setEnabled(false);
                btn_exit.setEnabled(true);

            }catch (Exception ee) {
                ee.printStackTrace();
            }

        }else{if(aux == JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(null,  "Cancelado", "Sistema", JOptionPane.INFORMATION_MESSAGE);

        }

        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void sistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sistemaActionPerformed
       
        if(sistema.isSelected()){
            //base_datos_lb.setText("1");
           base_datos.setEnabled(true);
           adm_usuarios.setEnabled(true);
           pri_usuarios.setEnabled(true);
           apariencia.setEnabled(true);
           configuracion.setEnabled(true);
           sucursal.setEnabled(true);
           
          
       }else{
           base_datos.setEnabled(false);
           adm_usuarios.setEnabled(false);
           pri_usuarios.setEnabled(false);
           apariencia.setEnabled(false);
           configuracion.setEnabled(false);
           sucursal.setEnabled(false);
         //  base_datos_lb.setText("0");
       }
        
    }//GEN-LAST:event_sistemaActionPerformed

    private void base_datosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_base_datosActionPerformed

       
       if(base_datos.isSelected()){
           base_datos_lb.setText("1");
       }else{
           base_datos_lb.setText("0");
       }
              
    }//GEN-LAST:event_base_datosActionPerformed

    private void adm_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adm_usuariosActionPerformed
       if(adm_usuarios.isSelected()){
           adm_privilegios.setText("1");
       }else{
           adm_privilegios.setText("0");
       }
    }//GEN-LAST:event_adm_usuariosActionPerformed

    private void pri_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pri_usuariosActionPerformed
       if(pri_usuarios.isSelected()){
           privi_usuari.setText("1");
       }else{
           privi_usuari.setText("0");
       }
    }//GEN-LAST:event_pri_usuariosActionPerformed

    private void aparienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aparienciaActionPerformed
       if(apariencia.isSelected()){
           apariencia_1.setText("1");
       }else{
           apariencia_1.setText("0");
       }
    }//GEN-LAST:event_aparienciaActionPerformed

    private void configuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configuracionActionPerformed
       if(configuracion.isSelected()){
           config_1.setText("1");
       }else{
           config_1.setText("0");
       }
    }//GEN-LAST:event_configuracionActionPerformed

    private void sucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucursalActionPerformed
       if(sucursal.isSelected()){
           sucu_1.setText("1");
       }else{
           sucu_1.setText("0");
       }
    }//GEN-LAST:event_sucursalActionPerformed

    private void proveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedoresActionPerformed
       if(proveedores.isSelected()){
           proveedores_1.setText("1");
       }else{
           proveedores_1.setText("0");
       }
    }//GEN-LAST:event_proveedoresActionPerformed

    private void productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosActionPerformed
       if(productos.isSelected()){
           producto_1.setText("1");
       }else{
           producto_1.setText("0");
       }
    }//GEN-LAST:event_productosActionPerformed

    private void add_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_stockActionPerformed
        
       if(add_stock.isSelected()){
           add_stock_1.setText("1");
       }else{
           add_stock_1.setText("0");
       }
        
    }//GEN-LAST:event_add_stockActionPerformed

    private void add_cajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_cajaActionPerformed
        
       if(add_caja.isSelected()){
           add_caja_1.setText("1");
       }else{
           add_caja_1.setText("0");
       }
        
    }//GEN-LAST:event_add_cajaActionPerformed

    private void add_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_clienteActionPerformed
       
        
       if(add_cliente.isSelected()){
           add_cliente_1.setText("1");
       }else{
           add_cliente_1.setText("0");
       }
        
    }//GEN-LAST:event_add_clienteActionPerformed

    private void grupo_proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupo_proActionPerformed
        
       if(grupo_pro.isSelected()){
           grupo_pro_1.setText("1");
       }else{
           grupo_pro_1.setText("0");
       }
        
    }//GEN-LAST:event_grupo_proActionPerformed

    private void cotizacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cotizacionesActionPerformed
        
       if(cotizaciones.isSelected()){
           cotiza.setText("1");
       }else{
           cotiza.setText("0");
       }
        
    }//GEN-LAST:event_cotizacionesActionPerformed

    private void comprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprasActionPerformed
       if(compras.isSelected()){
           compras_1.setText("1");
       }else{
           compras_1.setText("0");
       }
        
    }//GEN-LAST:event_comprasActionPerformed

    private void ped_realizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ped_realizadosActionPerformed
        
       if(ped_realizados.isSelected()){
           ped_realiz.setText("1");
       }else{
           ped_realiz.setText("0");
       }
        
    }//GEN-LAST:event_ped_realizadosActionPerformed

    private void confirmar_entregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmar_entregaActionPerformed
       
       if(confirmar_entrega.isSelected()){
           confirmar_entre.setText("1");
       }else{
           confirmar_entre.setText("0");
       }
        
    }//GEN-LAST:event_confirmar_entregaActionPerformed

    private void vta_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vta_1ActionPerformed
        
       if(vta_1.isSelected()){
           vta_lb.setText("1");
       }else{
           vta_lb.setText("0");
       }
        
    }//GEN-LAST:event_vta_1ActionPerformed

    private void presupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presupuestoActionPerformed
      
       if(presupuesto.isSelected()){
           presupu.setText("1");
       }else{
           presupu.setText("0");
       }
        
    }//GEN-LAST:event_presupuestoActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        
        int aux  =  JOptionPane.showConfirmDialog(null, "Desea Actualizar los Datos","OBSERVACION", JOptionPane.YES_NO_OPTION);
        if(aux == JOptionPane.YES_OPTION){
        
	Conexion cc=new Conexion();
	Connection con=cc.conectar();
                
        try {
        
        String sql = "UPDATE privilegios SET pri_desc = '"+pri_des.getText()+"', pri_obs = '"+pri_obs.getText()+"' , pri_base_datos = '"+base_datos_lb.getText()+"',"
        + " pri_adm_usuario = '"+adm_privilegios.getText()+"', pri_usuarios= '"+privi_usuari.getText()+"',pri_apariencia= '"+apariencia_1.getText()+"'"
        + ",pri_configuracion = '"+config_1.getText()+"', pri_sucursal ='"+sucu_1.getText()+"', pri_proveedores ='"+proveedores_1.getText()+"', "
        + "pri_productos ='"+producto_1.getText()+"', pri_addstock ='"+add_stock_1.getText()+"', pri_addcaja ='"+add_caja_1.getText()+"',"
        + " pri_addcliente ='"+add_cliente_1.getText()+"',pri_grupo_pro ='"+grupo_pro_1.getText()+"', pri_cotiza ='"+cotiza.getText()+"', pri_compra ='"+compras_1.getText()+"',"
        + " pri_pedirealiz ='"+ped_realiz.getText()+"', pri_confentrega ='"+confirmar_entre.getText()+"', pri_venta ='"+vta_lb.getText()+"', pri_presupuesto ='"+presupu.getText()+"'"
        + ",pri_consultavta ='"+cons_vta.getText()+"', pri_consultapresu ='"+cons_presu.getText()+"', pri_consultacli ='"+cons_clie.getText()+"', pri_consultavendedor ='"+cons_vende.getText()+"'"
        + ",pri_saldo ='"+saldo_cja.getText()+"', pri_movimiento ='"+movimi.getText()+"', pri_cobranza ='"+cobz.getText()+"',"
        + " pri_gasto ='"+gtos.getText()+"', pri_ingreso ='"+ingres.getText()+"', pri_listado ='"+listad.getText()+"', pri_cierrecaja ='"+label_cierrecaja.getText()+"' where pri_id   = '"+pri_id.getText()+"'";	
						
        st = con.createStatement();
				
        st.execute(sql);
       
        JOptionPane.showMessageDialog(null,  "Registro Actualizado", "Privilegios", JOptionPane.INFORMATION_MESSAGE);
        

        
        metodos.CARGAR_JTABLE_PRIVILEGIOS();
           
        btn_guardar.setVisible(true);
        btn_update.setVisible(false);
   
          btn_nuevo.setEnabled(true);
          btn_guardar.setEnabled(false);
          btn_update.setEnabled(false);
          btn_editar.setEnabled(false);
          btn_eliminar.setEnabled(false);
          btn_cancelar.setEnabled(false);
          btn_exit.setEnabled(true);
        
          
       pri_id.setEnabled(false);
        pri_des.setEnabled(false);
        pri_obs.setEnabled(false);
  
        
       } catch (SQLException ex) {
          System.out.println("ver error " + ex.getMessage());
        
       }
        }
        
        
    }//GEN-LAST:event_btn_updateActionPerformed

    private void pri_desKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pri_desKeyTyped
        ////convertir a mayusculas
        char c6 = evt.getKeyChar(); 
        if(Character.isLowerCase(c6)){
            String cad = ("" + c6).toUpperCase();
            c6 = cad.charAt(0);
            evt.setKeyChar(c6);
        }
    }//GEN-LAST:event_pri_desKeyTyped

    private void pri_obsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pri_obsKeyTyped
                ////convertir a mayusculas
        char c6 = evt.getKeyChar(); 
        if(Character.isLowerCase(c6)){
            String cad = ("" + c6).toUpperCase();
            c6 = cad.charAt(0);
            evt.setKeyChar(c6);
        }
    }//GEN-LAST:event_pri_obsKeyTyped

    private void cierrecajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cierrecajaActionPerformed
        if(cierrecaja.isSelected()){
           label_cierrecaja.setText("1");
       }else{
           label_cierrecaja.setText("0");
       }
            
    }//GEN-LAST:event_cierrecajaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(privilegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(privilegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(privilegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(privilegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new privilegio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox add_caja;
    public static javax.swing.JLabel add_caja_1;
    private javax.swing.JCheckBox add_cliente;
    public static javax.swing.JLabel add_cliente_1;
    private javax.swing.JCheckBox add_stock;
    public static javax.swing.JLabel add_stock_1;
    public static javax.swing.JLabel adm_privilegios;
    private javax.swing.JCheckBox adm_usuarios;
    private javax.swing.JCheckBox apariencia;
    public static javax.swing.JLabel apariencia_1;
    private javax.swing.JCheckBox base_datos;
    public static javax.swing.JLabel base_datos_lb;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_update;
    private javax.swing.JCheckBox caja;
    private javax.swing.JCheckBox cierrecaja;
    private javax.swing.JCheckBox cobranza;
    public static javax.swing.JLabel cobz;
    private javax.swing.JCheckBox compras;
    public static javax.swing.JLabel compras_1;
    public static javax.swing.JLabel config_1;
    private javax.swing.JCheckBox configuracion;
    public static javax.swing.JLabel confirmar_entre;
    private javax.swing.JCheckBox confirmar_entrega;
    public static javax.swing.JLabel cons_clie;
    public static javax.swing.JLabel cons_presu;
    public static javax.swing.JLabel cons_vende;
    private javax.swing.JCheckBox cons_ventas;
    public static javax.swing.JLabel cons_vta;
    private javax.swing.JCheckBox consu_cliente;
    private javax.swing.JCheckBox consu_presu;
    private javax.swing.JCheckBox consu_vendedor;
    private javax.swing.JCheckBox consultas;
    public static javax.swing.JLabel cotiza;
    private javax.swing.JCheckBox cotizaciones;
    private javax.swing.JCheckBox cpa;
    private javax.swing.JCheckBox gastos;
    private javax.swing.JCheckBox grupo_pro;
    public static javax.swing.JLabel grupo_pro_1;
    public static javax.swing.JLabel gtos;
    private javax.swing.JCheckBox informe;
    public static javax.swing.JLabel ingres;
    private javax.swing.JCheckBox ingresos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jtable_pri;
    public static javax.swing.JLabel label_cierrecaja;
    public static javax.swing.JLabel listad;
    private javax.swing.JCheckBox listado;
    private javax.swing.JCheckBox mov_caja;
    public static javax.swing.JLabel movimi;
    public static javax.swing.JLabel ped_realiz;
    private javax.swing.JCheckBox ped_realizados;
    public static javax.swing.JLabel presupu;
    private javax.swing.JCheckBox presupuesto;
    private javax.swing.JTextField pri_des;
    public static javax.swing.JTextField pri_id;
    private javax.swing.JTextField pri_obs;
    private javax.swing.JCheckBox pri_usuarios;
    public static javax.swing.JLabel privi_usuari;
    public static javax.swing.JLabel producto_1;
    private javax.swing.JCheckBox productos;
    private javax.swing.JCheckBox proveedores;
    public static javax.swing.JLabel proveedores_1;
    private javax.swing.JCheckBox registros;
    private javax.swing.JCheckBox saldo_caja;
    public static javax.swing.JLabel saldo_cja;
    private javax.swing.JCheckBox sistema;
    public static javax.swing.JLabel sucu_1;
    private javax.swing.JCheckBox sucursal;
    private javax.swing.JCheckBox ventas;
    private javax.swing.JCheckBox vta_1;
    public static javax.swing.JLabel vta_lb;
    // End of variables declaration//GEN-END:variables
}
