/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbstock;

import static dbstock.cliente.jTable_cliente;
import static dbstock.usuario.cmb_privilegios;
import java.awt.KeyEventPostProcessor;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URISyntaxException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Derlis
 */
public class proveedor  extends javax.swing.JFrame {

    Statement st;
    Connection con;
    public proveedor() {
        initComponents();
        
        this.setLocationRelativeTo(null);//centra el formulario
        this.setTitle("Registro de Proveedores");
        setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE); //inabilida el uso del boton exit X
        this.setResizable(false); //Disable the Resize Button
        
        
        
        pro_ruc.setEnabled(false);
        pro_empresa.setEnabled(false);
        pro_direccion.setEnabled(false);
        pro_telef.setEnabled(false);
        pro_correo.setEnabled(false);
        
          
          btn_usuguardar.setEnabled(false);
          btn_usuactualizar.setEnabled(false);
          btn_usueditar.setEnabled(false);
          btn_usueliminar.setEnabled(false);
          btn_usucalcelar.setEnabled(false);
          btn_usuexit.setEnabled(true);
          btn_usunuevo.requestFocus();
          BTN_WHATSAPP.setEnabled(false);
                ////cambiar icono del jframe
       // setIconImage(new ImageIcon(getClass().getResource("/img/user.png")).getImage());
        
       metodos.CARGAR_JTABLE_PROVEEDOR();
        
        //////////////////////////////////CIERRA LA VENTANA CON ESCAPE////////////////////////
        KeyboardFocusManager kb = KeyboardFocusManager.getCurrentKeyboardFocusManager();
        kb.addKeyEventPostProcessor(new KeyEventPostProcessor(){
            public boolean postProcessKeyEvent(KeyEvent e){
                if (e.getKeyCode() == KeyEvent.VK_ESCAPE && this != null){
                    //System.out.println("probando...");
                    dispose();
                    return false;
                }
                return true;
            }
        });
       ////////////////////////////////////////////////////////////////////////////////////////
   /*            addKeyListener(new KeyAdapter() {
               public void keyPressed(KeyEvent ke) {  // handler
        if(ke.getKeyCode() == ke.VK_ESCAPE) {
                       System.out.println("escaped ?");
                       setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE); // trying to close
                    } else {
                       System.out.println("not escaped");
                     }
              } 
           });*/
       /////////////////////////////////////////////////////////////////////////////////////////////
        
    }

    
     public void goToURL(String URL){
           if (java.awt.Desktop.isDesktopSupported()) {
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();

            if (desktop.isSupported(java.awt.Desktop.Action.BROWSE)) {
                try {
                    java.net.URI uri = new java.net.URI(URL);
                    desktop.browse(uri);
                } catch (URISyntaxException | IOException ex) {
                   // Logger.getLogger(Acerca.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_proveedor = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        pro_ruc = new javax.swing.JTextField();
        pro_empresa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pro_direccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pro_telef = new javax.swing.JTextField();
        btn_usunuevo = new javax.swing.JButton();
        btn_usuguardar = new javax.swing.JButton();
        btn_usueditar = new javax.swing.JButton();
        btn_usucalcelar = new javax.swing.JButton();
        btn_usueliminar = new javax.swing.JButton();
        btn_usuexit = new javax.swing.JButton();
        btn_usuactualizar = new javax.swing.JButton();
        pro_correo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BTN_WHATSAPP = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(760, 415));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("REGISTRO DE PROVEEDORES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jTable_proveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_proveedorMouseClicked(evt);
            }
        });
        jTable_proveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable_proveedorKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_proveedor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 360, 220));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Denominación:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        pro_ruc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pro_rucFocusLost(evt);
            }
        });
        pro_ruc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pro_rucKeyPressed(evt);
            }
        });
        getContentPane().add(pro_ruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 140, -1));

        pro_empresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pro_empresaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pro_empresaKeyTyped(evt);
            }
        });
        getContentPane().add(pro_empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 370, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("RUC:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Dirección");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));

        pro_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pro_direccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pro_direccionKeyTyped(evt);
            }
        });
        getContentPane().add(pro_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 370, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Correo Electronico");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 20));

        pro_telef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pro_telefActionPerformed(evt);
            }
        });
        pro_telef.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pro_telefKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pro_telefKeyTyped(evt);
            }
        });
        getContentPane().add(pro_telef, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 150, -1));

        btn_usunuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/add-file.png"))); // NOI18N
        btn_usunuevo.setText("Nuevo");
        btn_usunuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usunuevoActionPerformed(evt);
            }
        });
        btn_usunuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_usunuevoKeyPressed(evt);
            }
        });
        getContentPane().add(btn_usunuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 100, 40));

        btn_usuguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/save.png"))); // NOI18N
        btn_usuguardar.setText("Guardar");
        btn_usuguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuguardarActionPerformed(evt);
            }
        });
        btn_usuguardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_usuguardarKeyPressed(evt);
            }
        });
        getContentPane().add(btn_usuguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 110, 40));

        btn_usueditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/editar.png"))); // NOI18N
        btn_usueditar.setText("Editar");
        btn_usueditar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_usueditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usueditarActionPerformed(evt);
            }
        });
        btn_usueditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_usueditarKeyPressed(evt);
            }
        });
        getContentPane().add(btn_usueditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 100, 40));

        btn_usucalcelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/x-button.png"))); // NOI18N
        btn_usucalcelar.setText("Cancelar");
        btn_usucalcelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usucalcelarActionPerformed(evt);
            }
        });
        btn_usucalcelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_usucalcelarKeyPressed(evt);
            }
        });
        getContentPane().add(btn_usucalcelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 110, 40));

        btn_usueliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/eliminar.png"))); // NOI18N
        btn_usueliminar.setText("Eliminar");
        btn_usueliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usueliminarActionPerformed(evt);
            }
        });
        btn_usueliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_usueliminarKeyPressed(evt);
            }
        });
        getContentPane().add(btn_usueliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 110, 40));

        btn_usuexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/exit.png"))); // NOI18N
        btn_usuexit.setText("Salir");
        btn_usuexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuexitActionPerformed(evt);
            }
        });
        btn_usuexit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_usuexitKeyPressed(evt);
            }
        });
        getContentPane().add(btn_usuexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 110, 40));

        btn_usuactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/reload.png"))); // NOI18N
        btn_usuactualizar.setText("Actualizar");
        btn_usuactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuactualizarActionPerformed(evt);
            }
        });
        btn_usuactualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_usuactualizarKeyPressed(evt);
            }
        });
        getContentPane().add(btn_usuactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 110, 40));

        pro_correo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pro_correoFocusLost(evt);
            }
        });
        pro_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pro_correoActionPerformed(evt);
            }
        });
        pro_correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pro_correoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pro_correoKeyTyped(evt);
            }
        });
        getContentPane().add(pro_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 310, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Telefono");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 20));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("Contactar por WhatsApp");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 40));

        BTN_WHATSAPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/whatsapp.png"))); // NOI18N
        BTN_WHATSAPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_WHATSAPPActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_WHATSAPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/fondosistema.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 770, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_usunuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usunuevoActionPerformed
        pro_ruc.setEnabled(true);
        pro_empresa.setEnabled(true);
        pro_direccion.setEnabled(true);
        pro_telef.setEnabled(true);
        pro_correo.setEnabled(true);

        btn_usunuevo.setEnabled(false);
        btn_usuguardar.setEnabled(true);
        btn_usuactualizar.setEnabled(false);
        btn_usueditar.setEnabled(false);
        btn_usueliminar.setEnabled(false);
        btn_usucalcelar.setEnabled(true);
        btn_usuexit.setEnabled(true);
        
        pro_ruc.requestFocus();
        

    }//GEN-LAST:event_btn_usunuevoActionPerformed

    private void btn_usuguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuguardarActionPerformed

        int aux  =  JOptionPane.showConfirmDialog(null, "Desea Guardar el Registro?","OBSERVACION", JOptionPane.YES_NO_OPTION);
        if(aux == JOptionPane.YES_OPTION){

            Conexion cc=new Conexion();
            Connection con=cc.conectar();
            try {

                String sql = "INSERT INTO proveedores (pro_empresa, pro_ruc, pro_direccion,pro_telefono,pro_correo) "
                + "values ('"+pro_empresa.getText()+"','"+pro_ruc.getText()+"','"+pro_direccion.getText()+"','"+pro_telef.getText()+"','"+pro_correo.getText()+"')";
               

                st = con.createStatement();
                st.execute(sql);
                metodos.CARGAR_JTABLE_PROVEEDOR();

                btn_usunuevo.setEnabled(true);
                btn_usuexit.setEnabled(true);
                btn_usueditar.setEnabled(false);
                btn_usueliminar.setEnabled(false);
                btn_usuguardar.setEnabled(false);
                btn_usucalcelar.setEnabled(false);
                
                        pro_ruc.setEnabled(false);
                        pro_empresa.setEnabled(false);
                        pro_direccion.setEnabled(false);
                        pro_telef.setEnabled(false);
                        pro_correo.setEnabled(false);
                        
                        pro_ruc.setText("");
                        pro_empresa.setText("");
                        pro_direccion.setText("");
                        pro_telef.setText("");
                        pro_correo.setText("");
                        
                        btn_usunuevo.doClick();

            } catch (SQLException ex) {
                System.out.println("ver error " + ex.getMessage());

            }
        }

    }//GEN-LAST:event_btn_usuguardarActionPerformed

    private void btn_usueditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usueditarActionPerformed

        pro_ruc.setEnabled(true);
        pro_empresa.setEnabled(true);
        pro_direccion.setEnabled(true);
        pro_telef.setEnabled(true);
        pro_correo.setEnabled(true);

        btn_usuguardar.setVisible(false);
        btn_usuactualizar.setVisible(true);

        btn_usunuevo.setEnabled(false);
        btn_usuguardar.setEnabled(false);
        btn_usuactualizar.setEnabled(true);
        btn_usueditar.setEnabled(false);
        btn_usueliminar.setEnabled(false);
        btn_usucalcelar.setEnabled(true);
        btn_usuexit.setEnabled(true);

    }//GEN-LAST:event_btn_usueditarActionPerformed

    private void btn_usucalcelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usucalcelarActionPerformed

        int aux  =  JOptionPane.showConfirmDialog(null, "Desea Cancelar Registro?","OBSERVACION", JOptionPane.YES_NO_OPTION);
        if(aux == JOptionPane.YES_OPTION){

        pro_ruc.setEnabled(false);
        pro_empresa.setEnabled(false);
        pro_direccion.setEnabled(false);
        pro_telef.setEnabled(false);
        pro_correo.setEnabled(false);
                
            btn_usuguardar.setVisible(true);
            btn_usunuevo.setEnabled(true);
            btn_usuguardar.setEnabled(false);
            btn_usuactualizar.setEnabled(false);
            btn_usueditar.setEnabled(false);
            btn_usueliminar.setEnabled(false);
            btn_usucalcelar.setEnabled(false);
            btn_usuexit.setEnabled(true);

        }

    }//GEN-LAST:event_btn_usucalcelarActionPerformed

    private void btn_usueliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usueliminarActionPerformed

        int aux  =  JOptionPane.showConfirmDialog(null, "Desea eliminar ","Sistema Ficha del cliente", JOptionPane.YES_NO_OPTION);

        if(aux == JOptionPane.YES_OPTION){

            int nz = jTable_proveedor.getSelectedRow();
            String id = jTable_proveedor.getValueAt(nz, 0).toString();
            pro_ruc.setText(id);

            Conexion cc=new Conexion();
            Connection con=cc.conectar();

            try {

                String sql = "delete from provedores where pro_ruc = '"+pro_ruc.getText()+"' ";
                st = con.createStatement();

                st.execute(sql);

                metodos.CARGAR_JTABLE();

                pro_ruc.setText("");
                pro_empresa.setText("");
                pro_direccion.setText("");
                pro_telef.setText("");
                pro_correo.setText("");
                // cmb_privilegios.setText("");

                pro_ruc.setEnabled(false);
                pro_empresa.setEnabled(false);
                pro_direccion.setEnabled(false);
                pro_telef.setEnabled(false);
                pro_correo.setEnabled(false);
                
                btn_usuguardar.setVisible(true);
                btn_usunuevo.setEnabled(true);
                btn_usuguardar.setEnabled(false);
                btn_usuactualizar.setEnabled(false);
                btn_usueditar.setEnabled(false);
                btn_usueliminar.setEnabled(false);
                btn_usucalcelar.setEnabled(false);
                btn_usuexit.setEnabled(true);

            }catch (Exception ee) {
                ee.printStackTrace();
            }

        }else{if(aux == JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(null,  "Cancelado", "Sistema", JOptionPane.INFORMATION_MESSAGE);

        }

        }

    }//GEN-LAST:event_btn_usueliminarActionPerformed

    private void btn_usuexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuexitActionPerformed
        dispose();

    }//GEN-LAST:event_btn_usuexitActionPerformed

    private void btn_usuactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuactualizarActionPerformed

        int aux  =  JOptionPane.showConfirmDialog(null, "Desea Actualizar los Datos","OBSERVACION", JOptionPane.YES_NO_OPTION);
        if(aux == JOptionPane.YES_OPTION){

            Conexion cc=new Conexion();
            Connection con=cc.conectar();
            try {

                String sql = "UPDATE proveedores SET pro_empresa = '"+pro_empresa.getText()+"', pro_ruc = '"+pro_ruc.getText()+"',"
                + " pro_direccion= '"+pro_direccion.getText()+"', pro_telefono= '"+pro_telef.getText()+"',pro_correo = '"+pro_correo.getText()+"' where pro_ruc = '"+pro_ruc.getText()+"'";

                st = con.createStatement();

                st.execute(sql);

                JOptionPane.showMessageDialog(null,  "Registro Actualizado", "Usuarios", JOptionPane.INFORMATION_MESSAGE);

                metodos.CARGAR_JTABLE_PROVEEDOR();

                btn_usuguardar.setVisible(true);
                btn_usuactualizar.setVisible(false);

                btn_usunuevo.setEnabled(true);
                btn_usuguardar.setEnabled(false);
                btn_usuactualizar.setEnabled(false);
                btn_usueditar.setEnabled(false);
                btn_usueliminar.setEnabled(false);
                btn_usucalcelar.setEnabled(false);
                btn_usuexit.setEnabled(true);

                metodos.CARGAR_JTABLE_PROVEEDOR();
                pro_ruc.setEnabled(false);
                pro_empresa.setEnabled(false);
                pro_direccion.setEnabled(false);
                pro_telef.setEnabled(false);
                pro_correo.setEnabled(false);

            } catch (SQLException ex) {
                System.out.println("ver error " + ex.getMessage());

            }
        }

    }//GEN-LAST:event_btn_usuactualizarActionPerformed

    private void pro_empresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pro_empresaKeyTyped
        
        ////convertir a mayusculas
        char c6 = evt.getKeyChar(); 
        if(Character.isLowerCase(c6)){
            String cad = ("" + c6).toUpperCase();
            c6 = cad.charAt(0);
            evt.setKeyChar(c6);
        }
    }//GEN-LAST:event_pro_empresaKeyTyped

    private void pro_direccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pro_direccionKeyTyped
       
        ////convertir a mayusculas
        char c6 = evt.getKeyChar(); 
        if(Character.isLowerCase(c6)){
            String cad = ("" + c6).toUpperCase();
            c6 = cad.charAt(0);
            evt.setKeyChar(c6);
        }
        
    }//GEN-LAST:event_pro_direccionKeyTyped

    private void pro_telefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pro_telefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pro_telefActionPerformed

    private void pro_telefKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pro_telefKeyTyped
        ////convertir a mayusculas
        char c6 = evt.getKeyChar(); 
        if(Character.isLowerCase(c6)){
            String cad = ("" + c6).toUpperCase();
            c6 = cad.charAt(0);
            evt.setKeyChar(c6);
        }
    }//GEN-LAST:event_pro_telefKeyTyped

    private void jTable_proveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_proveedorMouseClicked
        
                pro_ruc.setEnabled(false);
                pro_empresa.setEnabled(false);
                pro_direccion.setEnabled(false);
                pro_telef.setEnabled(false);
                pro_correo.setEnabled(false);
        
          btn_usunuevo.setEnabled(true);
          btn_usuguardar.setEnabled(false);
          btn_usuactualizar.setEnabled(false);
          btn_usueditar.setEnabled(true);
          btn_usueliminar.setEnabled(true);
          btn_usucalcelar.setEnabled(false);
          btn_usuexit.setEnabled(true);
          
          BTN_WHATSAPP.setEnabled(true);
        
        int n2 = jTable_proveedor.getSelectedRow();
        String id = jTable_proveedor.getValueAt(n2, 0).toString();
        pro_ruc.setText(id);
        
 		Conexion cc=new Conexion();
		Connection con=cc.conectar();;
        	try {

		String sql = "Select * from proveedores where pro_ruc = '"+pro_ruc.getText()+"'";
		//ResultSet resultado = st.executeQuery(sql);
                st = con.createStatement();
                ResultSet rs=st.executeQuery(sql);
		if (rs.next()) {
                        pro_empresa.setText(rs.getString("pro_empresa"));
                        pro_ruc.setText(rs.getString("pro_ruc"));
                        pro_direccion.setText(rs.getString("pro_direccion"));
                        pro_telef.setText(rs.getString("pro_telefono"));
                        pro_correo.setText(rs.getString("pro_correo"));
                        
                    }
			rs.close();
			st.close();
			con.close();

		} catch (SQLException e) {
			JOptionPane.showMessageDialog(null, e.getMessage());
		}
        
    }//GEN-LAST:event_jTable_proveedorMouseClicked

    private void pro_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pro_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pro_correoActionPerformed

    private void pro_correoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pro_correoKeyTyped
        ////convertir a mayusculas
        char c6 = evt.getKeyChar(); 
        if(Character.isLowerCase(c6)){
            String cad = ("" + c6).toUpperCase();
            c6 = cad.charAt(0);
            evt.setKeyChar(c6);
        }
    }//GEN-LAST:event_pro_correoKeyTyped

    private void pro_rucFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pro_rucFocusLost
        pro_empresa.requestFocus();
    }//GEN-LAST:event_pro_rucFocusLost

    private void btn_usunuevoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_usunuevoKeyPressed
         if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
             btn_usunuevo.doClick();
         }
         
           if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }
             
    }//GEN-LAST:event_btn_usunuevoKeyPressed

    private void pro_correoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pro_correoFocusLost
        btn_usuguardar.requestFocus();
    }//GEN-LAST:event_pro_correoFocusLost

    private void btn_usuguardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_usuguardarKeyPressed
        int key = evt.getKeyCode();
        if (key == com.sun.glass.events.KeyEvent.VK_ENTER) {
            btn_usuguardar.doClick();
        }
        
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }
    }//GEN-LAST:event_btn_usuguardarKeyPressed

    private void pro_rucKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pro_rucKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }
    }//GEN-LAST:event_pro_rucKeyPressed

    private void pro_empresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pro_empresaKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_pro_empresaKeyPressed

    private void pro_direccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pro_direccionKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_pro_direccionKeyPressed

    private void pro_telefKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pro_telefKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_pro_telefKeyPressed

    private void pro_correoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pro_correoKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_pro_correoKeyPressed

    private void jTable_proveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable_proveedorKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_proveedorKeyPressed

    private void btn_usueditarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_usueditarKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_usueditarKeyPressed

    private void btn_usucalcelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_usucalcelarKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_usucalcelarKeyPressed

    private void btn_usueliminarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_usueliminarKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_usueliminarKeyPressed

    private void btn_usuexitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_usuexitKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_usuexitKeyPressed

    private void btn_usuactualizarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_usuactualizarKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
             btn_usuexit.doClick();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_usuactualizarKeyPressed

    private void BTN_WHATSAPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_WHATSAPPActionPerformed
        goToURL("https://api.whatsapp.com/send?phone=+595'"+pro_telef.getText()+"'");
        ///https://api.whatsapp.com/send?phone=+595973543110
    }//GEN-LAST:event_BTN_WHATSAPPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_WHATSAPP;
    private javax.swing.JButton btn_usuactualizar;
    private javax.swing.JButton btn_usucalcelar;
    private javax.swing.JButton btn_usueditar;
    private javax.swing.JButton btn_usueliminar;
    private javax.swing.JButton btn_usuexit;
    private javax.swing.JButton btn_usuguardar;
    private javax.swing.JButton btn_usunuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_proveedor;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField pro_correo;
    private javax.swing.JTextField pro_direccion;
    private javax.swing.JTextField pro_empresa;
    private javax.swing.JTextField pro_ruc;
    private javax.swing.JTextField pro_telef;
    // End of variables declaration//GEN-END:variables
}
