/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbstock;

import static dbstock.cliente.jTable_cliente;
import java.net.URL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Derlis
 */
public class sucursal extends javax.swing.JFrame {

    /**
     * Creates new form sucursal
     */
    Statement st;
    Connection con;
    
    public sucursal() {
        initComponents();
        
        this.setTitle("Registro de Sucursales");
        this.setLocationRelativeTo(null);//centra el formulario
        setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE); //inabilida el uso del boton exit X
        this.setResizable(false); //Disable the Resize Button
        
        metodos.CARGAR_JTABLE_SUC();
        
            su_codigo.setEnabled(false);
            su_descri.setEnabled(false);
            su_direc.setEnabled(false);
            su_telef.setEnabled(false);
            
          btn_usuguardar.setEnabled(false);
          btn_usuactualizar.setEnabled(false);
          btn_usueditar.setEnabled(false);
          btn_usueliminar.setEnabled(false);
          btn_usucalcelar.setEnabled(false);
          btn_usuexit.setEnabled(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable_sucursal = new javax.swing.JTable();
        su_codigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        su_descri = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        su_direc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        su_telef = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn_usunuevo = new javax.swing.JButton();
        btn_usuguardar = new javax.swing.JButton();
        btn_usueditar = new javax.swing.JButton();
        btn_usucalcelar = new javax.swing.JButton();
        btn_usueliminar = new javax.swing.JButton();
        btn_usuexit = new javax.swing.JButton();
        btn_usuactualizar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");
        jPopupMenu1.add(jMenuItem1);

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("REGISTRO DE SUCURSAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jtable_sucursal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable_sucursal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_sucursalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtable_sucursal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 390, 180));

        su_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                su_codigoKeyTyped(evt);
            }
        });
        getContentPane().add(su_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 50, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Codigo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        su_descri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                su_descriKeyTyped(evt);
            }
        });
        getContentPane().add(su_descri, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 220, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Descripcion");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));

        su_direc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                su_direcKeyTyped(evt);
            }
        });
        getContentPane().add(su_direc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 220, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Direccion");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 20));

        su_telef.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                su_telefKeyTyped(evt);
            }
        });
        getContentPane().add(su_telef, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 140, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Telefono");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        btn_usunuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/add-file.png"))); // NOI18N
        btn_usunuevo.setText("Nuevo");
        btn_usunuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usunuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usunuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, 40));

        btn_usuguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/save.png"))); // NOI18N
        btn_usuguardar.setText("Guardar");
        btn_usuguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usuguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 110, 40));

        btn_usueditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/editar.png"))); // NOI18N
        btn_usueditar.setText("Editar");
        btn_usueditar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_usueditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usueditarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usueditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 100, 40));

        btn_usucalcelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/x-button.png"))); // NOI18N
        btn_usucalcelar.setText("Cancelar");
        btn_usucalcelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usucalcelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usucalcelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 110, 40));

        btn_usueliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/eliminar.png"))); // NOI18N
        btn_usueliminar.setText("Eliminar");
        btn_usueliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usueliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usueliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 110, 40));

        btn_usuexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/exit.png"))); // NOI18N
        btn_usuexit.setText("Salir");
        btn_usuexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuexitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usuexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 110, 40));

        btn_usuactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/reload.png"))); // NOI18N
        btn_usuactualizar.setText("Actualizar");
        btn_usuactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuactualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usuactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 110, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/printer14.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 50, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbstock/img/fondosistema.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void su_codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_su_codigoKeyTyped
        ////convertir a mayusculas
        char c6 = evt.getKeyChar();
        if(Character.isLowerCase(c6)){
            String cad = ("" + c6).toUpperCase();
            c6 = cad.charAt(0);
            evt.setKeyChar(c6);
        }
    }//GEN-LAST:event_su_codigoKeyTyped

    private void su_descriKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_su_descriKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_su_descriKeyTyped

    private void su_direcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_su_direcKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_su_direcKeyTyped

    private void su_telefKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_su_telefKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_su_telefKeyTyped

    private void btn_usunuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usunuevoActionPerformed

        su_codigo.setText("");
        su_descri.setText("");
        su_direc.setText("");
        su_telef.setText("");

        su_codigo.setEnabled(true);
        su_descri.setEnabled(true);
        su_direc.setEnabled(true);
        su_telef.setEnabled(true);

        btn_usunuevo.setEnabled(false);
        btn_usuguardar.setEnabled(true);
        btn_usuactualizar.setEnabled(false);
        btn_usueditar.setEnabled(false);
        btn_usueliminar.setEnabled(false);
        btn_usucalcelar.setEnabled(true);
        btn_usuexit.setEnabled(true);
    }//GEN-LAST:event_btn_usunuevoActionPerformed

    private void btn_usuguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuguardarActionPerformed

        // if (cli_cedula.equals("")  && cli_nombre.equals("")  && cli_direccion.equals("")  && cli_telefono.equals("") ) {

            if ( (su_codigo != null) && (su_codigo.equals(""))  ) {
                JOptionPane.showMessageDialog(null, "Un campo esa vacio, Favor llenar todos los Datos ");
            }else{

                int aux  =  JOptionPane.showConfirmDialog(null, "Desea Guardar el Registro?","OBSERVACION", JOptionPane.YES_NO_OPTION);
                if(aux == JOptionPane.YES_OPTION){

                    Conexion cc=new Conexion();
                    Connection con=cc.conectar();
                    try {

                        String sql = "INSERT INTO sucursal (su_codigo, su_descri, su_direc,su_telef) "
                        + "values ('"+su_codigo.getText()+"','"+su_descri.getText()+"','"+su_direc.getText()+"','"+su_telef.getText()+"')";

                        st = con.createStatement();
                        st.execute(sql);
                        metodos.CARGAR_JTABLE_SUC();

                        btn_usueditar.setEnabled(true);
                        btn_usueliminar.setEnabled(true);

                    } catch (SQLException ex) {
                        System.out.println("ver error " + ex.getMessage());

                    }
                }
            }//cierre de if else

    }//GEN-LAST:event_btn_usuguardarActionPerformed

    private void btn_usueditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usueditarActionPerformed

        su_codigo.setEnabled(true);
        su_descri.setEnabled(true);
        su_direc.setEnabled(true);
        su_telef.setEnabled(true);

        btn_usuguardar.setVisible(false);
        btn_usuactualizar.setVisible(true);

        btn_usunuevo.setEnabled(false);
        btn_usuguardar.setEnabled(false);
        btn_usuactualizar.setEnabled(true);
        btn_usueditar.setEnabled(false);
        btn_usueliminar.setEnabled(false);
        btn_usucalcelar.setEnabled(true);
        btn_usuexit.setEnabled(true);
    }//GEN-LAST:event_btn_usueditarActionPerformed

    private void btn_usucalcelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usucalcelarActionPerformed

        int aux  =  JOptionPane.showConfirmDialog(null, "Desea Cancelar Registro?","OBSERVACION", JOptionPane.YES_NO_OPTION);
        if(aux == JOptionPane.YES_OPTION){

            su_codigo.setEnabled(false);
            su_descri.setEnabled(false);
            su_direc.setEnabled(false);
            su_telef.setEnabled(false);


            btn_usuguardar.setVisible(true);
            btn_usunuevo.setEnabled(true);
            btn_usuguardar.setEnabled(false);
            btn_usuactualizar.setEnabled(false);
            btn_usueditar.setEnabled(false);
            btn_usueliminar.setEnabled(false);
            btn_usucalcelar.setEnabled(false);
            btn_usuexit.setEnabled(true);

        }
    }//GEN-LAST:event_btn_usucalcelarActionPerformed

    private void btn_usueliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usueliminarActionPerformed

        int aux  =  JOptionPane.showConfirmDialog(null, "Desea eliminar ","Sistema", JOptionPane.YES_NO_OPTION);

        if(aux == JOptionPane.YES_OPTION){

            int nz = jtable_sucursal.getSelectedRow();
            String id = jtable_sucursal.getValueAt(nz, 0).toString();
            su_codigo.setText(id);

            Conexion cc=new Conexion();
            Connection con=cc.conectar();

            try {

                String sql = "delete from sucursal where su_codigo = '"+su_codigo.getText()+"' ";
                st = con.createStatement();

                st.execute(sql);

                metodos.CARGAR_JTABLE_SUC();

                su_codigo.setText("");
                su_descri.setText("");
                su_direc.setText("");
                su_telef.setText("");
                // cmb_privilegios.setText("");

                su_codigo.setEnabled(false);
                su_descri.setEnabled(false);
                su_direc.setEnabled(false);
                su_telef.setEnabled(false);

                btn_usuguardar.setVisible(true);
                btn_usunuevo.setEnabled(true);
                btn_usuguardar.setEnabled(false);
                btn_usuactualizar.setEnabled(false);
                btn_usueditar.setEnabled(false);
                btn_usueliminar.setEnabled(false);
                btn_usucalcelar.setEnabled(false);
                btn_usuexit.setEnabled(true);

            }catch (Exception ee) {
                ee.printStackTrace();
            }

        }else{if(aux == JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(null,  "Cancelado", "Sistema", JOptionPane.INFORMATION_MESSAGE);

        }

        }
    }//GEN-LAST:event_btn_usueliminarActionPerformed

    private void btn_usuexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuexitActionPerformed
        dispose();

  
    }//GEN-LAST:event_btn_usuexitActionPerformed

    private void btn_usuactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuactualizarActionPerformed

        int aux  =  JOptionPane.showConfirmDialog(null, "Desea Actualizar los Datos","OBSERVACION", JOptionPane.YES_NO_OPTION);
        if(aux == JOptionPane.YES_OPTION){

            Conexion cc=new Conexion();
            Connection con=cc.conectar();
            try {

                String sql = "UPDATE sucursal SET su_codigo = '"+su_codigo.getText()+"', su_descri = '"+su_descri.getText()+"',"
                + " su_direc= '"+su_direc.getText()+"', su_telef= '"+su_telef.getText()+"' where su_codigo = '"+su_codigo.getText()+"'";

                st = con.createStatement();

                st.execute(sql);

                JOptionPane.showMessageDialog(null,  "Registro Actualizado", "Clientes", JOptionPane.INFORMATION_MESSAGE);

                metodos.CARGAR_JTABLE_SUC();

                btn_usuguardar.setVisible(true);
                btn_usuactualizar.setVisible(false);

                btn_usunuevo.setEnabled(true);
                btn_usuguardar.setEnabled(false);
                btn_usuactualizar.setEnabled(false);
                btn_usueditar.setEnabled(false);
                btn_usueliminar.setEnabled(false);
                btn_usucalcelar.setEnabled(false);
                btn_usuexit.setEnabled(true);

               // metodos.CARGAR_JTABLE_cliente();
                su_codigo.setEnabled(false);
                su_descri.setEnabled(false);
                su_direc.setEnabled(false);
                su_telef.setEnabled(false);

            } catch (SQLException ex) {
                System.out.println("ver error " + ex.getMessage());

            }
        }
    }//GEN-LAST:event_btn_usuactualizarActionPerformed

    private void jtable_sucursalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_sucursalMouseClicked
        su_codigo.setEnabled(false);
        su_descri.setEnabled(false);
        su_direc.setEnabled(false);
        su_telef.setEnabled(false);
        
          btn_usunuevo.setEnabled(true);
          btn_usuguardar.setEnabled(false);
          btn_usuactualizar.setEnabled(false);
          btn_usueditar.setEnabled(true);
          btn_usueliminar.setEnabled(true);
          btn_usucalcelar.setEnabled(false);
          btn_usuexit.setEnabled(true);
        
        int n1 = jtable_sucursal.getSelectedRow();
        String id = jtable_sucursal.getValueAt(n1, 0).toString();
        su_codigo.setText(id);
        
 		Conexion cc=new Conexion();
		Connection con=cc.conectar();;
        	try {

		String sql = "Select * from sucursal where su_codigo = '"+su_codigo.getText()+"'";
		//ResultSet resultado = st.executeQuery(sql);
                st = con.createStatement();
                ResultSet rs=st.executeQuery(sql);
		if (rs.next()) {
                        su_codigo.setText(rs.getString("su_codigo"));
                        su_descri.setText(rs.getString("su_descri"));
                        su_direc.setText(rs.getString("su_direc"));
                        su_telef.setText(rs.getString("su_telef"));
                       // cmb_privilegios.setSelectedItem("usu_privilegios");         //***************************

                    }
			rs.close();
			st.close();
			con.close();

		} catch (SQLException e) {
			JOptionPane.showMessageDialog(null, e.getMessage());
		}
    }//GEN-LAST:event_jtable_sucursalMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        
                Conexion cc=new Conexion();
		Connection con=cc.conectar();
                try {
                URL master = this.getClass().getResource("/reporte/sucursal.jasper");
         
                if (master == null) {
                    System.out.println("No se encontro el archivo");                   
                    //System.exit(0);
                }
                
                JasperReport masterreport = null;
                try {
                    masterreport = (JasperReport) JRLoader.loadObject(master);
          
                } catch (Exception e) {
                    System.out.println("error al cargar reporte " + e.getMessage());                 
                }
                    Map parametros= new HashMap();
                    //parametros.put("documento", Ficha_Cliente.txt_docu.getText());
                    JasperPrint print = JasperFillManager.fillReport(masterreport, parametros, con);
                    JasperViewer ver = new JasperViewer(print,false);
                    ver.setTitle("Registro de Sucursal");
                    ver.setVisible(true);
            } catch (Exception e) {
                System.out.println("reporte.reporte.Reportefichaupdate()" + e);      
            }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sucursal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_usuactualizar;
    private javax.swing.JButton btn_usucalcelar;
    private javax.swing.JButton btn_usueditar;
    private javax.swing.JButton btn_usueliminar;
    private javax.swing.JButton btn_usuexit;
    private javax.swing.JButton btn_usuguardar;
    private javax.swing.JButton btn_usunuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jtable_sucursal;
    private javax.swing.JTextField su_codigo;
    private javax.swing.JTextField su_descri;
    private javax.swing.JTextField su_direc;
    private javax.swing.JTextField su_telef;
    // End of variables declaration//GEN-END:variables
}
